"""
Django settings for jizz project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ds-@$v6b_arl76ud+m*lzyk2qn0%3+xcyxcfu#i53sxt_lw-48'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',  # OAuth callback must use same host as login start; add for local dev
    'jizz.be',
    'www.jizz.be',
    'birdr.pro',
    'www.birdr.pro',
    'birdr.nl',
    'www.birdr.nl',
    'goedloek.nl',
    'www.goedloek.nl',
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'jizz',  # Put jizz before django.contrib.admin so our templates are found first
    'compare',  # Species comparison app
    'media',  # Media files app (Image, Video, Audio)
    'django_quill',  # Quill rich text editor (admin + forms)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'oauth2_provider',
    'social_django',
    'rest_framework_social_oauth2',
]

# Use database sessions so OAuth state survives redirects and is shared across processes (e.g. runserver + Daphne).
# Prevents "Session value state missing" when Google redirects back to /auth/complete/.
# Run `manage.py migrate` so the session table exists.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Ensure session cookie is sent when Google redirects (GET) back to our callback.
SESSION_COOKIE_SAMESITE = 'Lax'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'jizz.middleware.SocialAuthRedirectUriMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jizz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'jizz' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jizz.wsgi.application'
ASGI_APPLICATION = "jizz.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'django/'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# When not in debug (e.g. production behind HTTPS proxy), trust X-Forwarded-Proto
# so request.build_absolute_uri() returns https URLs (e.g. avatar_url).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration (can be overridden in local.py or production.py)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'info@birdr.pro')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'info@birdr.pro')

# Password reset link expiry (seconds; default_token_generator uses this)
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours


AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'jizz.backends.AppleIdAuth',  # custom: loads .p8 with cryptography for PyJWT
    'django.contrib.auth.backends.ModelBackend',
)

# Social OAuth2 settings
# Get from environment variables or set directly
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', '<YOUR_GOOGLE_CLIENT_ID>')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', '<YOUR_GOOGLE_CLIENT_SECRET>')
# Request profile and email scopes to get user name and avatar
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]

# Apple Sign In (redirect flow). KEY and TEAM must be non-empty strings for PyJWT.
SOCIAL_AUTH_APPLE_ID_CLIENT = os.environ.get('SOCIAL_AUTH_APPLE_ID_CLIENT', '')
_apple_secret_file = os.environ.get('SOCIAL_AUTH_APPLE_ID_SECRET_FILE')
if _apple_secret_file and os.path.isfile(_apple_secret_file):
    with open(_apple_secret_file, 'r') as f:
        SOCIAL_AUTH_APPLE_ID_SECRET = f.read()
else:
    _secret = os.environ.get('SOCIAL_AUTH_APPLE_ID_SECRET', '')
    SOCIAL_AUTH_APPLE_ID_SECRET = _secret.replace('\\n', '\n') if _secret else ''
# Key ID (kid) and Team ID must be strings; empty will break redirect flow
SOCIAL_AUTH_APPLE_ID_KEY = str(os.environ.get('SOCIAL_AUTH_APPLE_ID_KEY', '') or '')
SOCIAL_AUTH_APPLE_ID_TEAM = str(os.environ.get('SOCIAL_AUTH_APPLE_ID_TEAM', '') or '')
# Bundle ID of the native iOS app; native Sign in with Apple uses this as token audience (default: pro.birdr.app)
SOCIAL_AUTH_APPLE_ID_BUNDLE_ID = os.environ.get('SOCIAL_AUTH_APPLE_ID_BUNDLE_ID', 'pro.birdr.app')

SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_AZUREAD_OAUTH2_KEY', '<YOUR_MICROSOFT_CLIENT_ID>')
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET', '<YOUR_MICROSOFT_SECRET>')
SOCIAL_AUTH_AZUREAD_TENANT_ID = os.environ.get('SOCIAL_AUTH_AZUREAD_TENANT_ID', '<YOUR_MICROSOFT_TENANT_ID>')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'jizz.authentication.PlayerTokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # Removed SocialAuthentication from default - it causes issues with anonymous requests
        # It can be added to specific views that need it
        # 'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ],
   'DEFAULT_FILTER_BACKENDS': [
       'rest_framework.filters.OrderingFilter'
   ],
   'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
   'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1000),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # Temporarily disable to test if blacklisting is the issue
}

# Keep Google keys from env (set above); do not overwrite with placeholders
SOCIAL_AUTH_APPLE_ID_CLIENT = SOCIAL_AUTH_APPLE_ID_CLIENT or '<YOUR_APPLE_CLIENT_ID>'
if not (SOCIAL_AUTH_APPLE_ID_SECRET or '').strip().startswith('-----BEGIN'):
    SOCIAL_AUTH_APPLE_ID_SECRET = '<YOUR_APPLE_SECRET>'
SOCIAL_AUTH_APPLE_ID_KEY = SOCIAL_AUTH_APPLE_ID_KEY if (SOCIAL_AUTH_APPLE_ID_KEY or '') else ''
SOCIAL_AUTH_APPLE_ID_TEAM = SOCIAL_AUTH_APPLE_ID_TEAM if (SOCIAL_AUTH_APPLE_ID_TEAM or '') else ''

SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = '<YOUR_MICROSOFT_CLIENT_ID>'
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = '<YOUR_MICROSOFT_CLIENT_SECRET>'
SOCIAL_AUTH_AZUREAD_TENANT_ID = '<YOUR_TENANT_ID>'

SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://localhost:3000/login/google'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://jizz.be",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
CORS_ALLOW_HEADERS = ["*"]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = None
# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# eBird API (for taxonomy, species lists, etc.)
EBIRD_API_TOKEN = os.environ.get('EBIRD_API_TOKEN', '')

# eBird Status and Trends (for regional abundance CSV downloads); get key at https://ebird.org/st/request
EBIRD_ST_ACCESS_KEY = os.environ.get('EBIRD_ST_ACCESS_KEY', '')

# Ensure errors are visible in the server process (runserver, gunicorn, etc.)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stderr',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'jizz': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'django.request': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

DKIM_KEY = "dkim-key"
DEFAULT_FROM_EMAIL = "Birdr <info@birdr.pro>"
