"""Additional marketing copy. Same locale order as catalogs._LOCALES: nl, es, fr, de, it, pt-BR, ja."""

# English msgid, then translations in locale order.
EXTRA_ENTRIES: list[tuple[str, tuple[str, ...]]] = [
    (
        'See how Birdr teaches bird identification: photo quizzes, My Tricky Birds and Country Challenges. Free on iPhone, Android and the web.',
        (
            'Zo leert Birdr vogelherkenning: fotoquizzen, Mijn lastige vogels en landenuitdagingen. Gratis op iPhone, Android en het web.',
            'Así enseña Birdr a identificar aves: quizzes de fotos, Mis aves difíciles y retos por país. Gratis en iPhone, Android y la web.',
            'Comment Birdr enseigne l’identification : quiz photo, Mes oiseaux difficiles et défis pays. Gratuit sur iPhone, Android et le web.',
            'So lehrt Birdr Vogelbestimmung: Foto-Quiz, Meine schwierigen Vögel und Länder-Challenges. Kostenlos auf iPhone, Android und im Web.',
            'Come Birdr insegna a identificare gli uccelli: quiz fotografici, I miei uccelli difficili e sfide per paese. Gratis su iPhone, Android e sul web.',
            'Como o Birdr ensina identificação de aves: quizzes de fotos, Minhas aves difíceis e desafios por país. Grátis no iPhone, Android e na web.',
            'Birdrの鳥類識別の学び方：写真クイズ、苦手な鳥、国別チャレンジ。iPhone、Android、ウェブで無料。',
        ),
    ),
    (
        'Birdr is a training loop, not a camera that names the bird for you. You look, you guess, you learn the field marks—then the hard species come back.',
        (
            'Birdr is een trainingsslus, geen camera die de vogel voor je benoemt. Je kijkt, je gokt, je leert de kenmerken—en de lastige soorten komen terug.',
            'Birdr es un ciclo de entrenamiento, no una cámara que nombra el ave por ti. Miras, pruebas, aprendes las marcas de campo, y las especies difíciles vuelven.',
            'Birdr est une boucle d’entraînement, pas une caméra qui nomme l’oiseau à ta place. Tu regardes, tu devines, tu apprends les critères—puis les espèces difficiles reviennent.',
            'Birdr ist eine Trainingsschleife, keine Kamera, die den Vogel für dich benennt. Du schaust, rätst, lernst Feldmerkmale—dann kommen die schwierigen Arten wieder.',
            'Birdr è un ciclo di allenamento, non una fotocamera che nomina l’uccello al posto tuo. Guardi, provi, impari i caratteri—poi le specie difficili tornano.',
            'O Birdr é um ciclo de treino, não uma câmera que nomeia a ave por você. Você olha, chuta, aprende as marcas de campo—e as espécies difíceis voltam.',
            'Birdrはトレーニングの繰り返しであり、鳥の名前を代わりに答えるカメラではありません。見て、答えて、特徴を覚え、難しい種がまた出てきます。',
        ),
    ),
    (
        'Start with a photo quiz. You choose a country list and a level. Each question is a real photograph (or video or sound). Pick the species, then see whether you were right and what to look for next time.',
        (
            'Begin met een fotoquiz. Je kiest een landenlijst en een level. Elke vraag is een echte foto (of video of geluid). Kies de soort, en zie of je het goed had en waar je de volgende keer op let.',
            'Empieza con un quiz de fotos. Eliges la lista de un país y un nivel. Cada pregunta es una foto real (o vídeo o sonido). Elige la especie y comprueba si acertaste y qué mirar la próxima vez.',
            'Commence par un quiz photo. Tu choisis une liste de pays et un niveau. Chaque question est une vraie photo (ou vidéo ou son). Choisis l’espèce, puis vois si tu avais bon et quoi regarder la prochaine fois.',
            'Starte mit einem Foto-Quiz. Du wählst eine Länderliste und ein Level. Jede Frage ist ein echtes Foto (oder Video oder Ton). Wähle die Art, dann siehst du, ob du richtig lagst und worauf du als Nächstes achtest.',
            'Inizia con un quiz fotografico. Scegli la lista di un paese e un livello. Ogni domanda è una foto vera (o video o suono). Scegli la specie, poi vedi se avevi ragione e cosa guardare la volta dopo.',
            'Comece com um quiz de fotos. Você escolhe a lista de um país e um nível. Cada pergunta é uma foto de verdade (ou vídeo ou som). Escolha a espécie e veja se acertou e o que observar da próxima vez.',
            'まず写真クイズから。国のリストとレベルを選びます。各問は本物の写真（または動画・音声）です。種を選び、正解かどうかと、次にどこを見るかがわかります。',
        ),
    ),
    (
        'Misses are not wasted. My Tricky Birds remembers the species and confusing pairs you mix up, so later sessions spend time where it actually helps.',
        (
            'Missers zijn niet weggegooid. Mijn lastige vogels onthoudt de soorten en verwarrende paren die je door elkaar haalt, zodat latere sessies tijd besteden waar het echt helpt.',
            'Los fallos no se tiran. Mis aves difíciles recuerda las especies y los pares confusos que mezclas, para que las sesiones siguientes gasten tiempo donde de verdad ayuda.',
            'Les erreurs ne sont pas perdues. Mes oiseaux difficiles retient les espèces et les paires trompeuses que tu mélanges, pour que les sessions suivantes portent là où ça aide vraiment.',
            'Fehler sind nicht verloren. Meine schwierigen Vögel merkt sich die Arten und Paare, die du verwechselst, damit spätere Runden Zeit dort lassen, wo es wirklich hilft.',
            'Gli errori non sono sprecati. I miei uccelli difficili ricorda le specie e le coppie che confondi, così le sessioni successive spendono tempo dove serve davvero.',
            'Os erros não se perdem. Minhas aves difíceis lembra as espécies e os pares confusos que você mistura, para as sessões seguintes gastarem tempo onde realmente ajuda.',
            '間違いは無駄になりません。「苦手な鳥」が取り違えた種と紛らわしいペアを覚え、あとから本当に役立つところに時間を使います。',
        ),
    ),
    (
        'When you want a path rather than a one-off game, take a Country Challenge. Levels move from distinctive beginners to expert lookalikes on that country’s list.',
        (
            'Als je een pad wilt in plaats van een los spel, doe een landenuitdaging. Levels gaan van opvallende beginners tot expert-lookalikes op de lijst van dat land.',
            'Si quieres un recorrido en vez de una partida suelta, haz un reto por país. Los niveles van de principiantes distintivos a sosias de experto en la lista de ese país.',
            'Si tu veux un parcours plutôt qu’une partie isolée, lance un défi pays. Les niveaux vont des débutants bien marqués aux sosies experts de la liste de ce pays.',
            'Wenn du einen Weg willst statt eines einzelnen Spiels, nimm eine Länder-Challenge. Level gehen von markanten Anfängern zu Expert-Doppelgängern auf der Liste dieses Landes.',
            'Se vuoi un percorso invece di una partita isolata, fai una sfida per paese. I livelli vanno dai principianti distintivi ai sosia da esperto sulla lista di quel paese.',
            'Se você quer um caminho em vez de um jogo avulso, faça um desafio por país. Os níveis vão de iniciantes marcantes a sósias de expert na lista daquele país.',
            '一回きりのゲームではなく道筋がほしいときは、国別チャレンジを。その国のリストで、わかりやすい初級から上級の似た種まで進みます。',
        ),
    ),
    (
        'The iPhone and Android apps are the best place to practise daily. The website at /play is there if you want to try a quiz first, or play on a laptop.',
        (
            'De iPhone- en Android-apps zijn de beste plek om dagelijks te oefenen. De site op /play is er als je eerst een quiz wilt proberen, of op een laptop wilt spelen.',
            'Las apps de iPhone y Android son el mejor sitio para practicar a diario. La web en /play está si quieres probar un quiz primero, o jugar en un portátil.',
            'Les apps iPhone et Android sont le meilleur endroit pour s’entraîner chaque jour. Le site /play est là si tu veux d’abord essayer un quiz, ou jouer sur un ordinateur.',
            'Die iPhone- und Android-Apps sind der beste Ort zum täglichen Üben. Die Website unter /play ist da, wenn du zuerst ein Quiz ausprobieren oder am Laptop spielen willst.',
            'Le app iPhone e Android sono il posto migliore per esercitarsi ogni giorno. Il sito /play c’è se vuoi prima provare un quiz, o giocare sul computer.',
            'Os apps de iPhone e Android são o melhor lugar para praticar todo dia. O site em /play existe se você quiser testar um quiz primeiro, ou jogar no notebook.',
            '毎日の練習にはiPhone・Androidアプリが最適です。まずはクイズを試したい、またはノートPCで遊びたいときは /play のサイトがあります。',
        ),
    ),
    (
        'Very easy multiple choice. Only familiar, distinctive species, so you can learn the obvious birds first.',
        (
            'Zeer makkelijke meerkeuze. Alleen bekende, opvallende soorten, zodat je eerst de duidelijke vogels leert.',
            'Opción múltiple muy fácil. Solo especies familiares y distintivas, para aprender primero las aves obvias.',
            'QCM très facile. Seulement des espèces familières et distinctives, pour d’abord apprendre les oiseaux évidents.',
            'Sehr leichtes Multiple Choice. Nur bekannte, markante Arten, damit du zuerst die offensichtlichen Vögel lernst.',
            'Scelta multipla molto facile. Solo specie familiari e distintive, per imparare prima gli uccelli ovvi.',
            'Múltipla escolha bem fácil. Só espécies familiares e marcantes, para você aprender primeiro as aves óbvias.',
            'とても易しい選択問題。なじみ深く特徴のはっきりした種だけなので、まずわかりやすい鳥から学べます。',
        ),
    ),
    (
        'Still easy multiple choice, but the pool includes regular species, not only the most common ones.',
        (
            'Nog steeds makkelijke meerkeuze, maar de pool bevat gewone soorten, niet alleen de allermeest voorkomende.',
            'Sigue siendo opción múltiple fácil, pero el conjunto incluye especies habituales, no solo las más comunes.',
            'Toujours un QCM facile, mais le pool inclut des espèces régulières, pas seulement les plus communes.',
            'Immer noch leichtes Multiple Choice, aber der Pool enthält regelmäßige Arten, nicht nur die häufigsten.',
            'Ancora scelta multipla facile, ma il pool include specie regolari, non solo le più comuni.',
            'Ainda múltipla escolha fácil, mas o conjunto inclui espécies regulares, não só as mais comuns.',
            'まだ易しい選択問題ですが、いちばん普通の種だけでなく、ふつうにいる種も入ります。',
        ),
    ),
    (
        'Multiple choice with similar-looking birds mixed in. Built around the regular species of the country.',
        (
            'Meerkeuze met gelijkende vogels ertussen. Gebouwd rond de gewone soorten van het land.',
            'Opción múltiple con aves parecidas mezcladas. Centrado en las especies habituales del país.',
            'QCM avec des oiseaux ressemblants mélangés. Construit autour des espèces régulières du pays.',
            'Multiple Choice mit ähnlich aussehenden Vögeln dazwischen. Aufgebaut um die regelmäßigen Arten des Landes.',
            'Scelta multipla con uccelli simili mescolati. Costruito intorno alle specie regolari del paese.',
            'Múltipla escolha com aves parecidas misturadas. Feito em torno das espécies regulares do país.',
            '似た鳥が混ざった選択問題。その国でふつうにいる種を中心に組まれています。',
        ),
    ),
    (
        'The same lookalike multiple choice, now including rare species.',
        (
            'Dezelfde lookalike-meerkeuze, nu inclusief zeldzame soorten.',
            'La misma opción múltiple de sosias, ahora incluyendo especies raras.',
            'Le même QCM de sosies, cette fois avec les espèces rares.',
            'Dasselbe Doppelgänger-Multiple-Choice, jetzt inklusive seltener Arten.',
            'La stessa scelta multipla di sosia, ora con le specie rare.',
            'A mesma múltipla escolha de sósias, agora incluindo espécies raras.',
            '同じ似た種の選択問題に、珍しい種も入ります。',
        ),
    ),
    (
        'Type the name yourself, with autocomplete. Includes rare birds.',
        (
            'Typ de naam zelf, met autocomplete. Inclusief zeldzame vogels.',
            'Escribe el nombre tú mismo, con autocompletar. Incluye aves raras.',
            'Tape le nom toi-même, avec l’autocomplétion. Inclut les oiseaux rares.',
            'Tippe den Namen selbst, mit Autovervollständigung. Inklusive seltener Vögel.',
            'Scrivi il nome tu, con autocompletamento. Include gli uccelli rari.',
            'Digite o nome você mesmo, com autocompletar. Inclui aves raras.',
            '名前を自分で入力（オートコンプリートあり）。珍しい鳥も含みます。',
        ),
    ),
    (
        'The language used for bird names in the quiz. Other players in the same game can pick a different language for themselves.',
        (
            'De taal voor vogelnamen in de quiz. Andere spelers in hetzelfde spel kunnen voor zichzelf een andere taal kiezen.',
            'El idioma de los nombres de aves en el quiz. Otros jugadores de la misma partida pueden elegir otro idioma para sí.',
            'La langue des noms d’oiseaux dans le quiz. Les autres joueurs de la même partie peuvent choisir une autre langue pour eux.',
            'Die Sprache der Vogelnamen im Quiz. Andere Spieler im selben Spiel können für sich eine andere Sprache wählen.',
            'La lingua dei nomi degli uccelli nel quiz. Gli altri giocatori della stessa partita possono scegliere un’altra lingua per sé.',
            'O idioma dos nomes das aves no quiz. Outros jogadores no mesmo jogo podem escolher outro idioma para si.',
            'クイズで使う鳥の名前の言語。同じゲームの他のプレイヤーは、自分用に別の言語を選べます。',
        ),
    ),
    (
        'Which country’s bird list the quiz draws from, so you practise species you can actually meet there.',
        (
            'Van welk land de vogellijst komt, zodat je soorten oefent die je daar echt kunt tegenkomen.',
            'De qué país es la lista de aves del quiz, para practicar especies que realmente puedes ver allí.',
            'De quel pays vient la liste d’oiseaux du quiz, pour t’entraîner sur des espèces que tu peux vraiment y rencontrer.',
            'Aus welchem Land die Vogelliste stammt, damit du Arten übst, die du dort wirklich treffen kannst.',
            'Di quale paese è la lista di uccelli del quiz, così ti eserciti su specie che puoi davvero incontrare lì.',
            'De qual país é a lista de aves do quiz, para você praticar espécies que realmente pode encontrar lá.',
            'クイズが使う国の鳥リスト。そこで実際に出会える種を練習できます。',
        ),
    ),
    (
        'How long the quiz is: 10, 20, 50 or 100 questions.',
        (
            'Hoe lang de quiz is: 10, 20, 50 of 100 vragen.',
            'Cuánto dura el quiz: 10, 20, 50 o 100 preguntas.',
            'Quelle longueur a le quiz : 10, 20, 50 ou 100 questions.',
            'Wie lang das Quiz ist: 10, 20, 50 oder 100 Fragen.',
            'Quanto è lungo il quiz: 10, 20, 50 o 100 domande.',
            'Quanto dura o quiz: 10, 20, 50 ou 100 perguntas.',
            'クイズの長さ：10、20、50、100問。',
        ),
    ),
    (
        'Pictures, sounds or video. Sound quizzes can be limited to passerines (songbirds).',
        (
            'Foto’s, geluid of video. Geluidquizzen kunnen beperkt worden tot zangvogels (passerines).',
            'Fotos, sonidos o vídeo. Los quizzes de sonido se pueden limitar a paseriformes (aves canoras).',
            'Photos, sons ou vidéo. Les quiz sonores peuvent être limités aux passereaux.',
            'Bilder, Töne oder Video. Ton-Quiz können auf Sperlingsvögel beschränkt werden.',
            'Foto, suoni o video. I quiz di canti si possono limitare ai passeriformi.',
            'Fotos, sons ou vídeo. Quizzes de som podem se limitar a passeriformes (pássaros canoros).',
            '写真、鳴き声、動画。鳴き声クイズはスズメ目（鳴禽）に限定できます。',
        ),
    ),
    (
        'Optional. Restrict the quiz to an order (for example ducks or passerines) or a family (warblers, gulls) instead of the whole country list.',
        (
            'Optioneel. Beperk de quiz tot een orde (bijvoorbeeld eenden of zangvogels) of een familie (zangers, meeuwen) in plaats van de hele landenlijst.',
            'Opcional. Restringe el quiz a un orden (por ejemplo patos o paseriformes) o una familia (currucas, gaviotas) en vez de toda la lista del país.',
            'Facultatif. Limite le quiz à un ordre (par exemple canards ou passereaux) ou une famille (fauvettes, goélands) au lieu de toute la liste du pays.',
            'Optional. Beschränke das Quiz auf eine Ordnung (z. B. Enten oder Sperlingsvögel) oder eine Familie (Grasmücken, Möwen) statt der ganzen Länderliste.',
            'Facoltativo. Limita il quiz a un ordine (per esempio anatre o passeriformi) o a una famiglia (silvidi, gabbiani) invece di tutta la lista del paese.',
            'Opcional. Restrinja o quiz a uma ordem (por exemplo patos ou passeriformes) ou uma família (toutinegras, gaivotas) em vez da lista inteira do país.',
            '任意。国のリスト全体ではなく、目（カモ類やスズメ目など）や科（ムシクイ、カモメ）に限定できます。',
        ),
    ),
    ('Learn Bird Identification – Practice That Sticks | Birdr', ('Leer vogels herkennen – oefening die blijft hangen | Birdr', 'Aprende a identificar aves – práctica que se queda | Birdr', 'Apprendre à identifier les oiseaux – une pratique qui reste | Birdr', 'Vögel bestimmen lernen – Übung, die sitzt | Birdr', 'Impara a identificare gli uccelli – pratica che resta | Birdr', 'Aprenda a identificar aves – prática que gruda | Birdr', '鳥の識別を学ぶ – 定着する練習 | Birdr')),
    (
        'Learn bird identification with personalised practice, confusing-pair drills and country challenges. Free on iPhone, Android and the web.',
        (
            'Leer vogels herkennen met persoonlijke oefening, verwarrende paren en landenuitdagingen. Gratis op iPhone, Android en het web.',
            'Aprende a identificar aves con práctica personalizada, ejercicios de pares confusos y retos por país. Gratis en iPhone, Android y la web.',
            'Apprends à identifier les oiseaux avec un entraînement personnalisé, des paires trompeuses et des défis pays. Gratuit sur iPhone, Android et le web.',
            'Lerne Vögel bestimmen mit persönlichem Training, Verwechslungspaaren und Länder-Challenges. Kostenlos auf iPhone, Android und im Web.',
            'Impara a identificare gli uccelli con pratica personalizzata, coppie ingannevoli e sfide per paese. Gratis su iPhone, Android e sul web.',
            'Aprenda a identificar aves com prática personalizada, pares confusos e desafios por país. Grátis no iPhone, Android e na web.',
            'あなた向けの練習、紛らわしいペア、国別チャレンジで鳥の識別を学ぶ。iPhone、Android、ウェブで無料。',
        ),
    ),
    ('Learn bird identification yourself', ('Leer zelf vogels herkennen', 'Aprende a identificar aves tú mismo', 'Apprends à identifier les oiseaux toi-même', 'Lerne, Vögel selbst zu bestimmen', 'Impara a identificare gli uccelli da solo', 'Aprenda a identificar aves você mesmo', '自分で鳥を見分けられるようになろう')),
    (
        'Automatic photo IDs are useful in the field. Birdr is for the other skill: recognising birds when you next see them, without handing the photo to an app.',
        (
            'Automatische fotoherkenning is handig in het veld. Birdr is voor de andere vaardigheid: vogels herkennen als je ze de volgende keer ziet, zonder de foto aan een app te geven.',
            'Las identificaciones automáticas por foto son útiles en el campo. Birdr es para la otra habilidad: reconocer aves cuando las veas, sin entregar la foto a una app.',
            'Les identifications photo automatiques sont utiles sur le terrain. Birdr vise l’autre compétence : reconnaître les oiseaux la prochaine fois, sans donner la photo à une app.',
            'Automatische Foto-IDs sind im Gelände nützlich. Birdr ist für die andere Fähigkeit: Vögel wiederzuerkennen, ohne das Foto an eine App zu geben.',
            'Le identificazioni automatiche da foto sono utili sul campo. Birdr è per l’altra abilità: riconoscere gli uccelli la volta dopo, senza dare la foto a un’app.',
            'IDs automáticas por foto são úteis no campo. O Birdr é para a outra habilidade: reconhecer as aves da próxima vez, sem entregar a foto a um app.',
            '写真の自動識別はフィールドで便利です。Birdrはもう一つの技能向け：次に見たときに、アプリに写真を渡さず自分で見分けられること。',
        ),
    ),
    ('Start practising', ('Begin met oefenen', 'Empieza a practicar', 'Commencer à s’entraîner', 'Mit dem Üben beginnen', 'Inizia a esercitarti', 'Comece a praticar', '練習を始める')),
    (
        'You learn by doing: photo quizzes, Country Challenges with rising levels, and extra practice on the species you actually mix up.',
        (
            'Je leert door te doen: fotoquizzen, landenuitdagingen met oplopende levels, en extra oefening op de soorten die je écht door elkaar haalt.',
            'Aprendes haciendo: quizzes de fotos, retos por país con niveles que suben, y práctica extra en las especies que de verdad mezclas.',
            'Tu apprends en faisant : quiz photo, défis pays à niveaux croissants, et entraînement supplémentaire sur les espèces que tu mélanges vraiment.',
            'Du lernst durch Tun: Foto-Quiz, Länder-Challenges mit steigenden Leveln und extra Übung an den Arten, die du wirklich verwechselst.',
            'Impari facendo: quiz fotografici, sfide per paese con livelli che salgono, e pratica extra sulle specie che davvero confondi.',
            'Você aprende fazendo: quizzes de fotos, desafios por país com níveis que sobem, e prática extra nas espécies que você realmente mistura.',
            'やって覚えます。写真クイズ、レベルが上がる国別チャレンジ、そして本当に取り違える種の追加練習。',
        ),
    ),
    (
        'Comparisons for confusing pairs (for example sparrowhawk and goshawk) explain the field marks, then you can practise that pair until it is automatic.',
        (
            'Vergelijkingen voor verwarrende paren (bijvoorbeeld sperwer en havik) leggen de kenmerken uit, daarna kun je dat paar oefenen tot het automatisch gaat.',
            'Las comparaciones de pares confusos (por ejemplo gavilán y azor) explican las marcas de campo, y luego puedes practicar ese par hasta que sea automático.',
            'Les comparaisons de paires trompeuses (par exemple épervier et autour) expliquent les critères, puis tu peux pratiquer cette paire jusqu’à ce que ce soit automatique.',
            'Vergleiche für verwirrende Paare (z. B. Sperber und Habicht) erklären die Feldmerkmale, dann kannst du das Paar üben, bis es automatisch sitzt.',
            'I confronti per coppie ingannevoli (per esempio sparviero e astore) spiegano i caratteri, poi puoi esercitarti su quella coppia finché diventa automatico.',
            'Comparações de pares confusos (por exemplo gavião e açor) explicam as marcas de campo, e então você pratica aquele par até ficar automático.',
            '紛らわしいペア（ハイタカとオオタカなど）の比較で特徴を説明し、そのペアを自動になるまで練習できます。',
        ),
    ),
    ('Birding training app', ('Trainingsapp voor vogelaars', 'App de entrenamiento de aves', 'App d’entraînement ornitho', 'Birding-Trainings-App', 'App di allenamento birdwatching', 'App de treino de observação', '探鳥トレーニングアプリ')),
    ('Practise difficult birds', ('Oefen lastige vogels', 'Practica aves difíciles', 'S’entraîner sur les oiseaux difficiles', 'Schwierige Vögel üben', 'Esercitati sugli uccelli difficili', 'Pratique aves difíceis', '難しい鳥を練習')),
    ('Bird Quizzes by Country – Country Challenges | Birdr', ('Vogelquizzen per land – landenuitdagingen | Birdr', 'Quizzes de aves por país – retos por país | Birdr', 'Quiz oiseaux par pays – défis pays | Birdr', 'Vogelquiz nach Land – Länder-Challenges | Birdr', 'Quiz di uccelli per paese – sfide per paese | Birdr', 'Quizzes de aves por país – desafios por país | Birdr', '国別の鳥クイズ – 国別チャレンジ | Birdr')),
    (
        'Play bird quizzes by country and take Country Challenges from easy to expert. Study the birds you will meet at home or on your next trip.',
        (
            'Speel vogelquizzen per land en doe landenuitdagingen van makkelijk tot expert. Bestudeer de vogels die je thuis of op je volgende reis tegenkomt.',
            'Juega quizzes de aves por país y retos de fácil a experto. Estudia las aves que verás en casa o en tu próximo viaje.',
            'Joue des quiz oiseaux par pays et des défis du facile à l’expert. Étudie les oiseaux que tu rencontreras chez toi ou au prochain voyage.',
            'Spiele Vogelquiz nach Land und Länder-Challenges von leicht bis Expert. Lerne die Vögel, die du zu Hause oder auf der nächsten Reise triffst.',
            'Gioca quiz di uccelli per paese e sfide dal facile all’esperto. Studia gli uccelli che incontrerai a casa o nel prossimo viaggio.',
            'Jogue quizzes de aves por país e desafios do fácil ao expert. Estude as aves que você vai encontrar em casa ou na próxima viagem.',
            '国別の鳥クイズと、易しい〜上級の国別チャレンジ。自宅や次の旅で出会う鳥を学べます。',
        ),
    ),
    ('Bird quizzes by country', ('Vogelquizzen per land', 'Quizzes de aves por país', 'Quiz oiseaux par pays', 'Vogelquiz nach Land', 'Quiz di uccelli per paese', 'Quizzes de aves por país', '国別の鳥クイズ')),
    (
        'Every country list is a different classroom. Quiz on the birds of the Netherlands, Colombia, Japan or wherever you bird—then take a Country Challenge.',
        (
            'Elke landenlijst is een ander klaslokaal. Quiz op de vogels van Nederland, Colombia, Japan of waar je maar vogelt—en doe dan een landenuitdaging.',
            'Cada lista de país es un aula distinta. Haz un quiz con las aves de Países Bajos, Colombia, Japón o donde observes, y luego un reto por país.',
            'Chaque liste de pays est une autre salle de classe. Quiz sur les oiseaux des Pays-Bas, de Colombie, du Japon ou d’où tu observes—puis un défi pays.',
            'Jede Länderliste ist ein anderes Klassenzimmer. Quiz zu den Vögeln der Niederlande, Kolumbiens, Japans oder wo du beobachtest—dann eine Länder-Challenge.',
            'Ogni lista di paese è un’aula diversa. Quiz sugli uccelli dei Paesi Bassi, Colombia, Giappone o dove fai birdwatching—poi una sfida per paese.',
            'Cada lista de país é uma sala diferente. Faça um quiz com as aves dos Países Baixos, Colômbia, Japão ou onde você observa—depois um desafio por país.',
            '国ごとのリストは別の教室です。オランダ、コロンビア、日本など、探鳥する土地の鳥でクイズし、国別チャレンジへ。',
        ),
    ),
    ('Start a Country Challenge', ('Start een landenuitdaging', 'Empezar un reto por país', 'Lancer un défi pays', 'Länder-Challenge starten', 'Inizia una sfida per paese', 'Começar um desafio por país', '国別チャレンジを始める')),
    (
        'A Country Challenge walks you through levels, from common and distinctive species to harder lookalikes. It is a structured way to learn a country list, not a random mix of world birds.',
        (
            'Een landenuitdaging leidt je door levels, van algemene, opvallende soorten tot lastigere lookalikes. Het is een gestructureerde manier om een landenlijst te leren, geen willekeurige mix van wereldvogels.',
            'Un reto por país te lleva por niveles, de especies comunes y distintivas a sosias más difíciles. Es una forma estructurada de aprender la lista de un país, no una mezcla aleatoria del mundo.',
            'Un défi pays te fait passer des niveaux, des espèces communes et distinctives aux sosies plus durs. C’est une façon structurée d’apprendre une liste de pays, pas un mélange aléatoire d’oiseaux du monde.',
            'Eine Länder-Challenge führt dich durch Level, von häufigen, markanten Arten zu schwierigeren Doppelgängern. So lernst du eine Länderliste strukturiert, nicht als Zufallsmix der Welt.',
            'Una sfida per paese ti porta attraverso i livelli, dalle specie comuni e distintive ai sosia più difficili. È un modo strutturato di imparare la lista di un paese, non un misto casuale del mondo.',
            'Um desafio por país te leva pelos níveis, de espécies comuns e marcantes a sósias mais difíceis. É um jeito estruturado de aprender a lista de um país, não uma mistura aleatória do mundo.',
            '国別チャレンジはレベルを順に進みます。普通で特徴のはっきりした種から、より難しい似た種へ。世界の鳥のランダム混ぜではなく、その国のリストを構造的に学ぶ方法です。',
        ),
    ),
    (
        'Use a one-off quiz when you want a short session, or a challenge when you want to work through a country properly.',
        (
            'Gebruik een losse quiz voor een korte sessie, of een challenge als je een land écht wilt doorwerken.',
            'Usa un quiz suelto si quieres una sesión corta, o un reto si quieres trabajar un país de verdad.',
            'Utilise un quiz isolé pour une session courte, ou un défi si tu veux vraiment parcourir un pays.',
            'Nimm ein einzelnes Quiz für eine kurze Runde, oder eine Challenge, wenn du ein Land richtig durcharbeiten willst.',
            'Usa un quiz isolato per una sessione breve, o una sfida se vuoi lavorare un paese per davvero.',
            'Use um quiz avulso para uma sessão curta, ou um desafio se quiser trabalhar um país de verdade.',
            '短いセッションなら一回のクイズ、その国をきちんとやりたいならチャレンジを。',
        ),
    ),
    ('The Birdr app', ('De Birdr-app', 'La app Birdr', 'L’app Birdr', 'Die Birdr-App', 'L’app Birdr', 'O app Birdr', 'Birdrアプリ')),
    ('Birding Training App – Free on iPhone, Android & Web | Birdr', ('Trainingsapp voor vogelaars – gratis op iPhone, Android en web | Birdr', 'App de entrenamiento – gratis en iPhone, Android y web | Birdr', 'App d’entraînement ornitho – gratuite iPhone, Android et web | Birdr', 'Birding-Trainings-App – kostenlos auf iPhone, Android & Web | Birdr', 'App di allenamento – gratis su iPhone, Android e web | Birdr', 'App de treino – grátis no iPhone, Android e web | Birdr', '探鳥トレーニングアプリ – iPhone、Android、ウェブで無料 | Birdr')),
    (
        'Birdr is a free birding training app: photo quizzes, country challenges and personalised practice so you learn to identify birds yourself.',
        (
            'Birdr is een gratis trainingsapp voor vogelaars: fotoquizzen, landenuitdagingen en persoonlijke oefening, zodat je zelf vogels leert herkennen.',
            'Birdr es una app gratis de entrenamiento: quizzes de fotos, retos por país y práctica personalizada para que aprendas a identificar aves tú mismo.',
            'Birdr est une app d’entraînement gratuite : quiz photo, défis pays et pratique personnalisée pour apprendre à identifier les oiseaux toi-même.',
            'Birdr ist eine kostenlose Trainings-App: Foto-Quiz, Länder-Challenges und persönliches Training, damit du Vögel selbst bestimmen lernst.',
            'Birdr è un’app di allenamento gratis: quiz fotografici, sfide per paese e pratica personalizzata per imparare a identificare gli uccelli da solo.',
            'O Birdr é um app de treino grátis: quizzes de fotos, desafios por país e prática personalizada para você aprender a identificar aves.',
            'Birdrは無料の探鳥トレーニングアプリ。写真クイズ、国別チャレンジ、あなた向けの練習で、自分で鳥を見分けます。',
        ),
    ),
    ('A birding app for learning, not auto-ID', ('Een vogelapp om te leren, geen auto-ID', 'Una app de aves para aprender, no auto-ID', 'Une app ornitho pour apprendre, pas l’auto-ID', 'Eine Birding-App zum Lernen, keine Auto-ID', 'Un’app di birdwatching per imparare, non auto-ID', 'Um app de aves para aprender, não auto-ID', '学ぶための探鳥アプリ。自動識別ではない')),
    (
        'Birdr is a training app for birders. Free photo quizzes, personalised practice and country challenges on iPhone, Android and the web.',
        (
            'Birdr is een trainingsapp voor vogelaars. Gratis fotoquizzen, persoonlijke oefening en landenuitdagingen op iPhone, Android en het web.',
            'Birdr es una app de entrenamiento para observadores. Quizzes de fotos gratis, práctica personalizada y retos por país en iPhone, Android y la web.',
            'Birdr est une app d’entraînement pour les ornithos. Quiz photo gratuits, pratique personnalisée et défis pays sur iPhone, Android et le web.',
            'Birdr ist eine Trainings-App für Birding. Kostenlose Foto-Quiz, persönliches Training und Länder-Challenges auf iPhone, Android und im Web.',
            'Birdr è un’app di allenamento per birdwatcher. Quiz fotografici gratis, pratica personalizzata e sfide per paese su iPhone, Android e sul web.',
            'O Birdr é um app de treino para observadores. Quizzes de fotos grátis, prática personalizada e desafios por país no iPhone, Android e na web.',
            'Birdrはバーダー向けのトレーニングアプリ。無料の写真クイズ、あなた向けの練習、国別チャレンジをiPhone、Android、ウェブで。',
        ),
    ),
    ('Open Birdr', ('Open Birdr', 'Abrir Birdr', 'Ouvrir Birdr', 'Birdr öffnen', 'Apri Birdr', 'Abrir o Birdr', 'Birdrを開く')),
    (
        'Use it on a commute, before a trip, or after a confusing day in the field. The same account works in the apps and in the browser.',
        (
            'Gebruik het in de trein, voor een reis, of na een verwarrende dag in het veld. Hetzelfde account werkt in de apps en in de browser.',
            'Úsalo en el trayecto, antes de un viaje, o después de un día confuso en el campo. La misma cuenta funciona en las apps y en el navegador.',
            'Utilise-le dans les transports, avant un voyage, ou après une journée confuse sur le terrain. Le même compte marche dans les apps et le navigateur.',
            'Nutze es im Pendelverkehr, vor einer Reise oder nach einem verwirrenden Tag im Gelände. Dasselbe Konto gilt in den Apps und im Browser.',
            'Usalo in treno, prima di un viaggio, o dopo una giornata confusa sul campo. Lo stesso account vale nelle app e nel browser.',
            'Use no deslocamento, antes de uma viagem, ou depois de um dia confuso no campo. A mesma conta funciona nos apps e no navegador.',
            '通勤中、旅の前、フィールドで迷った日のあとにも。同じアカウントがアプリとブラウザで使えます。',
        ),
    ),
    (
        'Friends can run a Daily Challenge. You can drill My Tricky Birds until the hard species stop being hard.',
        (
            'Vrienden kunnen een Daily Challenge spelen. Jij kunt Mijn lastige vogels oefenen tot de moeilijke soorten niet meer moeilijk zijn.',
            'Los amigos pueden hacer un Daily Challenge. Tú puedes practicar Mis aves difíciles hasta que las especies difíciles dejen de serlo.',
            'Les amis peuvent faire un Daily Challenge. Tu peux bosser Mes oiseaux difficiles jusqu’à ce que les espèces dures ne le soient plus.',
            'Freunde können eine Daily Challenge spielen. Du kannst Meine schwierigen Vögel üben, bis die harten Arten nicht mehr hart sind.',
            'Gli amici possono fare una Daily Challenge. Tu puoi esercitarti su I miei uccelli difficili finché le specie difficili smettono di esserlo.',
            'Amigos podem fazer um Daily Challenge. Você pode treinar Minhas aves difíceis até as espécies difíceis deixarem de ser.',
            '友人と Daily Challenge もできます。「苦手な鳥」を、難しい種が難しくなくなるまで繰り返せます。',
        ),
    ),
    ('Practise Difficult Bird Species – My Tricky Birds | Birdr', ('Oefen lastige vogelsoorten – Mijn lastige vogels | Birdr', 'Practica especies difíciles – Mis aves difíciles | Birdr', 'S’entraîner sur les espèces difficiles – Mes oiseaux difficiles | Birdr', 'Schwierige Vogelarten üben – Meine schwierigen Vögel | Birdr', 'Esercitati sulle specie difficili – I miei uccelli difficili | Birdr', 'Pratique espécies difíceis – Minhas aves difíceis | Birdr', '難しい種を練習 – 苦手な鳥 | Birdr')),
    (
        'Practise the bird species you mix up. My Tricky Birds and confusing-pair drills turn mistakes into focused training.',
        (
            'Oefen de soorten die je door elkaar haalt. Mijn lastige vogels en verwarrende paren maken van missers gerichte training.',
            'Practica las especies que mezclas. Mis aves difíciles y los ejercicios de pares confusos convierten los fallos en entrenamiento centrado.',
            'Entraîne-toi sur les espèces que tu mélanges. Mes oiseaux difficiles et les paires trompeuses transforment les erreurs en entraînement ciblé.',
            'Übe die Arten, die du verwechselst. Meine schwierigen Vögel und Verwechslungspaare machen aus Fehlern gezieltes Training.',
            'Esercitati sulle specie che confondi. I miei uccelli difficili e le coppie ingannevoli trasformano gli errori in allenamento mirato.',
            'Pratique as espécies que você mistura. Minhas aves difíceis e os pares confusos transformam erros em treino focado.',
            '取り違える種を練習。「苦手な鳥」と紛らわしいペアのドリルが、間違いを集中トレーニングに変えます。',
        ),
    ),
    (
        'Everyone has a handful of species that will not stick. Birdr keeps those trouble spots and the confusing pairs you mix up, so practice stays focused.',
        (
            'Iedereen heeft een handvol soorten die niet blijven hangen. Birdr bewaart die lastige plekken en de verwarrende paren, zodat oefenen gericht blijft.',
            'Todo el mundo tiene un puñado de especies que no se quedan. Birdr guarda esos puntos débiles y los pares confusos, para que la práctica siga centrada.',
            'Tout le monde a une poignée d’espèces qui ne rentrent pas. Birdr garde ces points faibles et les paires trompeuses, pour que l’entraînement reste ciblé.',
            'Jeder hat eine Handvoll Arten, die nicht sitzen. Birdr behält diese Schwachstellen und die verwirrenden Paare, damit das Üben fokussiert bleibt.',
            'Tutti hanno un pugno di specie che non restano. Birdr tiene quei punti deboli e le coppie ingannevoli, così la pratica resta mirata.',
            'Todo mundo tem um punhado de espécies que não grudam. O Birdr guarda esses pontos fracos e os pares confusos, para a prática continuar focada.',
            '誰にでも、どうしても定着しない種がいくつかあります。Birdrがその苦手と紛らわしいペアを残すので、練習が散らかりません。',
        ),
    ),
    ('Open My Tricky Birds', ('Open Mijn lastige vogels', 'Abrir Mis aves difíciles', 'Ouvrir Mes oiseaux difficiles', 'Meine schwierigen Vögel öffnen', 'Apri I miei uccelli difficili', 'Abrir Minhas aves difíceis', '苦手な鳥を開く')),
    (
        'After quizzes, wrong answers feed a personal list. You can practise a single species or a pair (for example two Accipiters) until the field marks feel obvious.',
        (
            'Na quizzen vullen foute antwoorden een persoonlijke lijst. Je kunt één soort of een paar (bijvoorbeeld twee Accipiters) oefenen tot de kenmerken vanzelfsprekend voelen.',
            'Después de los quizzes, los fallos alimentan una lista personal. Puedes practicar una especie o un par (por ejemplo dos Accipiter) hasta que las marcas de campo se vean obvias.',
            'Après les quiz, les mauvaises réponses alimentent une liste perso. Tu peux pratiquer une espèce ou une paire (par exemple deux Accipiter) jusqu’à ce que les critères paraissent évidents.',
            'Nach Quizzen füllen falsche Antworten eine persönliche Liste. Du kannst eine Art oder ein Paar (z. B. zwei Accipiter) üben, bis die Feldmerkmale offensichtlich wirken.',
            'Dopo i quiz, le risposte sbagliate alimentano una lista personale. Puoi esercitarti su una specie o una coppia (per esempio due Accipiter) finché i caratteri sembrano ovvi.',
            'Depois dos quizzes, os erros alimentam uma lista pessoal. Você pode praticar uma espécie ou um par (por exemplo dois Accipiter) até as marcas de campo parecerem óbvias.',
            'クイズの間違いは個人リストに入ります。一種、またはペア（オオタカ属など）を、特徴が当たり前に見えるまで練習できます。',
        ),
    ),
    (
        'That is the point of Birdr: not a high score on birds you already know, but time spent on the difficult ones.',
        (
            'Dat is het punt van Birdr: geen high score op vogels die je al kent, maar tijd aan de moeilijke.',
            'Ese es el punto de Birdr: no un récord en aves que ya conoces, sino tiempo en las difíciles.',
            'C’est le but de Birdr : pas un high score sur les oiseaux que tu connais déjà, mais du temps sur les difficiles.',
            'Darum geht es bei Birdr: kein Highscore bei Vögeln, die du schon kennst, sondern Zeit für die schwierigen.',
            'Questo è il punto di Birdr: non un punteggio alto sugli uccelli che già conosci, ma tempo su quelli difficili.',
            'Esse é o ponto do Birdr: não um recorde nas aves que você já conhece, e sim tempo nas difíceis.',
            'それがBirdrの趣旨です。すでに知っている鳥の高得点ではなく、難しい種に時間を使うこと。',
        ),
    ),
    (
        'My Tricky Birds in the app: a list of lookalike pairs for the Netherlands, with Practice buttons and FIXED badges',
        (
            'Mijn lastige vogels in de app: een lijst lookalike-paren voor Nederland, met Oefen-knoppen en FIXED-badges',
            'Mis aves difíciles en la app: una lista de pares parecidos para Países Bajos, con botones Practicar y distintivos FIXED',
            'Mes oiseaux difficiles dans l’app : une liste de paires sosies pour les Pays-Bas, avec boutons Pratiquer et badges FIXED',
            'Meine schwierigen Vögel in der App: eine Liste von Doppelgänger-Paaren für die Niederlande, mit Üben-Buttons und FIXED-Badges',
            'I miei uccelli difficili nell’app: una lista di coppie simili per i Paesi Bassi, con pulsanti Pratica e badge FIXED',
            'Minhas aves difíceis no app: uma lista de pares parecidos para os Países Baixos, com botões Praticar e selos FIXED',
            'アプリの「苦手な鳥」：オランダの似たペア一覧。練習ボタンと FIXED バッジ付き',
        ),
    ),
    ('Your tricky pairs', ('Jouw lastige paren', 'Tus pares difíciles', 'Tes paires difficiles', 'Deine schwierigen Paare', 'Le tue coppie difficili', 'Seus pares difíceis', '苦手なペア')),
    (
        'Pair practice quiz: Eurasian Treecreeper versus Short-toed Treecreeper, with the correct species marked',
        (
            'Paaroefenquiz: boomkruiper versus kortteenboomkruiper, met de juiste soort gemarkeerd',
            'Quiz de práctica de par: agateador euroasiático frente a agateador común, con la especie correcta marcada',
            'Quiz de pratique en paire : grimpereau des jardins contre grimpereau des bois, avec la bonne espèce marquée',
            'Paar-Übung: Waldbaumläufer gegen Gartenbaumläufer, mit der richtigen Art markiert',
            'Quiz di pratica a coppia: rampichino comune contro rampichino alpestre, con la specie corretta evidenziata',
            'Quiz de prática em par: trepadeira-comum versus trepadeira-do-bosque, com a espécie certa marcada',
            'ペア練習クイズ：キバシリ対コキバシリ、正解の種がマークされた画面',
        ),
    ),
    ('Practise a pair', ('Oefen een paar', 'Practica un par', 'Pratiquer une paire', 'Ein Paar üben', 'Esercitati su una coppia', 'Pratique um par', 'ペアを練習')),
    (
        'Pair practice results: 18 of 20 correct, and the treecreepers no longer seem confusing',
        (
            'Resultaat paaroefening: 18 van 20 goed, en de boomkruipers lijken niet meer verwarrend',
            'Resultados de práctica de par: 18 de 20 correctas, y los agateadores ya no parecen confusos',
            'Résultats de pratique en paire : 18 sur 20 justes, et les grimpereaux ne semblent plus trompeurs',
            'Ergebnis der Paar-Übung: 18 von 20 richtig, und die Baumläufer wirken nicht mehr verwirrend',
            'Risultati della pratica a coppia: 18 su 20 corretti, e i rampichini non sembrano più confusi',
            'Resultados da prática em par: 18 de 20 certos, e as trepadeiras já não parecem confusas',
            'ペア練習の結果：20問中18問正解。キバシリ類がもう紛らわしくない',
        ),
    ),
    ('See when a pair is fixed', ('Zie wanneer een paar is opgelost', 'Mira cuándo un par está resuelto', 'Voir quand une paire est réglée', 'Sehen, wann ein Paar sitzt', 'Vedi quando una coppia è sistemata', 'Veja quando um par está resolvido', 'ペアが定着したとき')),
    ('Bird Club Quiz & Leaderboard – Flocks | Birdr', ('Vogelclubquiz en klassement – Flocks | Birdr', 'Quiz de club y clasificación – Flocks | Birdr', 'Quiz de club et classement – Flocks | Birdr', 'Vogelclub-Quiz und Rangliste – Flocks | Birdr', 'Quiz del club e classifica – Flocks | Birdr', 'Quiz de clube e ranking – Flocks | Birdr', '探鳥クラブのクイズとランキング – Flocks | Birdr')),
    (
        'Create a Flock for your bird club or group. Shared quizzes and a leaderboard keep everyone practising together. Free on Birdr.',
        (
            'Maak een Flock voor je vogelclub of groep. Gedeelde quizzen en een klassement houden iedereen samen aan het oefenen. Gratis op Birdr.',
            'Crea un Flock para tu club o grupo. Quizzes compartidos y una clasificación mantienen a todos practicando juntos. Gratis en Birdr.',
            'Crée un Flock pour ton club ou groupe. Des quiz partagés et un classement font pratiquer tout le monde ensemble. Gratuit sur Birdr.',
            'Erstelle einen Flock für deinen Vogelclub oder die Gruppe. Gemeinsame Quiz und eine Rangliste halten alle beim Üben. Kostenlos auf Birdr.',
            'Crea un Flock per il tuo club o gruppo. Quiz condivisi e una classifica tengono tutti a esercitarsi insieme. Gratis su Birdr.',
            'Crie um Flock para o seu clube ou grupo. Quizzes compartilhados e um ranking mantêm todo mundo praticando junto. Grátis no Birdr.',
            'クラブやグループ用の Flock を作る。共有クイズとランキングでみんな一緒に練習。Birdrで無料。',
        ),
    ),
    ('Flocks: quizzes for bird clubs', ('Flocks: quizzen voor vogelclubs', 'Flocks: quizzes para clubs de aves', 'Flocks : quiz pour les clubs', 'Flocks: Quiz für Vogelclubs', 'Flocks: quiz per i club', 'Flocks: quizzes para clubes', 'Flocks：探鳥クラブ向けクイズ')),
    (
        'A Flock is your club, WhatsApp group or trip companions on Birdr. Play the same quiz, compare scores, and keep a leaderboard.',
        (
            'Een Flock is je club, WhatsApp-groep of reisgenoten op Birdr. Speel dezelfde quiz, vergelijk scores en houd een klassement bij.',
            'Un Flock es tu club, grupo de WhatsApp o compañeros de viaje en Birdr. Jugad el mismo quiz, comparad puntuaciones y tened una clasificación.',
            'Un Flock, c’est ton club, groupe WhatsApp ou compagnons de voyage sur Birdr. Jouez au même quiz, comparez les scores, gardez un classement.',
            'Ein Flock ist dein Club, die WhatsApp-Gruppe oder Reisegefährten auf Birdr. Spielt dasselbe Quiz, vergleicht Punkte und haltet eine Rangliste.',
            'Un Flock è il tuo club, gruppo WhatsApp o compagni di viaggio su Birdr. Giocate lo stesso quiz, confrontate i punteggi e tenete una classifica.',
            'Um Flock é o seu clube, grupo de WhatsApp ou companheiros de viagem no Birdr. Joguem o mesmo quiz, comparem pontuações e tenham um ranking.',
            'Flock は Birdr 上のクラブ、WhatsApp、旅の仲間。同じクイズをプレイし、スコアを比べ、ランキングを残せます。',
        ),
    ),
    ('Create or join a Flock', ('Maak of join een Flock', 'Crear o unirse a un Flock', 'Créer ou rejoindre un Flock', 'Flock erstellen oder beitreten', 'Crea o unisciti a un Flock', 'Criar ou entrar em um Flock', 'Flockを作る／参加する')),
    (
        'Each Flock quiz has 25 questions. It starts easy and finishes hard, so mixed-ability groups can play the same game.',
        (
            'Elke Flock-quiz heeft 25 vragen. Hij begint makkelijk en eindigt lastig, zodat groepen van gemengd niveau hetzelfde spel kunnen spelen.',
            'Cada quiz de Flock tiene 25 preguntas. Empieza fácil y termina difícil, para que grupos de nivel mixto jueguen la misma partida.',
            'Chaque quiz Flock a 25 questions. Ça commence facile et ça finit dur, pour que des groupes de niveaux mixtes jouent la même partie.',
            'Jedes Flock-Quiz hat 25 Fragen. Es startet leicht und endet schwer, damit gemischte Gruppen dasselbe Spiel spielen können.',
            'Ogni quiz Flock ha 25 domande. Inizia facile e finisce difficile, così gruppi di livello misto possono giocare la stessa partita.',
            'Cada quiz de Flock tem 25 perguntas. Começa fácil e termina difícil, para grupos de níveis mistos jogarem o mesmo jogo.',
            'Flock のクイズは各25問。易しく始まり難しく終わるので、実力の違うグループでも同じゲームができます。',
        ),
    ),
    (
        'Admins set a country and a challenge. Members play on their phones or on the web. Results can be shared without opening the whole club to the public.',
        (
            'Admins zetten een land en een challenge. Leden spelen op hun telefoon of op het web. Resultaten kun je delen zonder de hele club openbaar te maken.',
            'Los admins eligen un país y un reto. Los miembros juegan en el móvil o en la web. Los resultados se pueden compartir sin abrir todo el club al público.',
            'Les admins choisissent un pays et un défi. Les membres jouent sur le téléphone ou le web. Les résultats se partagent sans ouvrir tout le club au public.',
            'Admins setzen ein Land und eine Challenge. Mitglieder spielen am Handy oder im Web. Ergebnisse lassen sich teilen, ohne den ganzen Club öffentlich zu machen.',
            'Gli admin impostano un paese e una sfida. I membri giocano sul telefono o sul web. I risultati si possono condividere senza aprire tutto il club al pubblico.',
            'Admins definem um país e um desafio. Membros jogam no celular ou na web. Resultados podem ser compartilhados sem abrir o clube inteiro ao público.',
            '管理者が国とチャレンジを設定。メンバーはスマホかウェブでプレイ。クラブ全体を公開しなくても結果を共有できます。',
        ),
    ),
    (
        'It is built for real groups of birders, not a global anonymous ladder. Start from the app or the web after you sign in.',
        (
            'Het is gebouwd voor echte groepen vogelaars, geen anonieme wereldwijde ladder. Start in de app of op het web na het inloggen.',
            'Está hecho para grupos reales de observadores, no una clasificación anónima mundial. Empieza en la app o la web después de iniciar sesión.',
            'C’est fait pour de vrais groupes d’ornithos, pas un classement anonyme mondial. Commence dans l’app ou le web après connexion.',
            'Es ist für echte Birding-Gruppen gebaut, keine anonyme Weltrangliste. Starte in der App oder im Web nach dem Anmelden.',
            'È fatto per gruppi veri di birdwatcher, non una classifica anonima globale. Inizia dall’app o dal web dopo l’accesso.',
            'Foi feito para grupos reais de observadores, não um ranking anônimo mundial. Comece no app ou na web depois de entrar.',
            '世界の匿名ランキングではなく、実際のバーダーのグループ向け。ログイン後、アプリかウェブから始めます。',
        ),
    ),
    ('Country quizzes', ('Landenquizzen', 'Quizzes por país', 'Quiz par pays', 'Länder-Quiz', 'Quiz per paese', 'Quizzes por país', '国別クイズ')),
    ('Help Birdr – Community | Birdr', ('Help Birdr – Community | Birdr', 'Ayuda a Birdr – Comunidad | Birdr', 'Aider Birdr – Communauté | Birdr', 'Birdr helfen – Community | Birdr', 'Aiuta Birdr – Community | Birdr', 'Ajude o Birdr – Comunidade | Birdr', 'Birdrを助ける – コミュニティ | Birdr')),
    (
        'Help Birdr by sending feedback, reviewing quiz photos, writing species comparisons, or sharing it in a bird club newsletter.',
        (
            'Help Birdr met feedback, het beoordelen van quizfoto’s, het schrijven van soortvergelijkingen, of een stukje in de clubnieuwsbrief.',
            'Ayuda a Birdr enviando comentarios, revisando fotos del quiz, escribiendo comparaciones, o compartiéndolo en el boletín del club.',
            'Aide Birdr en envoyant un avis, en relisant des photos de quiz, en écrivant des comparaisons, ou en le partageant dans le bulletin du club.',
            'Hilf Birdr mit Feedback, dem Prüfen von Quiz-Fotos, Vergleichstexten oder einem Hinweis im Club-Newsletter.',
            'Aiuta Birdr inviando feedback, rivedendo le foto dei quiz, scrivendo confronti, o condividendolo nel notiziario del club.',
            'Ajude o Birdr enviando feedback, revisando fotos do quiz, escrevendo comparações, ou divulgando no boletim do clube.',
            'フィードバック、クイズ写真の確認、種の比較文、クラブ会報での紹介で Birdr を助けてください。',
        ),
    ),
    (
        'Birdr is a small project. Feedback, photo review, comparison descriptions, and spreading the word to other birders all help.',
        (
            'Birdr is een klein project. Feedback, fotobeoordeling, vergelijkingsteksten en het doorvertellen aan andere vogelaars helpen allemaal.',
            'Birdr es un proyecto pequeño. Los comentarios, la revisión de fotos, las comparaciones y contárselo a otros observadores ayudan.',
            'Birdr est un petit projet. Avis, relecture des photos, descriptions comparatives et le bouche-à-oreille auprès d’autres ornithos aident tous.',
            'Birdr ist ein kleines Projekt. Feedback, Fotoprüfung, Vergleichstexte und Weitersagen an andere Birding-Leute helfen alle.',
            'Birdr è un progetto piccolo. Feedback, revisione delle foto, descrizioni comparative e passaparola ad altri birdwatcher aiutano tutti.',
            'O Birdr é um projeto pequeno. Feedback, revisão de fotos, comparações e divulgar para outros observadores: tudo ajuda.',
            'Birdrは小さなプロジェクトです。フィードバック、写真確認、比較説明、他のバーダーへの紹介、どれも助かります。',
        ),
    ),
    ('Birdr FAQ – Free Bird Identification Quiz', ('Birdr FAQ – gratis quiz voor vogelherkenning', 'FAQ de Birdr – quiz gratis de identificación', 'FAQ Birdr – quiz gratuit d’identification', 'Birdr-FAQ – kostenloses Bestimmungsquiz', 'FAQ Birdr – quiz gratis di identificazione', 'FAQ do Birdr – quiz grátis de identificação', 'Birdr FAQ – 無料の鳥類識別クイズ')),
    (
        'Answers about Birdr: is it free, does it identify birds from a photo, and where you can play photo quizzes and country challenges.',
        (
            'Antwoorden over Birdr: is het gratis, herkent het vogels van een foto, en waar je fotoquizzen en landenuitdagingen speelt.',
            'Respuestas sobre Birdr: si es gratis, si identifica aves a partir de una foto, y dónde jugar quizzes de fotos y retos por país.',
            'Réponses sur Birdr : est-il gratuit, identifie-t-il les oiseaux à partir d’une photo, et où jouer aux quiz photo et défis pays.',
            'Antworten zu Birdr: Ist es kostenlos, bestimmt es Vögel anhand eines Fotos, und wo du Foto-Quiz und Länder-Challenges spielst.',
            'Risposte su Birdr: è gratis, identifica gli uccelli da una foto, e dove giocare quiz fotografici e sfide per paese.',
            'Respostas sobre o Birdr: é grátis, identifica aves a partir de uma foto, e onde jogar quizzes de fotos e desafios por país.',
            'Birdrについての答え。無料か、写真から識別するか、写真クイズや国別チャレンジはどこでプレイできるか。',
        ),
    ),
    ('Frequently asked questions', ('Veelgestelde vragen', 'Preguntas frecuentes', 'Questions fréquentes', 'Häufige Fragen', 'Domande frequenti', 'Perguntas frequentes', 'よくある質問')),
    (
        'Is Birdr free? Does it identify birds from a photo? Where can you play?',
        (
            'Is Birdr gratis? Herkent het vogels van een foto? Waar kun je spelen?',
            '¿Birdr es gratis? ¿Identifica aves a partir de una foto? ¿Dónde puedes jugar?',
            'Birdr est-il gratuit ? Identifie-t-il les oiseaux à partir d’une photo ? Où jouer ?',
            'Ist Birdr kostenlos? Bestimmt es Vögel anhand eines Fotos? Wo kannst du spielen?',
            'Birdr è gratis? Identifica gli uccelli da una foto? Dove puoi giocare?',
            'O Birdr é grátis? Ele identifica aves a partir de uma foto? Onde você pode jogar?',
            'Birdrは無料？写真から鳥を識別する？どこでプレイできる？',
        ),
    ),
    ('Try a quiz', ('Probeer een quiz', 'Probar un quiz', 'Essayer un quiz', 'Ein Quiz ausprobieren', 'Prova un quiz', 'Experimente um quiz', 'クイズを試す')),
]
