"""UI, help, community and testimonial strings. Locale order: nl, es, fr, de, it, pt-BR, ja."""

UI_ENTRIES: list[tuple[str, tuple[str, ...]]] = [
    ('Open Birdr', ('Open Birdr', 'Abrir Birdr', 'Ouvrir Birdr', 'Birdr öffnen', 'Apri Birdr', 'Abrir o Birdr', 'Birdrを開く')),
    ('Practise difficult birds', ('Oefen lastige vogels', 'Practica aves difíciles', 'S’entraîner sur les oiseaux difficiles', 'Schwierige Vögel üben', 'Esercitati sugli uccelli difficili', 'Pratique aves difíceis', '難しい鳥を練習')),
    ('See when a pair is fixed', ('Zie wanneer een paar is opgelost', 'Mira cuándo un par está resuelto', 'Voir quand une paire est réglée', 'Sehen, wann ein Paar sitzt', 'Vedi quando una coppia è sistemata', 'Veja quando um par está resolvido', 'ペアが定着したとき')),
    ('Best on the', ('Het best in de', 'Mejor en las', 'Mieux sur les', 'Am besten in den', 'Meglio nelle', 'Melhor nos', 'おすすめは')),
    ('iPhone and Android apps', ('iPhone- en Android-apps', 'apps de iPhone y Android', 'apps iPhone et Android', 'iPhone- und Android-Apps', 'app iPhone e Android', 'apps de iPhone e Android', 'iPhone・Androidアプリ')),
    ('More country quizzes', ('Meer landenquizzen', 'Más quizzes por país', 'Plus de quiz par pays', 'Mehr Länder-Quiz', 'Altri quiz per paese', 'Mais quizzes por país', 'ほかの国別クイズ')),
    ('How people play in {name}', ('Hoe mensen spelen in {name}', 'Cómo se juega en {name}', 'Comment on joue en {name}', 'Wie in {name} gespielt wird', 'Come si gioca in {name}', 'Como as pessoas jogam em {name}', '{name}でのプレイ')),
    ('Quizzes played', ('Gespeelde quizzen', 'Quizzes jugados', 'Quiz joués', 'Gespielte Quiz', 'Quiz giocati', 'Quizzes jogados', 'プレイされたクイズ')),
    ('1 player has taken a Birdr quiz on the {name} list.', ('1 speler heeft een Birdr-quiz op de lijst van {name} gedaan.', '1 jugador ha hecho un quiz de Birdr en la lista de {name}.', '1 joueur a fait un quiz Birdr sur la liste {name}.', '1 Spieler hat ein Birdr-Quiz auf der Liste von {name} gespielt.', '1 giocatore ha fatto un quiz Birdr sulla lista di {name}.', '1 jogador fez um quiz do Birdr na lista de {name}.', '{name}のリストでBirdrクイズをした人は1人です。')),
    ('{count} players have taken a Birdr quiz on the {name} list.', ('{count} spelers hebben een Birdr-quiz op de lijst van {name} gedaan.', '{count} jugadores han hecho un quiz de Birdr en la lista de {name}.', '{count} joueurs ont fait un quiz Birdr sur la liste {name}.', '{count} Spieler haben ein Birdr-Quiz auf der Liste von {name} gespielt.', '{count} giocatori hanno fatto un quiz Birdr sulla lista di {name}.', '{count} jogadores fizeram um quiz do Birdr na lista de {name}.', '{name}のリストでBirdrクイズをした人は{count}人です。')),
    ('Games played over time', ('Spellen in de tijd', 'Partidas a lo largo del tiempo', 'Parties dans le temps', 'Spiele im Zeitverlauf', 'Partite nel tempo', 'Jogos ao longo do tempo', '期間中のプレイ数')),
    ('Full Country Challenge leaderboard', ('Volledig klassement landenuitdaging', 'Clasificación completa del reto por país', 'Classement complet du défi pays', 'Vollständige Länder-Challenge-Rangliste', 'Classifica completa della sfida per paese', 'Ranking completo do desafio por país', '国別チャレンジの全ランキング')),
    ('Full high score list', ('Volledige highscorelijst', 'Lista completa de puntuaciones', 'Liste complète des scores', 'Vollständige Highscore-Liste', 'Elenco completo dei punteggi', 'Lista completa de recordes', 'ハイスコア全一覧')),
    ('Most missed birds', ('Meest gemiste vogels', 'Aves más falladas', 'Oiseaux les plus ratés', 'Am häufigsten verfehlte Vögel', 'Uccelli più sbagliati', 'Aves mais erradas', 'いちばん間違えられる鳥')),
    ('From quizzes on the {name} list.', ('Uit quizzen op de lijst van {name}.', 'De quizzes en la lista de {name}.', 'Issus des quiz sur la liste {name}.', 'Aus Quiz auf der Liste von {name}.', 'Dai quiz sulla lista di {name}.', 'De quizzes na lista de {name}.', '{name}のリストのクイズから。')),
    ('All missed species', ('Alle gemiste soorten', 'Todas las especies falladas', 'Toutes les espèces ratées', 'Alle verfehlten Arten', 'Tutte le specie sbagliate', 'Todas as espécies erradas', '間違えた種のすべて')),
    ('All confusing pairs', ('Alle verwarrende paren', 'Todos los pares confusos', 'Toutes les paires trompeuses', 'Alle verwirrenden Paare', 'Tutte le coppie ingannevoli', 'Todos os pares confusos', '紛らわしいペアのすべて')),
    ('versus', ('versus', 'frente a', 'contre', 'gegen', 'contro', 'versus', '対')),
    ('Play a quiz with {left} and {right}', ('Speel een quiz met {left} en {right}', 'Juega un quiz con {left} y {right}', 'Faire un quiz avec {left} et {right}', 'Ein Quiz mit {left} und {right} spielen', 'Fai un quiz con {left} e {right}', 'Jogue um quiz com {left} e {right}', '{left}と{right}のクイズ')),
    ('Thanks — your description is live.', ('Bedankt — je beschrijving staat live.', 'Gracias: tu descripción ya está publicada.', 'Merci — ta description est en ligne.', 'Danke — deine Beschreibung ist live.', 'Grazie: la descrizione è online.', 'Obrigado — sua descrição está no ar.', 'ありがとう。説明が公開されました。')),
    ('The community description was removed.', ('De communitybeschrijving is verwijderd.', 'Se eliminó la descripción de la comunidad.', 'La description communautaire a été supprimée.', 'Die Community-Beschreibung wurde entfernt.', 'La descrizione della community è stata rimossa.', 'A descrição da comunidade foi removida.', 'コミュニティの説明は削除されました。')),
    (
        'This text is taken from Birds of the World identification notes. It is not a rewritten field-guide card.',
        (
            'Deze tekst komt uit de identificatienotities van Birds of the World. Het is geen herschreven veldgidskaart.',
            'Este texto sale de las notas de identificación de Birds of the World. No es una ficha de guía reescrita.',
            'Ce texte vient des notes d’identification de Birds of the World. Ce n’est pas une fiche de guide réécrite.',
            'Dieser Text stammt aus den Bestimmungsnotizen von Birds of the World. Es ist keine umgeschriebene Feldführer-Karte.',
            'Questo testo viene dalle note di identificazione di Birds of the World. Non è una scheda da guida riscritta.',
            'Este texto vem das notas de identificação de Birds of the World. Não é um cartão de guia reescrito.',
            'この文は Birds of the World の識別ノートからです。フィールドガイドを書き直したものではありません。',
        ),
    ),
    (
        'O-o, we ran out of AI credits. I develop Birdr in my spare time, and there is no funding behind it right now. If you would like to help it grow, write to me at <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
        (
            'O-o, we zijn door de AI-credits heen. Ik ontwikkel Birdr in mijn vrije tijd, en er is nu geen financiering. Wil je helpen het te laten groeien, schrijf me dan op <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'O-o, se nos acabaron los créditos de IA. Desarrollo Birdr en mi tiempo libre, y ahora mismo no hay financiación. Si te apetece ayudar a que crezca, escríbeme a <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'O-o, on n’a plus de crédits IA. Je développe Birdr sur mon temps libre, et il n’y a pas de financement pour l’instant. Si tu as envie d’aider à le faire grandir, écris-moi à <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'O-o, unsere KI-Credits sind alle. Ich entwickle Birdr in meiner Freizeit, und es gibt gerade keine Finanzierung. Wenn du helfen möchtest, dass es wächst, schreib mir an <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'O-o, i crediti IA sono finiti. Sviluppo Birdr nel tempo libero, e al momento non c’è finanziamento. Se vuoi aiutare a farlo crescere, scrivimi a <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'O-o, os créditos de IA acabaram. Eu desenvolvo o Birdr no tempo livre, e agora não há financiamento. Se quiser ajudar a crescer, escreva para <a href="mailto:info@birdr.pro">info@birdr.pro</a>.',
            'おっと、AIのクレジットがなくなりました。Birdrは余暇に開発していて、今は資金がありません。成長を手伝いたい方は <a href="mailto:info@birdr.pro">info@birdr.pro</a> まで。',
        ),
    ),
    ('This text was generated by AI from several sources. It can contain mistakes.', ('Deze tekst is door AI gemaakt uit verschillende bronnen. Er kunnen fouten in staan.', 'Este texto lo generó la IA a partir de varias fuentes. Puede contener errores.', 'Ce texte a été généré par IA à partir de plusieurs sources. Il peut contenir des erreurs.', 'Dieser Text wurde von KI aus mehreren Quellen erzeugt. Er kann Fehler enthalten.', 'Questo testo è stato generato dall’IA da più fonti. Può contenere errori.', 'Este texto foi gerado por IA a partir de várias fontes. Pode ter erros.', 'この文は複数の出典からAIが生成しました。誤りが含まれることがあります。')),
    ('Show the community comparison', ('Toon de communityvergelijking', 'Ver la comparación de la comunidad', 'Voir la comparaison communautaire', 'Community-Vergleich anzeigen', 'Mostra il confronto della community', 'Ver a comparação da comunidade', 'コミュニティの比較を表示')),
    ('By {name}', ('Door {name}', 'Por {name}', 'Par {name}', 'Von {name}', 'Di {name}', 'Por {name}', '{name} による')),
    ('Show the AI-generated comparison', ('Toon de AI-vergelijking', 'Ver la comparación generada por IA', 'Voir la comparaison générée par IA', 'KI-Vergleich anzeigen', 'Mostra il confronto generato dall’IA', 'Ver a comparação gerada por IA', 'AI比較を表示')),
    (
        'Birdr is a community-driven project. If you know these birds, you can improve this comparison so others can tell them apart more easily.',
        (
            'Birdr is een communityproject. Als je deze vogels kent, kun je deze vergelijking verbeteren zodat anderen ze makkelijker uit elkaar houden.',
            'Birdr es un proyecto de comunidad. Si conoces estas aves, puedes mejorar esta comparación para que otros las distingan más fácilmente.',
            'Birdr est un projet communautaire. Si tu connais ces oiseaux, tu peux améliorer cette comparaison pour que d’autres les distinguent plus facilement.',
            'Birdr ist ein Community-Projekt. Wenn du diese Vögel kennst, kannst du den Vergleich verbessern, damit andere sie leichter unterscheiden.',
            'Birdr è un progetto della community. Se conosci questi uccelli, puoi migliorare questo confronto perché altri li distinguano più facilmente.',
            'O Birdr é um projeto da comunidade. Se você conhece essas aves, pode melhorar esta comparação para os outros as distinguirem melhor.',
            'Birdrはコミュニティのプロジェクトです。この鳥を知っているなら比較を良くして、ほかの人が見分けやすくできます。',
        ),
    ),
    ('Writing a comparison…', ('Vergelijking schrijven…', 'Escribiendo una comparación…', 'Rédaction d’une comparaison…', 'Vergleich wird geschrieben…', 'Scrittura del confronto…', 'Escrevendo uma comparação…', '比較を作成中…')),
    (
        'This looks up Birds of the World identification notes, then asks the model to contrast the pair. It can take a minute.',
        (
            'Dit zoekt identificatienotities van Birds of the World op en vraagt het model het paar te vergelijken. Het kan een minuut duren.',
            'Consulta las notas de identificación de Birds of the World y pide al modelo contrastar el par. Puede tardar un minuto.',
            'Cela cherche les notes d’identification de Birds of the World, puis demande au modèle de contraster la paire. Ça peut prendre une minute.',
            'Das schlägt Bestimmungsnotizen von Birds of the World nach und lässt das Modell das Paar gegenüberstellen. Es kann eine Minute dauern.',
            'Cerca le note di identificazione di Birds of the World, poi chiede al modello di contrapporre la coppia. Può richiedere un minuto.',
            'Consulta as notas de identificação de Birds of the World e pede ao modelo para contrastar o par. Pode levar um minuto.',
            'Birds of the World の識別ノートを引き、モデルにペアの対比を頼みます。1分ほどかかることがあります。',
        ),
    ),
    (
        'These two are often mixed up in quizzes. Look at the photos, then practise the pair until the field marks stick.',
        (
            'Deze twee worden in quizzen vaak door elkaar gehaald. Bekijk de foto’s en oefen het paar tot de kenmerken blijven hangen.',
            'Estas dos se mezclan a menudo en los quizzes. Mira las fotos y practica el par hasta que las marcas de campo se queden.',
            'Ces deux-là sont souvent mélangés dans les quiz. Regarde les photos, puis pratique la paire jusqu’à ce que les critères rentrent.',
            'Diese beiden werden in Quiz oft verwechselt. Schau dir die Fotos an und übe das Paar, bis die Feldmerkmale sitzen.',
            'Questi due si confondono spesso nei quiz. Guarda le foto, poi esercitati sulla coppia finché i caratteri restano.',
            'Essas duas se misturam bastante nos quizzes. Olhe as fotos e pratique o par até as marcas de campo grudarem.',
            'クイズでよく取り違えられる2種です。写真を見て、特徴が定着するまでペアを練習してください。',
        ),
    ),
    ('Comparison', ('Vergelijking', 'Comparación', 'Comparaison', 'Vergleich', 'Confronto', 'Comparação', '比較')),
    ('Delete description', ('Beschrijving verwijderen', 'Eliminar descripción', 'Supprimer la description', 'Beschreibung löschen', 'Elimina la descrizione', 'Excluir descrição', '説明を削除')),
    ('Submit a better description', ('Stuur een betere beschrijving', 'Enviar una descripción mejor', 'Envoyer une meilleure description', 'Eine bessere Beschreibung senden', 'Invia una descrizione migliore', 'Enviar uma descrição melhor', 'より良い説明を送る')),
    ('Please don’t copy and paste from copyright-protected sources. Write in your own words.', ('Kopieer niet uit bronnen met auteursrecht. Schrijf in je eigen woorden.', 'No copies y pegues de fuentes con copyright. Escribe con tus palabras.', 'Ne copie-colle pas de sources protégées. Écris avec tes mots.', 'Bitte nicht aus urheberrechtlich geschützten Quellen kopieren. Schreib in eigenen Worten.', 'Non copiare da fonti protette da copyright. Scrivi con parole tue.', 'Não copie de fontes protegidas por direitos autorais. Escreva com suas palavras.', '著作権のある出典からコピーしないでください。自分の言葉で書いてください。')),
    ('I understand', ('Ik begrijp het', 'Entendido', 'J’ai compris', 'Verstanden', 'Ho capito', 'Entendi', 'わかりました')),
    ('Use the same sections as the comparison. Your text is published immediately.', ('Gebruik dezelfde onderdelen als de vergelijking. Je tekst staat meteen live.', 'Usa las mismas secciones que la comparación. El texto se publica al momento.', 'Utilise les mêmes sections que la comparaison. Ton texte est publié tout de suite.', 'Nutze dieselben Abschnitte wie der Vergleich. Dein Text ist sofort veröffentlicht.', 'Usa le stesse sezioni del confronto. Il testo viene pubblicato subito.', 'Use as mesmas seções da comparação. Seu texto é publicado na hora.', '比較と同じ項目を使ってください。文章はすぐに公開されます。')),
    ('Formatting for {label}', ('Opmaak voor {label}', 'Formato de {label}', 'Mise en forme de {label}', 'Formatierung für {label}', 'Formattazione di {label}', 'Formatação de {label}', '{label}の書式')),
    ('Bold', ('Vet', 'Negrita', 'Gras', 'Fett', 'Grassetto', 'Negrito', '太字')),
    ('Italic', ('Cursief', 'Cursiva', 'Italique', 'Kursiv', 'Corsivo', 'Itálico', '斜体')),
    ('Bullet list', ('Opsomming', 'Lista con viñetas', 'Liste à puces', 'Aufzählung', 'Elenco puntato', 'Lista com marcadores', '箇条書き')),
    ('Numbered list', ('Genummerde lijst', 'Lista numerada', 'Liste numérotée', 'Nummerierte Liste', 'Elenco numerato', 'Lista numerada', '番号付きリスト')),
    ('Discard your changes?', ('Wijzigingen weggooien?', '¿Descartar los cambios?', 'Abandonner tes modifications ?', 'Änderungen verwerfen?', 'Scartare le modifiche?', 'Descartar as alterações?', '変更を破棄しますか？')),
    ('You have unsaved edits. If you leave now, those changes will be lost.', ('Je hebt niet-opgeslagen wijzigingen. Als je nu weggaat, gaan die verloren.', 'Tienes ediciones sin guardar. Si sales ahora, se perderán.', 'Tu as des modifications non enregistrées. Si tu pars maintenant, elles seront perdues.', 'Du hast ungespeicherte Änderungen. Wenn du jetzt gehst, gehen sie verloren.', 'Hai modifiche non salvate. Se esci ora, andranno perse.', 'Você tem edições não salvas. Se sair agora, elas serão perdidas.', '保存していない編集があります。今離れると失われます。')),
    ('Keep editing', ('Blijf bewerken', 'Seguir editando', 'Continuer à modifier', 'Weiter bearbeiten', 'Continua a modificare', 'Continuar editando', '編集を続ける')),
    ('Discard', ('Weggooien', 'Descartar', 'Abandonner', 'Verwerfen', 'Scarta', 'Descartar', '破棄')),
    ('Media type', ('Mediatype', 'Tipo de medio', 'Type de média', 'Medientyp', 'Tipo di media', 'Tipo de mídia', 'メディアの種類')),
    ('{name} illustration', ('Illustratie van {name}', 'Ilustración de {name}', 'Illustration de {name}', 'Illustration von {name}', 'Illustrazione di {name}', 'Ilustração de {name}', '{name}の図')),
    ('Play a quiz with {name} and similar species', ('Speel een quiz met {name} en gelijkende soorten', 'Juega un quiz con {name} y especies parecidas', 'Faire un quiz avec {name} et des espèces similaires', 'Ein Quiz mit {name} und ähnlichen Arten spielen', 'Fai un quiz con {name} e specie simili', 'Jogue um quiz com {name} e espécies parecidas', '{name}と似た種のクイズ')),
    ('View all photos, video and sound', ('Alle foto’s, video en geluid bekijken', 'Ver todas las fotos, vídeo y sonido', 'Voir toutes les photos, vidéos et sons', 'Alle Fotos, Videos und Töne ansehen', 'Vedi tutte le foto, i video e i suoni', 'Ver todas as fotos, vídeos e sons', '写真・動画・音声をすべて見る')),
    (
        'Birdr is a community-driven project, and many photos still need a human check. If you know this bird, you can help by reviewing its images.',
        (
            'Birdr is een communityproject, en veel foto’s moeten nog door iemand nagekeken worden. Als je deze vogel kent, kun je helpen door de beelden te beoordelen.',
            'Birdr es un proyecto de comunidad, y muchas fotos aún necesitan un visto humano. Si conoces esta ave, puedes ayudar revisando sus imágenes.',
            'Birdr est un projet communautaire, et beaucoup de photos attendent encore un œil humain. Si tu connais cet oiseau, tu peux aider en relisant ses images.',
            'Birdr ist ein Community-Projekt, und viele Fotos brauchen noch eine menschliche Prüfung. Wenn du diesen Vogel kennst, kannst du die Bilder prüfen.',
            'Birdr è un progetto della community, e molte foto aspettano ancora un controllo umano. Se conosci questo uccello, puoi aiutare rivedendo le immagini.',
            'O Birdr é um projeto da comunidade, e muitas fotos ainda precisam de um olhar humano. Se você conhece esta ave, pode ajudar revisando as imagens.',
            'Birdrはコミュニティのプロジェクトで、多くの写真がいまだ人の確認待ちです。この鳥を知っているなら、画像の確認で助けられます。',
        ),
    ),
    ('Often mixed up with', ('Vaak verward met', 'A menudo se confunde con', 'Souvent mélangé avec', 'Oft verwechselt mit', 'Spesso confuso con', 'Muitas vezes confundido com', 'よく取り違えられる相手')),
    (
        'In quizzes, players most often confuse {name} with these birds—either this species was picked by mistake, or the other way around.',
        (
            'In quizzen verwarren spelers {name} het vaakst met deze vogels—óf deze soort werd per ongeluk gekozen, of andersom.',
            'En los quizzes, los jugadores suelen confundir {name} con estas aves: o se eligió esta especie por error, o al revés.',
            'Dans les quiz, les joueurs confondent le plus souvent {name} avec ces oiseaux—soit cette espèce a été choisie par erreur, soit l’inverse.',
            'In Quiz verwechseln Spieler {name} am häufigsten mit diesen Vögeln—entweder wurde diese Art irrtümlich gewählt oder umgekehrt.',
            'Nei quiz i giocatori confondono più spesso {name} con questi uccelli: o questa specie è stata scelta per errore, o il contrario.',
            'Nos quizzes, os jogadores mais confundem {name} com estas aves—ou esta espécie foi escolhida por engano, ou o contrário.',
            'クイズでは、{name} をこれらの鳥とよく取り違えます。この種を誤って選ぶか、その逆です。',
        ),
    ),
    ('How Birdr teaches identification', ('Hoe Birdr herkenning leert', 'Cómo enseña Birdr a identificar', 'Comment Birdr enseigne l’identification', 'Wie Birdr Bestimmung lehrt', 'Come Birdr insegna l’identificazione', 'Como o Birdr ensina identificação', 'Birdrの識別の教え方')),
    ('Guides and information about the app.', ('Gidsen en informatie over de app.', 'Guías e información sobre la app.', 'Guides et infos sur l’app.', 'Leitfäden und Infos zur App.', 'Guide e informazioni sull’app.', 'Guias e informações sobre o app.', 'アプリについての案内と情報。')),
    ('draft', ('concept', 'borrador', 'brouillon', 'Entwurf', 'bozza', 'rascunho', '下書き')),
    ('No pages published yet.', ('Nog geen pagina’s gepubliceerd.', 'Aún no hay páginas publicadas.', 'Aucune page publiée pour l’instant.', 'Noch keine Seiten veröffentlicht.', 'Nessuna pagina pubblicata ancora.', 'Ainda não há páginas publicadas.', 'まだ公開ページはありません。')),
    (
        'Search Birdr’s species pages, see which birds people miss most in quizzes, and open the lookalikes that are hardest to tell apart.',
        (
            'Zoek in de soortpagina’s van Birdr, zie welke vogels mensen in quizzen het meest missen, en open de lookalikes die het lastigst uit elkaar te houden zijn.',
            'Busca las páginas de especies de Birdr, mira qué aves se fallan más en los quizzes y abre los sosias más difíciles de distinguir.',
            'Cherche les pages d’espèces de Birdr, vois quels oiseaux les gens ratent le plus dans les quiz, et ouvre les sosies les plus durs à distinguer.',
            'Durchsuche Birdrs Artseiten, sieh, welche Vögel in Quiz am häufigsten verfehlt werden, und öffne die Doppelgänger, die am schwersten zu unterscheiden sind.',
            'Cerca le pagine delle specie di Birdr, vedi quali uccelli si sbagliano di più nei quiz e apri i sosia più difficili da distinguere.',
            'Pesquise as páginas de espécies do Birdr, veja quais aves as pessoas mais erram nos quizzes e abra os sósias mais difíceis de distinguir.',
            'Birdrの種ページを探し、クイズでいちばん間違われる鳥を見て、見分けにくい似た種を開きます。',
        ),
    ),
    ('{count} species have a public page.', ('{count} soorten hebben een openbare pagina.', '{count} especies tienen una página pública.', '{count} espèces ont une page publique.', '{count} Arten haben eine öffentliche Seite.', '{count} specie hanno una pagina pubblica.', '{count} espécies têm uma página pública.', '{count}種に公開ページがあります。')),
    ('Search by common or scientific name', ('Zoek op gewone of wetenschappelijke naam', 'Busca por nombre común o científico', 'Chercher par nom commun ou scientifique', 'Nach Trivial- oder Wissenschaftsnamen suchen', 'Cerca per nome comune o scientifico', 'Pesquise por nome comum ou científico', '和名または学名で検索')),
    ('e.g. sparrowhawk or Accipiter nisus', ('bijv. sperwer of Accipiter nisus', 'p. ej. gavilán o Accipiter nisus', 'ex. épervier ou Accipiter nisus', 'z. B. Sperber oder Accipiter nisus', 'es. sparviero o Accipiter nisus', 'ex.: gavião ou Accipiter nisus', '例：ハイタカ、Accipiter nisus')),
    ('Results for “{query}” in {family}', ('Resultaten voor “{query}” in {family}', 'Resultados para “{query}” en {family}', 'Résultats pour « {query} » dans {family}', 'Ergebnisse für „{query}“ in {family}', 'Risultati per “{query}” in {family}', 'Resultados para “{query}” em {family}', '「{query}」の結果（{family}）')),
    ('Results for “{query}”', ('Resultaten voor “{query}”', 'Resultados para “{query}”', 'Résultats pour « {query} »', 'Ergebnisse für „{query}“', 'Risultati per “{query}”', 'Resultados para “{query}”', '「{query}」の結果')),
    ('Showing the first {n} matches. Narrow the search to see more.', ('De eerste {n} treffers. Versmal de zoekopdracht om meer te zien.', 'Mostrando los primeros {n} resultados. Afina la búsqueda para ver más.', 'Affichage des {n} premiers résultats. Affine la recherche pour en voir plus.', 'Die ersten {n} Treffer. Suche eingrenzen, um mehr zu sehen.', 'I primi {n} risultati. Restringi la ricerca per vederne di più.', 'Mostrando os primeiros {n} resultados. Afine a busca para ver mais.', '先頭の{n}件です。検索を絞るとさらに見られます。')),
    ('No matching species with a public page. Try another name, or browse the lists below.', ('Geen soort met een openbare pagina. Probeer een andere naam, of blader door de lijsten hieronder.', 'No hay especies con página pública. Prueba otro nombre, o mira las listas de abajo.', 'Aucune espèce avec une page publique. Essaie un autre nom, ou parcours les listes ci-dessous.', 'Keine Art mit öffentlicher Seite. Anderen Namen versuchen oder die Listen unten durchsehen.', 'Nessuna specie con pagina pubblica. Prova un altro nome, o sfoglia gli elenchi sotto.', 'Nenhuma espécie com página pública. Tente outro nome, ou veja as listas abaixo.', '公開ページのある種が見つかりません。別名を試すか、下のリストを見てください。')),
    ('From quizzes', ('Uit quizzen', 'De los quizzes', 'Issus des quiz', 'Aus Quiz', 'Dai quiz', 'Dos quizzes', 'クイズから')),
    ('Birds players pick by mistake most often.', ('Vogels die spelers het vaakst per ongeluk kiezen.', 'Aves que los jugadores eligen por error con más frecuencia.', 'Oiseaux que les joueurs choisissent le plus souvent par erreur.', 'Vögel, die Spieler am häufigsten irrtümlich wählen.', 'Uccelli che i giocatori scelgono per errore più spesso.', 'Aves que os jogadores mais escolhem por engano.', 'プレイヤーが誤っていちばん選びやすい鳥。')),
    ('Species most often mixed up with each other.', ('Soorten die het vaakst door elkaar gehaald worden.', 'Especies que más se confunden entre sí.', 'Espèces le plus souvent mélangées entre elles.', 'Arten, die am häufigsten miteinander verwechselt werden.', 'Specie più spesso confuse tra loro.', 'Espécies mais misturadas uma com a outra.', 'いちばんよく互いに取り違えられる種。')),
    ('Short field-mark notes for pairs that birders mix up.', ('Korte kenmerken voor paren die vogelaars door elkaar halen.', 'Notas breves de marcas de campo para pares que los observadores mezclan.', 'Courtes notes de critères pour les paires que les ornithos mélangent.', 'Kurze Feldmerkmale für Paare, die Birding-Leute verwechseln.', 'Brevi note sui caratteri per coppie che i birdwatcher confondono.', 'Notas curtas de marcas de campo para pares que os observadores misturam.', 'バーダーが取り違えるペア向けの、短い識別メモ。')),
    ('Browse by country', ('Blader per land', 'Explorar por país', 'Parcourir par pays', 'Nach Land durchsehen', 'Sfoglia per paese', 'Navegar por país', '国から探す')),
    ('Open a country list, then quiz on the birds you will actually meet.', ('Open een landenlijst en quiz dan op de vogels die je daar écht tegenkomt.', 'Abre la lista de un país y haz un quiz con las aves que realmente verás.', 'Ouvre une liste de pays, puis quiz sur les oiseaux que tu rencontreras vraiment.', 'Öffne eine Länderliste und quizze dann die Vögel, die du wirklich triffst.', 'Apri la lista di un paese, poi fai un quiz sugli uccelli che incontrerai davvero.', 'Abra a lista de um país e faça um quiz com as aves que você realmente vai encontrar.', '国のリストを開き、そこで実際に出会う鳥でクイズ。')),
    ('Practise tricky birds', ('Oefen lastige vogels', 'Practica aves difíciles', 'S’entraîner sur les oiseaux difficiles', 'Schwierige Vögel üben', 'Esercitati sugli uccelli difficili', 'Pratique aves difíceis', '苦手な鳥を練習')),
    (
        'Birdr quiz: identify a bird from a photo, with Black-legged Kittiwake marked as the correct answer',
        (
            'Birdr-quiz: herken een vogel van een foto, met drieteenmeeuw als goed antwoord gemarkeerd',
            'Quiz de Birdr: identifica un ave a partir de una foto, con gaviota tridáctila marcada como respuesta correcta',
            'Quiz Birdr : identifier un oiseau à partir d’une photo, avec la mouette tridactyle marquée comme bonne réponse',
            'Birdr-Quiz: Vogel anhand eines Fotos bestimmen, Dreizehenmöwe als richtige Antwort markiert',
            'Quiz Birdr: identifica un uccello da una foto, con gabbiano tridattilo segnato come risposta corretta',
            'Quiz do Birdr: identifique uma ave a partir de uma foto, com gaivota-tridáctila marcada como resposta certa',
            'Birdrクイズ：写真から鳥を識別。ミツユビカモメが正解としてマークされている',
        ),
    ),
    ('Focused drills on the species and confusing pairs you actually mix up.', ('Gerichte oefening op de soorten en verwarrende paren die jij door elkaar haalt.', 'Ejercicios centrados en las especies y pares confusos que de verdad mezclas.', 'Exercices ciblés sur les espèces et paires trompeuses que tu mélanges vraiment.', 'Gezielte Übungen zu den Arten und Paaren, die du wirklich verwechselst.', 'Esercizi mirati sulle specie e coppie che davvero confondi.', 'Treinos focados nas espécies e pares confusos que você realmente mistura.', '本当に取り違える種と紛らわしいペアに絞った練習。')),
    (
        'Learn to identify the birds of {name} yourself. The Birdr list has {count} species—photo quizzes and a Country Challenge take you from distinctive beginners to harder lookalikes.',
        (
            'Leer zelf de vogels van {name} herkennen. De Birdr-lijst heeft {count} soorten—fotoquizzen en een landenuitdaging gaan van opvallende beginners tot lastigere lookalikes.',
            'Aprende a identificar tú mismo las aves de {name}. La lista de Birdr tiene {count} especies: quizzes de fotos y un reto por país van de principiantes distintivos a sosias más difíciles.',
            'Apprends à identifier toi-même les oiseaux de {name}. La liste Birdr compte {count} espèces—quiz photo et défi pays vont des débutants distinctifs aux sosies plus durs.',
            'Lerne, die Vögel von {name} selbst zu bestimmen. Die Birdr-Liste hat {count} Arten—Foto-Quiz und eine Länder-Challenge führen von markanten Anfängern zu schwierigeren Doppelgängern.',
            'Impara a identificare da solo gli uccelli di {name}. La lista Birdr ha {count} specie: quiz fotografici e una sfida per paese vanno dai principianti distintivi ai sosia più difficili.',
            'Aprenda a identificar você mesmo as aves de {name}. A lista do Birdr tem {count} espécies—quizzes de fotos e um desafio por país vão de iniciantes marcantes a sósias mais difíceis.',
            '{name}の鳥を自分で見分けられるようになろう。Birdrのリストは{count}種。写真クイズと国別チャレンジで、わかりやすい初級から難しい似た種まで。',
        ),
    ),
    (
        'A one-off quiz is a short session on this country’s list. A Country Challenge is structured practice with levels, so you keep meeting new birds instead of repeating only the easy ones.',
        (
            'Een losse quiz is een korte sessie op de lijst van dit land. Een landenuitdaging is gestructureerde oefening met levels, zodat je nieuwe vogels blijft tegenkomen in plaats van alleen de makkelijke te herhalen.',
            'Un quiz suelto es una sesión corta en la lista de este país. Un reto por país es práctica estructurada con niveles, para seguir viendo aves nuevas en vez de repetir solo las fáciles.',
            'Un quiz isolé est une session courte sur la liste de ce pays. Un défi pays est un entraînement structuré avec des niveaux, pour continuer à voir de nouveaux oiseaux au lieu de répéter seulement les faciles.',
            'Ein einzelnes Quiz ist eine kurze Runde auf der Liste dieses Landes. Eine Länder-Challenge ist strukturiertes Üben mit Leveln, damit du neue Vögel siehst statt nur die leichten zu wiederholen.',
            'Un quiz isolato è una sessione breve sulla lista di questo paese. Una sfida per paese è pratica strutturata con livelli, così continui a incontrare uccelli nuovi invece di ripetere solo i facili.',
            'Um quiz avulso é uma sessão curta na lista deste país. Um desafio por país é prática estruturada com níveis, para você continuar vendo aves novas em vez de repetir só as fáceis.',
            '一回のクイズはこの国のリストでの短いセッション。国別チャレンジはレベル付きの練習なので、易しい種ばかり繰り返さず、新しい鳥に出会い続けます。',
        ),
    ),
    ('Countries on Birdr', ('Landen op Birdr', 'Países en Birdr', 'Pays sur Birdr', 'Länder auf Birdr', 'Paesi su Birdr', 'Países no Birdr', 'Birdrの国')),
    ('App screenshots', ('App-screenshots', 'Capturas de la app', 'Captures de l’app', 'App-Screenshots', 'Screenshot dell’app', 'Capturas do app', 'アプリの画面')),
    (
        'Every quiz has a level, plus a few other settings. Start with distinctive birds, then work up to rare lookalikes and typing the name yourself.',
        (
            'Elke quiz heeft een level, plus een paar andere instellingen. Begin met opvallende vogels en werk toe naar zeldzame lookalikes en zelf de naam typen.',
            'Cada quiz tiene un nivel, más unos ajustes. Empieza con aves distintivas y llega a sosias raros y a escribir el nombre tú mismo.',
            'Chaque quiz a un niveau, plus quelques autres réglages. Commence par des oiseaux distinctifs, puis monte jusqu’aux sosies rares et à taper le nom toi-même.',
            'Jedes Quiz hat ein Level und ein paar andere Einstellungen. Starte mit markanten Vögeln, dann seltene Doppelgänger und den Namen selbst tippen.',
            'Ogni quiz ha un livello, più altre impostazioni. Inizia con uccelli distintivi, poi arriva ai sosia rari e a scrivere il nome tu.',
            'Cada quiz tem um nível, mais alguns ajustes. Comece com aves marcantes e chegue a sósias raras e a digitar o nome você mesmo.',
            'どのクイズにもレベルと、ほかの設定が少しあります。特徴のはっきりした鳥から始め、珍しい似た種、自分で名前を入力する段階へ。',
        ),
    ),
    ('Birds people mix up most', ('Vogels die mensen het meest door elkaar halen', 'Aves que más se confunden', 'Oiseaux que les gens mélangent le plus', 'Vögel, die am häufigsten verwechselt werden', 'Uccelli che si confondono di più', 'Aves que as pessoas mais misturam', 'いちばん取り違えられる鳥')),
    (
        'These are the species and pairs with the most quiz mistakes. Open a page, then practise them until they stick.',
        (
            'Dit zijn de soorten en paren met de meeste quizfouten. Open een pagina en oefen tot ze blijven hangen.',
            'Estas son las especies y pares con más errores en el quiz. Abre una página y practícalas hasta que se queden.',
            'Ce sont les espèces et paires avec le plus d’erreurs de quiz. Ouvre une page, puis pratique jusqu’à ce que ça rentre.',
            'Das sind die Arten und Paare mit den meisten Quizfehlern. Öffne eine Seite und übe, bis sie sitzen.',
            'Queste sono le specie e coppie con più errori nei quiz. Apri una pagina, poi esercitati finché restano.',
            'Estas são as espécies e pares com mais erros de quiz. Abra uma página e pratique até grudar.',
            'クイズでの間違いがいちばん多い種とペアです。ページを開き、定着するまで練習してください。',
        ),
    ),
    ('Spread the word', ('Vertel het verder', 'Corre la voz', 'Faites-le connaître', 'Weitersagen', 'Spargi la voce', 'Divulgue', '広めてください')),
    ('See a newsletter example', ('Bekijk een nieuwsbriefvoorbeeld', 'Ver un ejemplo de boletín', 'Voir un exemple de bulletin', 'Newsletter-Beispiel ansehen', 'Vedi un esempio di notiziario', 'Ver um exemplo de boletim', '会報の例を見る')),
    ('Spread Birdr', ('Verspreid Birdr', 'Difunde Birdr', 'Faites connaître Birdr', 'Birdr bekannt machen', 'Diffondi Birdr', 'Divulgue o Birdr', 'Birdrを広める')),
    ('Add it to your bird club newsletter', ('Zet het in de clubnieuwsbrief', 'Añádelo al boletín del club', 'Ajoutez-le au bulletin du club', 'In den Club-Newsletter', 'Mettilo nel notiziario del club', 'Coloque no boletim do clube', 'クラブ会報に載せる')),
    ('Example newsletter item', ('Voorbeeld nieuwsbriefbericht', 'Ejemplo de nota para el boletín', 'Exemple d’article de bulletin', 'Beispiel für einen Newsletter-Text', 'Esempio di voce per il notiziario', 'Exemplo de item de boletim', '会報記事の例')),
    ('Example club newsletter item', ('Voorbeeld clubnieuwsbrief', 'Ejemplo de boletín de club', 'Exemple de bulletin de club', 'Beispiel Club-Newsletter', 'Esempio di notiziario del club', 'Exemplo de boletim de clube', 'クラブ会報の例')),
    ('Copy', ('Kopieer', 'Copiar', 'Copier', 'Kopieren', 'Copia', 'Copiar', 'コピー')),
    ('Copied', ('Gekopieerd', 'Copiado', 'Copié', 'Kopiert', 'Copiato', 'Copiado', 'コピーしました')),
    ('Could not copy', ('Kopiëren lukte niet', 'No se pudo copiar', 'Impossible de copier', 'Kopieren fehlgeschlagen', 'Impossibile copiare', 'Não foi possível copiar', 'コピーできませんでした')),
    ('A free way to practise bird ID between field trips', ('Gratis oefenen met vogelherkenning tussen excursies door', 'Una forma gratis de practicar identificación entre salidas', 'Un moyen gratuit de s’entraîner à l’ID entre les sorties', 'Kostenlos Vogelbestimmung zwischen Exkursionen üben', 'Un modo gratis di esercitarsi all’ID tra le uscite', 'Um jeito grátis de praticar identificação entre saídas', '探鳥の合間に無料で識別練習')),
    ('Quizzes, challenges and Flocks', ('Quizzen, challenges en Flocks', 'Quizzes, retos y Flocks', 'Quiz, défis et Flocks', 'Quiz, Challenges und Flocks', 'Quiz, sfide e Flocks', 'Quizzes, desafios e Flocks', 'クイズ、チャレンジ、Flocks')),
    ('Pick a country and start', ('Kies een land en start', 'Elige un país y empieza', 'Choisis un pays et lance', 'Land wählen und starten', 'Scegli un paese e parti', 'Escolha um país e comece', '国を選んでスタート')),
    ('Identify the bird from a photo', ('Herken de vogel van een foto', 'Identifica el ave a partir de una foto', 'Identifier l’oiseau à partir d’une photo', 'Den Vogel anhand eines Fotos bestimmen', 'Identifica l’uccello da una foto', 'Identifique a ave a partir de uma foto', '写真から鳥を識別')),
    ('Review more pictures', ('Bekijk meer foto’s', 'Ver más fotos', 'Voir plus de photos', 'Mehr Fotos ansehen', 'Vedi altre foto', 'Veja mais fotos', '写真をもっと見る')),
    ('Starts easy. Ends tough.', ('Begint makkelijk. Eindigt lastig.', 'Empieza fácil. Acaba duro.', 'Ça commence facile. Ça finit dur.', 'Fängt leicht an. Wird hart.', 'Inizia facile. Finisce tosta.', 'Começa fácil. Termina difícil.', '最初は易しく、終わりは厳しい。')),
    ('Drill similar-looking species', ('Oefen gelijkende soorten', 'Practica especies parecidas', 'Travailler les espèces ressemblantes', 'Ähnliche Arten üben', 'Esercitati su specie simili', 'Treine espécies parecidas', '似た種を練習')),
    ('Your personal mix-ups', ('Jouw persoonlijke verwarringen', 'Tus confusiones personales', 'Tes confusions perso', 'Deine persönlichen Verwechslungen', 'Le tue confusioni personali', 'Suas confusões pessoais', 'あなた専用の取り違え')),
    ('Practise a confusing pair', ('Oefen een verwarrend paar', 'Practica un par confuso', 'Pratiquer une paire trompeuse', 'Ein verwirrendes Paar üben', 'Esercitati su una coppia ingannevole', 'Pratique um par confuso', '紛らわしいペアを練習')),
    ('Country Challenge, from easy to hard', ('Landenuitdaging, van makkelijk naar lastig', 'Reto por país, de fácil a difícil', 'Défi pays, du facile au difficile', 'Länder-Challenge, von leicht nach schwer', 'Sfida per paese, dal facile al difficile', 'Desafio por país, do fácil ao difícil', '国別チャレンジ、易しいから難しいまで')),
    ('My Tricky Birds screenshots', ('Screenshots van Mijn lastige vogels', 'Capturas de Mis aves difíciles', 'Captures de Mes oiseaux difficiles', 'Screenshots von Meine schwierigen Vögel', 'Screenshot de I miei uccelli difficili', 'Capturas de Minhas aves difíceis', '苦手な鳥の画面')),
    ('Birdr screenshots', ('Birdr-screenshots', 'Capturas de Birdr', 'Captures Birdr', 'Birdr-Screenshots', 'Screenshot di Birdr', 'Capturas do Birdr', 'Birdrの画面')),
    ('Country challenge screenshot', ('Screenshot landenuitdaging', 'Captura del reto por país', 'Capture du défi pays', 'Screenshot der Länder-Challenge', 'Screenshot della sfida per paese', 'Captura do desafio por país', '国別チャレンジの画面')),
    ('Thank you. We read every message.', ('Dank je. We lezen elk bericht.', 'Gracias. Leemos cada mensaje.', 'Merci. On lit chaque message.', 'Danke. Wir lesen jede Nachricht.', 'Grazie. Leggiamo ogni messaggio.', 'Obrigado. Lemos cada mensagem.', 'ありがとう。すべてのメッセージを読んでいます。')),
    ('Found a bug, have a suggestion, or something that worked well? Tell us here, or write to', ('Een bug, een suggestie, of iets dat juist goed ging? Vertel het hier, of mail naar', '¿Un error, una sugerencia o algo que funcionó bien? Cuéntanoslo aquí, o escribe a', 'Un bug, une suggestion, ou quelque chose qui a bien marché ? Dis-le ici, ou écris à', 'Einen Fehler, einen Vorschlag oder etwas, das gut lief? Schreib hier oder an', 'Un bug, un suggerimento, o qualcosa che ha funzionato bene? Diccelo qui, o scrivi a', 'Achou um bug, tem uma sugestão, ou algo que funcionou bem? Conte aqui, ou escreva para', '不具合、提案、うまくいったこと？ここに書くか、メールを')),
    ('Please write a short message.', ('Schrijf een kort bericht.', 'Escribe un mensaje breve.', 'Écris un court message.', 'Bitte eine kurze Nachricht schreiben.', 'Scrivi un breve messaggio.', 'Escreva uma mensagem curta.', '短いメッセージを書いてください。')),
    ('That email address does not look valid.', ('Dat e-mailadres lijkt niet geldig.', 'Esa dirección de correo no parece válida.', 'Cette adresse e-mail ne semble pas valide.', 'Diese E-Mail-Adresse sieht ungültig aus.', 'Quell’indirizzo email non sembra valido.', 'Esse e-mail não parece válido.', 'そのメールアドレスは正しくないようです。')),
    ('Review {name} photos', ('Beoordeel foto’s van {name}', 'Revisar fotos de {name}', 'Relire les photos de {name}', 'Fotos von {name} prüfen', 'Rivedi le foto di {name}', 'Revisar fotos de {name}', '{name}の写真を確認')),
    ('Review photos from any country', ('Beoordeel foto’s van elk land', 'Revisar fotos de cualquier país', 'Relire les photos de n’importe quel pays', 'Fotos aus jedem Land prüfen', 'Rivedi le foto di qualsiasi paese', 'Revisar fotos de qualquer país', 'どの国の写真でも確認')),
    ('Review media', ('Beoordeel media', 'Revisar medios', 'Relire les médias', 'Medien prüfen', 'Rivedi i media', 'Revisar mídia', 'メディアを確認')),
    ('Photo reviews', ('Fotobeoordelingen', 'Revisiones de fotos', 'Relectures de photos', 'Fotoprüfungen', 'Revisioni delle foto', 'Revisões de fotos', '写真の確認')),
    ('Accepted', ('Goedgekeurd', 'Aceptadas', 'Acceptées', 'Angenommen', 'Accettate', 'Aceitas', '承認')),
    ('Rejected', ('Afgewezen', 'Rechazadas', 'Refusées', 'Abgelehnt', 'Rifiutate', 'Rejeitadas', '却下')),
    ('You have not reviewed any photos yet.', ('Je hebt nog geen foto’s beoordeeld.', 'Aún no has revisado ninguna foto.', 'Tu n’as encore relu aucune photo.', 'Du hast noch keine Fotos geprüft.', 'Non hai ancora rivisto nessuna foto.', 'Você ainda não revisou nenhuma foto.', 'まだ写真を確認していません。')),
    ('Comparisons you have written', ('Vergelijkingen die je hebt geschreven', 'Comparaciones que has escrito', 'Comparaisons que tu as écrites', 'Vergleiche, die du geschrieben hast', 'Confronti che hai scritto', 'Comparações que você escreveu', 'あなたが書いた比較')),
    ('Log in to see the comparisons you have published and the photos you have reviewed.', ('Log in om de vergelijkingen te zien die je hebt gepubliceerd en de foto’s die je hebt beoordeeld.', 'Inicia sesión para ver las comparaciones que has publicado y las fotos que has revisado.', 'Connecte-toi pour voir les comparaisons que tu as publiées et les photos que tu as relues.', 'Melde dich an, um die veröffentlichten Vergleiche und geprüften Fotos zu sehen.', 'Accedi per vedere i confronti pubblicati e le foto che hai rivisto.', 'Entre para ver as comparações que você publicou e as fotos que revisou.', '公開した比較と確認した写真を見るにはログインしてください。')),
    (
        'You have not published a comparison yet. Open a confusing pair and write a better description so others can tell the birds apart.',
        (
            'Je hebt nog geen vergelijking gepubliceerd. Open een verwarrend paar en schrijf een betere beschrijving zodat anderen de vogels uit elkaar kunnen houden.',
            'Aún no has publicado una comparación. Abre un par confuso y escribe una descripción mejor para que otros distingan las aves.',
            'Tu n’as pas encore publié de comparaison. Ouvre une paire trompeuse et écris une meilleure description pour que d’autres distinguent les oiseaux.',
            'Du hast noch keinen Vergleich veröffentlicht. Öffne ein verwirrendes Paar und schreibe eine bessere Beschreibung, damit andere die Vögel unterscheiden können.',
            'Non hai ancora pubblicato un confronto. Apri una coppia ingannevole e scrivi una descrizione migliore perché altri distinguano gli uccelli.',
            'Você ainda não publicou uma comparação. Abra um par confuso e escreva uma descrição melhor para os outros distinguirem as aves.',
            'まだ比較を公開していません。紛らわしいペアを開き、ほかの人が見分けられるよう、より良い説明を書いてください。',
        ),
    ),
    (
        'Birdr is a community-driven project. Comparisons you write help other birders tell similar species apart, and photo reviews keep the quiz images accurate.',
        (
            'Birdr is een communityproject. Vergelijkingen die jij schrijft helpen anderen gelijkende soorten uit elkaar te houden, en fotobeoordelingen houden de quizbeelden accuraat.',
            'Birdr es un proyecto de comunidad. Las comparaciones que escribes ayudan a otros a distinguir especies parecidas, y las revisiones de fotos mantienen precisas las imágenes del quiz.',
            'Birdr est un projet communautaire. Tes comparaisons aident d’autres ornithos à distinguer des espèces ressemblantes, et les relectures de photos gardent les images du quiz justes.',
            'Birdr ist ein Community-Projekt. Deine Vergleiche helfen anderen, ähnliche Arten zu unterscheiden, und Fotoprüfungen halten die Quizbilder korrekt.',
            'Birdr è un progetto della community. I confronti che scrivi aiutano altri a distinguere specie simili, e le revisioni delle foto tengono accurate le immagini dei quiz.',
            'O Birdr é um projeto da comunidade. As comparações que você escreve ajudam outros a distinguir espécies parecidas, e as revisões de fotos mantêm as imagens do quiz corretas.',
            'Birdrはコミュニティのプロジェクトです。あなたが書く比較は似た種の見分けに役立ち、写真確認はクイズ画像の正確さを保ちます。',
        ),
    ),
    ('No images available', ('Geen afbeeldingen beschikbaar', 'No hay imágenes disponibles', 'Aucune image disponible', 'Keine Bilder verfügbar', 'Nessuna immagine disponibile', 'Nenhuma imagem disponível', '画像がありません')),
    ('No videos available', ('Geen video’s beschikbaar', 'No hay vídeos disponibles', 'Aucune vidéo disponible', 'Keine Videos verfügbar', 'Nessun video disponibile', 'Nenhum vídeo disponível', '動画がありません')),
    ('No sounds available', ('Geen geluiden beschikbaar', 'No hay sonidos disponibles', 'Aucun son disponible', 'Keine Töne verfügbar', 'Nessun suono disponibile', 'Nenhum som disponível', '音声がありません')),
    ('Could not load media. Try again later.', ('Media laden mislukt. Probeer later opnieuw.', 'No se pudo cargar el medio. Inténtalo más tarde.', 'Impossible de charger le média. Réessaie plus tard.', 'Medien konnten nicht geladen werden. Später erneut versuchen.', 'Impossibile caricare i media. Riprova più tardi.', 'Não foi possível carregar a mídia. Tente mais tarde.', 'メディアを読み込めませんでした。あとで再試行してください。')),
    ('Could not generate the comparison.', ('Vergelijking genereren mislukt.', 'No se pudo generar la comparación.', 'Impossible de générer la comparaison.', 'Vergleich konnte nicht erzeugt werden.', 'Impossibile generare il confronto.', 'Não foi possível gerar a comparação.', '比較を生成できませんでした。')),
    ('A handbook comparison is not available yet.', ('Er is nog geen handboekvergelijking.', 'Aún no hay una comparación de handbook.', 'Une comparaison handbook n’est pas encore disponible.', 'Ein Handbook-Vergleich ist noch nicht verfügbar.', 'Un confronto da handbook non è ancora disponibile.', 'Uma comparação de handbook ainda não está disponível.', 'ハンドブック比較はまだありません。')),
    ('Video', ('Video', 'Vídeo', 'Vidéo', 'Video', 'Video', 'Vídeo', '動画')),
    (
        'The bird comparisons are thorough and could really help people improve their identification skills.',
        (
            'De vogelvergelijkingen zijn grondig en kunnen mensen écht helpen hun herkenning te verbeteren.',
            'Las comparaciones de aves son minuciosas y pueden ayudar de verdad a mejorar la identificación.',
            'Les comparaisons d’oiseaux sont soignées et peuvent vraiment aider à progresser en identification.',
            'Die Vogelvergleiche sind gründlich und können wirklich helfen, die Bestimmung zu verbessern.',
            'I confronti tra uccelli sono approfonditi e possono davvero aiutare a migliorare l’identificazione.',
            'As comparações de aves são cuidadosas e podem mesmo ajudar a melhorar a identificação.',
            '鳥の比較が丁寧で、識別力を上げるのに本当に役立ちそうです。',
        ),
    ),
    ('Birdr works well—even with Finnish bird names.', ('Birdr werkt goed—ook met Finse vogelnamen.', 'Birdr funciona bien, incluso con nombres de aves en finés.', 'Birdr marche bien—même avec les noms d’oiseaux finlandais.', 'Birdr funktioniert gut—auch mit finnischen Vogelnamen.', 'Birdr funziona bene, anche con i nomi finlandesi degli uccelli.', 'O Birdr funciona bem—até com nomes de aves em finlandês.', 'Birdrはフィンランド語の鳥名でもきちんと動きます。')),
    (
        'The Pro and Expert levels offer exactly the kind of serious identification training I was looking for.',
        (
            'De Pro- en Expert-levels bieden precies de serieuze herkenningstraining die ik zocht.',
            'Los niveles Pro y Experto ofrecen exactamente el entrenamiento serio de identificación que buscaba.',
            'Les niveaux Pro et Expert offrent exactement l’entraînement sérieux à l’identification que je cherchais.',
            'Die Pro- und Expert-Level bieten genau das ernste Bestimmungstraining, das ich gesucht habe.',
            'I livelli Pro ed Esperto offrono esattamente l’allenamento serio all’identificazione che cercavo.',
            'Os níveis Pro e Expert oferecem exatamente o treino sério de identificação que eu procurava.',
            'プロとエキスパートのレベルは、探していた本格的な識別トレーニングそのものです。',
        ),
    ),
    (
        'The app looks appealing and friendly, while the higher levels provide a genuine challenge.',
        (
            'De app oogt aantrekkelijk en vriendelijk, terwijl de hogere levels een échte uitdaging zijn.',
            'La app se ve atractiva y amable, mientras que los niveles altos dan un reto de verdad.',
            'L’app a l’air attrayante et amicale, et les niveaux élevés offrent un vrai défi.',
            'Die App wirkt ansprechend und freundlich, die höheren Level sind eine echte Herausforderung.',
            'L’app è gradevole e amichevole, mentre i livelli più alti danno una vera sfida.',
            'O app parece atraente e amigável, e os níveis mais altos dão um desafio de verdade.',
            'アプリは親しみやすく、上位レベルは本物の難しさがあります。',
        ),
    ),
    (
        'I really like the similar-species tests. They’re a great way to practise difficult birds.',
        (
            'Ik vind de tests met gelijkende soorten heel sterk. Een goede manier om lastige vogels te oefenen.',
            'Me gustan mucho las pruebas de especies parecidas. Son una gran forma de practicar aves difíciles.',
            'J’aime vraiment les tests d’espèces ressemblantes. C’est un super moyen de s’entraîner sur les oiseaux difficiles.',
            'Die Tests mit ähnlichen Arten gefallen mir sehr. Eine tolle Art, schwierige Vögel zu üben.',
            'Mi piacciono molto i test sulle specie simili. Sono un ottimo modo per esercitarsi sugli uccelli difficili.',
            'Gosto muito dos testes de espécies parecidas. São um ótimo jeito de praticar aves difíceis.',
            '似た種のテストがとても良いです。難しい鳥の練習にぴったりです。',
        ),
    ),
    (
        'Birdr has massively improved my bird recognition in a surprisingly short time.',
        (
            'Birdr heeft mijn vogelherkenning in verrassend korte tijd enorm verbeterd.',
            'Birdr ha mejorado muchísimo mi reconocimiento de aves en un tiempo sorprendentemente corto.',
            'Birdr a énormément amélioré ma reconnaissance des oiseaux en un temps étonnamment court.',
            'Birdr hat meine Vogelbestimmung in überraschend kurzer Zeit enorm verbessert.',
            'Birdr ha migliorato moltissimo il mio riconoscimento degli uccelli in un tempo sorprendentemente breve.',
            'O Birdr melhorou muito meu reconhecimento de aves em um tempo surpreendentemente curto.',
            'Birdrのおかげで、驚くほど短い期間で鳥の識別が大きく上達しました。',
        ),
    ),
    ('A fun and educational way to sharpen your bird-identification skills.', ('Een leuke en leerzame manier om je vogelherkenning aan te scherpen.', 'Una forma divertida y educativa de afilar la identificación de aves.', 'Un moyen amusant et pédagogique d’affûter l’identification des oiseaux.', 'Eine unterhaltsame und lehrreiche Art, die Vogelbestimmung zu schärfen.', 'Un modo divertente e formativo per affinare l’identificazione degli uccelli.', 'Um jeito divertido e educativo de afiar a identificação de aves.', '楽しく学べる、鳥の識別スキルの磨き方。')),
    (
        'The Country Challenge is great! It’s a fun way to learn the birds of different countries.',
        (
            'De landenuitdaging is geweldig! Een leuke manier om de vogels van verschillende landen te leren.',
            '¡El reto por país es genial! Es una forma divertida de aprender las aves de distintos países.',
            'Le défi pays est super ! C’est un moyen amusant d’apprendre les oiseaux de différents pays.',
            'Die Länder-Challenge ist toll! Eine unterhaltsame Art, die Vögel verschiedener Länder zu lernen.',
            'La sfida per paese è fantastica! Un modo divertente per imparare gli uccelli di paesi diversi.',
            'O desafio por país é ótimo! É um jeito divertido de aprender as aves de países diferentes.',
            '国別チャレンジが最高です！いろいろな国の鳥を楽しく学べます。',
        ),
    ),
    ('A great way to study the birds you might encounter on your next trip.', ('Een goede manier om de vogels te leren die je op je volgende reis kunt tegenkomen.', 'Una gran forma de estudiar las aves que puedes ver en tu próximo viaje.', 'Un super moyen d’étudier les oiseaux que tu pourrais rencontrer au prochain voyage.', 'Eine tolle Art, die Vögel zu lernen, die du auf der nächsten Reise treffen könntest.', 'Un ottimo modo per studiare gli uccelli che potresti incontrare nel prossimo viaggio.', 'Um ótimo jeito de estudar as aves que você pode encontrar na próxima viagem.', '次の旅で出会いそうな鳥を学ぶのにぴったりです。')),
    (
        'The confusing-pairs games make practising difficult species both focused and fun.',
        (
            'De spellen met verwarrende paren maken oefenen met lastige soorten gericht én leuk.',
            'Los juegos de pares confusos hacen que practicar especies difíciles sea centrado y divertido.',
            'Les jeux de paires trompeuses rendent l’entraînement sur les espèces difficiles à la fois ciblé et amusant.',
            'Die Spiele mit verwirrenden Paaren machen das Üben schwieriger Arten fokussiert und unterhaltsam.',
            'I giochi sulle coppie ingannevoli rendono la pratica delle specie difficili mirata e divertente.',
            'Os jogos de pares confusos tornam a prática de espécies difíceis focada e divertida.',
            '紛らわしいペアのゲームは、難しい種の練習を集中的かつ楽しくしてくれます。',
        ),
    ),
    (
        'I’m very happy with Birdr. It’s a fantastic initiative, and it keeps getting better.',
        (
            'Ik ben erg blij met Birdr. Het is een fantastisch initiatief, en het wordt steeds beter.',
            'Estoy muy contento con Birdr. Es una iniciativa fantástica, y no para de mejorar.',
            'Je suis très content de Birdr. C’est une initiative formidable, et ça continue de s’améliorer.',
            'Ich bin sehr zufrieden mit Birdr. Eine fantastische Initiative, und sie wird immer besser.',
            'Sono molto contento di Birdr. È un’iniziativa fantastica, e continua a migliorare.',
            'Estou muito feliz com o Birdr. É uma iniciativa fantástica, e não para de melhorar.',
            'Birdrにとても満足しています。すばらしい取り組みで、どんどん良くなっています。',
        ),
    ),
    (
        'The <a href="https://www.facebook.com/groups/birdrcommunity">Facebook group</a> is the place to have discussions with other birders.',
        (
            'De <a href="https://www.facebook.com/groups/birdrcommunity">Facebookgroep</a> is de plek voor gesprekken met andere vogelaars.',
            'El <a href="https://www.facebook.com/groups/birdrcommunity">grupo de Facebook</a> es el sitio para hablar con otros observadores.',
            'Le <a href="https://www.facebook.com/groups/birdrcommunity">groupe Facebook</a> est l’endroit pour discuter avec d’autres ornithos.',
            'Die <a href="https://www.facebook.com/groups/birdrcommunity">Facebook-Gruppe</a> ist der Ort für Gespräche mit anderen Birding-Leuten.',
            'Il <a href="https://www.facebook.com/groups/birdrcommunity">gruppo Facebook</a> è il posto per discutere con altri birdwatcher.',
            'O <a href="https://www.facebook.com/groups/birdrcommunity">grupo do Facebook</a> é o lugar para conversar com outros observadores.',
            'ほかのバーダーと話す場所は <a href="https://www.facebook.com/groups/birdrcommunity">Facebookグループ</a> です。',
        ),
    ),
    (
        'To report a bug or request a feature, <a href="https://github.com/birdr-app/birdr/issues">submit a ticket on GitHub</a>.',
        (
            'Om een bug te melden of een functie te vragen, <a href="https://github.com/birdr-app/birdr/issues">dien een ticket in op GitHub</a>.',
            'Para informar de un error o pedir una función, <a href="https://github.com/birdr-app/birdr/issues">abre un ticket en GitHub</a>.',
            'Pour signaler un bug ou demander une fonction, <a href="https://github.com/birdr-app/birdr/issues">ouvre un ticket sur GitHub</a>.',
            'Um einen Fehler zu melden oder eine Funktion zu wünschen, <a href="https://github.com/birdr-app/birdr/issues">eröffne ein Ticket auf GitHub</a>.',
            'Per segnalare un bug o chiedere una funzione, <a href="https://github.com/birdr-app/birdr/issues">apri un ticket su GitHub</a>.',
            'Para reportar um bug ou pedir um recurso, <a href="https://github.com/birdr-app/birdr/issues">abra um ticket no GitHub</a>.',
            '不具合の報告や機能の要望は <a href="https://github.com/birdr-app/birdr/issues">GitHubでチケットを送ってください</a>。',
        ),
    ),
    (
        'Birdr is a small project. Honest feedback, spotting the wrong bird, writing comparison descriptions for lookalike species, and telling other birders all help.',
        (
            'Birdr is een klein project. Eerlijke feedback, de verkeerde vogel herkennen, vergelijkingen schrijven voor lookalikes, en het doorvertellen aan andere vogelaars: alles helpt.',
            'Birdr es un proyecto pequeño. Comentarios honestos, detectar el ave equivocada, escribir comparaciones de especies parecidas y contárselo a otros observadores: todo ayuda.',
            'Birdr est un petit projet. Un avis honnête, repérer le mauvais oiseau, écrire des comparaisons pour les sosies, et en parler à d’autres ornithos : tout aide.',
            'Birdr ist ein kleines Projekt. Ehrliches Feedback, den falschen Vogel erkennen, Vergleiche für Doppelgänger schreiben und anderen Birding-Leuten davon erzählen: alles hilft.',
            'Birdr è un progetto piccolo. Feedback onesto, riconoscere l’uccello sbagliato, scrivere confronti per i sosia e dirlo ad altri birdwatcher: tutto aiuta.',
            'O Birdr é um projeto pequeno. Feedback honesto, achar a ave errada, escrever comparações de sósias e contar para outros observadores: tudo ajuda.',
            'Birdrは小さなプロジェクトです。率直なフィードバック、違う鳥の指摘、似た種の比較文、ほかのバーダーへの紹介、どれも助かります。',
        ),
    ),
    (
        'During a quiz, tap <strong>Flag</strong> if the photo, video or sound is not the species shown—or is otherwise unusable. That skips the clip in your game and reports it so we can take it out of the set.',
        (
            'Tijdens een quiz tik je op <strong>Flag</strong> als de foto, video of het geluid niet de getoonde soort is—of anderszins onbruikbaar. Dan sla je het fragment over en wordt het gemeld, zodat we het uit de set kunnen halen.',
            'Durante un quiz, toca <strong>Flag</strong> si la foto, el vídeo o el sonido no es la especie mostrada, o no sirve. Eso salta el clip en tu partida y lo avisa para que lo saquemos del conjunto.',
            'Pendant un quiz, appuie sur <strong>Flag</strong> si la photo, la vidéo ou le son n’est pas l’espèce affichée—ou est inutilisable. Ça saute le clip dans ta partie et le signale pour qu’on le retire du jeu.',
            'Während eines Quiz tippe auf <strong>Flag</strong>, wenn Foto, Video oder Ton nicht die gezeigte Art ist—oder sonst unbrauchbar. Dann wird der Clip in deinem Spiel übersprungen und gemeldet, damit wir ihn aus dem Satz nehmen.',
            'Durante un quiz, tocca <strong>Flag</strong> se la foto, il video o il suono non è la specie mostrata—o è inutilizzabile. Così il clip si salta nella partita e viene segnalato, perché lo togliamo dal set.',
            'Durante um quiz, toque em <strong>Flag</strong> se a foto, o vídeo ou o som não for a espécie mostrada—ou estiver inutilizável. Isso pula o clipe no seu jogo e avisa para retirarmos do conjunto.',
            'クイズ中、写真・動画・音声が示された種でない、または使えないときは <strong>Flag</strong> をタップ。そのクリップはゲームからスキップされ、セットから外せるよう報告されます。',
        ),
    ),
    (
        'A large part of the picture library is still waiting for review. If you know a country’s birds, open <a href="#review-photos">Review photos</a> below and approve or reject images a few at a time.',
        (
            'Een groot deel van de fotobibliotheek wacht nog op beoordeling. Ken je de vogels van een land, open dan hieronder <a href="#review-photos">Foto’s beoordelen</a> en keur beelden een paar tegelijk goed of af.',
            'Gran parte de la fototeca sigue esperando revisión. Si conoces las aves de un país, abre <a href="#review-photos">Revisar fotos</a> abajo y aprueba o rechaza imágenes de pocas en pocas.',
            'Une grande partie de la photothèque attend encore une relecture. Si tu connais les oiseaux d’un pays, ouvre <a href="#review-photos">Relire les photos</a> ci-dessous et approuve ou refuse les images par petites séries.',
            'Ein großer Teil der Bildbibliothek wartet noch auf Prüfung. Kennst du die Vögel eines Landes, öffne unten <a href="#review-photos">Fotos prüfen</a> und nimm Bilder in kleinen Mengen an oder ab.',
            'Gran parte della fototeca è ancora in attesa di revisione. Se conosci gli uccelli di un paese, apri sotto <a href="#review-photos">Rivedi le foto</a> e approva o rifiuta le immagini un po’ alla volta.',
            'Boa parte da fototeca ainda espera revisão. Se você conhece as aves de um país, abra <a href="#review-photos">Revisar fotos</a> abaixo e aprove ou rejeite imagens aos poucos.',
            '写真ライブラリの多くがまだ確認待ちです。その国の鳥を知っているなら、下の<a href="#review-photos">写真を確認</a>を開き、少しずつ承認または却下してください。',
        ),
    ),
    (
        'Comparison pages still rely on AI text until someone who knows the birds writes a better one. Open a lookalike pair from <a href="{href}">Species</a>, then use <strong>Write a better description</strong>.',
        (
            'Vergelijkingspagina’s steunen nog op AI-tekst tot iemand die de vogels kent iets beters schrijft. Open een lookalike-paar via <a href="{href}">Soorten</a> en gebruik <strong>Schrijf een betere beschrijving</strong>.',
            'Las páginas de comparación siguen con texto de IA hasta que alguien que conoce las aves escriba una mejor. Abre un par de sosias desde <a href="{href}">Especies</a> y usa <strong>Escribe una descripción mejor</strong>.',
            'Les pages de comparaison s’appuient encore sur du texte IA jusqu’à ce que quelqu’un qui connaît les oiseaux en écrive une meilleure. Ouvre une paire de sosies depuis <a href="{href}">Espèces</a>, puis <strong>Écrire une meilleure description</strong>.',
            'Vergleichsseiten stützen sich noch auf KI-Text, bis jemand, der die Vögel kennt, etwas Besseres schreibt. Öffne ein Doppelgänger-Paar unter <a href="{href}">Arten</a> und nutze <strong>Eine bessere Beschreibung schreiben</strong>.',
            'Le pagine di confronto si basano ancora su testo IA finché qualcuno che conosce gli uccelli non ne scrive una migliore. Apri una coppia di sosia da <a href="{href}">Specie</a>, poi <strong>Scrivi una descrizione migliore</strong>.',
            'As páginas de comparação ainda usam texto de IA até alguém que conhece as aves escrever uma melhor. Abra um par de sósias em <a href="{href}">Espécies</a> e use <strong>Escreva uma descrição melhor</strong>.',
            '比較ページは、その鳥を知る人がより良い文を書くまでAI文です。<a href="{href}">種</a>から似たペアを開き、<strong>より良い説明を書く</strong>を使ってください。',
        ),
    ),
    (
        'Quizzes are only as good as the pictures, and many still have not been checked. Help by approving good photos and rejecting the wrong bird—start with any country, or the birds you know best.',
        (
            'Quizzen zijn zo goed als de foto’s, en veel zijn nog niet nagekeken. Help door goede foto’s goed te keuren en de verkeerde vogel af te wijzen—begin bij elk land, of de vogels die je het best kent.',
            'Los quizzes valen lo que valen las fotos, y muchas aún no se han revisado. Ayuda aprobando buenas fotos y rechazando el ave equivocada: empieza por cualquier país, o las aves que mejor conoces.',
            'Les quiz ne valent que par les photos, et beaucoup n’ont pas encore été relues. Aide en approuvant les bonnes photos et en refusant le mauvais oiseau—commence par n’importe quel pays, ou les oiseaux que tu connais le mieux.',
            'Quiz sind nur so gut wie die Bilder, und viele sind noch ungeprüft. Hilf, indem du gute Fotos annimmst und den falschen Vogel ablehnst—starte mit jedem Land oder den Vögeln, die du am besten kennst.',
            'I quiz valgono quanto le foto, e molte non sono ancora state controllate. Aiuta approvando le foto buone e rifiutando l’uccello sbagliato: inizia da qualsiasi paese, o dagli uccelli che conosci meglio.',
            'Os quizzes valem pelas fotos, e muitas ainda não foram conferidas. Ajude aprovando fotos boas e rejeitando a ave errada—comece por qualquer país, ou as aves que você mais conhece.',
            'クイズの質は写真次第で、多くが未確認です。良い写真を承認し、違う鳥を却下して手伝ってください。どの国からでも、いちばんよく知る鳥からでも。',
        ),
    ),
    (
        'Species pages link to lookalikes that people mix up. If you know those birds, you can replace the AI text with a description that actually helps others tell them apart. You need to be signed in.',
        (
            'Soortpagina’s linken naar lookalikes die mensen door elkaar halen. Ken je die vogels, dan kun je de AI-tekst vervangen door een beschrijving die anderen écht helpt ze uit elkaar te houden. Je moet ingelogd zijn.',
            'Las páginas de especies enlazan a sosias que la gente mezcla. Si conoces esas aves, puedes sustituir el texto de IA por una descripción que de verdad ayude a distinguirlas. Tienes que iniciar sesión.',
            'Les pages d’espèces lient vers des sosies que les gens mélangent. Si tu connais ces oiseaux, tu peux remplacer le texte IA par une description qui aide vraiment à les distinguer. Il faut être connecté.',
            'Artseiten verlinken Doppelgänger, die Leute verwechseln. Kennst du diese Vögel, kannst du den KI-Text durch eine Beschreibung ersetzen, die anderen wirklich beim Unterscheiden hilft. Du musst angemeldet sein.',
            'Le pagine delle specie collegano i sosia che la gente confonde. Se conosci quegli uccelli, puoi sostituire il testo IA con una descrizione che aiuta davvero a distinguerli. Devi essere connesso.',
            'As páginas de espécies ligam sósias que as pessoas misturam. Se você conhece essas aves, pode trocar o texto de IA por uma descrição que realmente ajude a distingui-las. É preciso estar logado.',
            '種ページは、人が取り違える似た種へリンクします。その鳥を知っているなら、AI文を本当に見分けに役立つ説明に差し替えられます。ログインが必要です。',
        ),
    ),
    (
        'Birdr grows when birders tell other birders. Mention it in a club newsletter, a WhatsApp group, or after a field trip. Clubs can also start a <a href="{href}">Flock</a> and play the same quiz.',
        (
            'Birdr groeit als vogelaars het aan andere vogelaars vertellen. Noem het in een clubnieuwsbrief, een WhatsApp-groep, of na een excursie. Clubs kunnen ook een <a href="{href}">Flock</a> starten en dezelfde quiz spelen.',
            'Birdr crece cuando los observadores se lo cuentan a otros. Menciónalo en el boletín del club, un grupo de WhatsApp o después de una salida. Los clubs también pueden crear un <a href="{href}">Flock</a> y jugar el mismo quiz.',
            'Birdr grandit quand les ornithos en parlent à d’autres. Mentionne-le dans un bulletin de club, un groupe WhatsApp, ou après une sortie. Les clubs peuvent aussi créer un <a href="{href}">Flock</a> et jouer au même quiz.',
            'Birdr wächst, wenn Birding-Leute es weitererzählen. Erwähne es im Club-Newsletter, in einer WhatsApp-Gruppe oder nach einer Exkursion. Clubs können auch einen <a href="{href}">Flock</a> starten und dasselbe Quiz spielen.',
            'Birdr cresce quando i birdwatcher lo dicono ad altri. Menzionalo nel notiziario del club, in un gruppo WhatsApp o dopo un’uscita. I club possono anche creare un <a href="{href}">Flock</a> e giocare lo stesso quiz.',
            'O Birdr cresce quando observadores contam para outros. Mencione no boletim do clube, num grupo de WhatsApp ou depois de uma saída. Clubes também podem criar um <a href="{href}">Flock</a> e jogar o mesmo quiz.',
            'Birdrは、バーダーがほかのバーダーに伝えると広がります。会報、WhatsApp、探鳥のあとで紹介を。クラブは<a href="{href}">Flock</a>を作って同じクイズもできます。',
        ),
    ),
    (
        'A short note in a club email or magazine reaches people who already care about identification. You are welcome to reuse the item below, including the screenshots. Change the wording if it fits your club better.',
        (
            'Een kort stukje in een clubmail of blad bereikt mensen die al om herkenning geven. Je mag het bericht hieronder hergebruiken, inclusief de screenshots. Pas de tekst aan als dat beter bij je club past.',
            'Una nota breve en un correo o revista de club llega a quien ya le importa la identificación. Puedes reutilizar el texto de abajo, incluidas las capturas. Cambia el tono si encaja mejor con tu club.',
            'Une courte note dans un e-mail ou un magazine de club touche des gens qui tiennent déjà à l’identification. Tu peux réutiliser le texte ci-dessous, captures comprises. Adapte le libellé si ça va mieux à ton club.',
            'Ein kurzer Hinweis in einer Club-Mail oder Zeitschrift erreicht Leute, denen Bestimmung schon wichtig ist. Den Text unten darfst du wiederverwenden, inklusive Screenshots. Formuliere um, wenn es besser zu deinem Club passt.',
            'Una nota breve in una mail o rivista di club raggiunge chi ha già a cuore l’identificazione. Puoi riusare il testo sotto, screenshot compresi. Cambia le parole se sta meglio al tuo club.',
            'Uma nota curta num e-mail ou revista de clube chega a quem já se importa com identificação. Você pode reutilizar o texto abaixo, inclusive as capturas. Mude o texto se encaixar melhor no seu clube.',
            '会報メールや雑誌の短い紹介は、すでに識別に関心がある人に届きます。下の文とスクリーンショットはそのまま使って構いません。クラブに合わせて文言を変えてください。',
        ),
    ),
    (
        'Free on <a href="{app}">iPhone and Android</a>, or play in the browser at <a href="https://birdr.pro/play">birdr.pro/play</a>.',
        (
            'Gratis op <a href="{app}">iPhone en Android</a>, of speel in de browser op <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            'Gratis en <a href="{app}">iPhone y Android</a>, o juega en el navegador en <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            'Gratuit sur <a href="{app}">iPhone et Android</a>, ou joue dans le navigateur sur <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            'Kostenlos auf <a href="{app}">iPhone und Android</a>, oder im Browser unter <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            'Gratis su <a href="{app}">iPhone e Android</a>, o gioca nel browser su <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            'Grátis no <a href="{app}">iPhone e Android</a>, ou jogue no navegador em <a href="https://birdr.pro/play">birdr.pro/play</a>.',
            '<a href="{app}">iPhoneとAndroid</a>で無料。ブラウザなら <a href="https://birdr.pro/play">birdr.pro/play</a>。',
        ),
    ),
    (
        'Use Copy to put this example on the clipboard, including the screenshots. Images stay on birdr.pro, so they show when you paste into email or Word. If your club starts a Flock, include the invite so members can join in one tap.',
        (
            'Gebruik Kopieer om dit voorbeeld op het klembord te zetten, inclusief de screenshots. De afbeeldingen blijven op birdr.pro, zodat ze zichtbaar zijn als je in e-mail of Word plakt. Start je club een Flock, zet de uitnodiging erbij zodat leden in één tik kunnen meedoen.',
            'Usa Copiar para poner este ejemplo en el portapapeles, incluidas las capturas. Las imágenes siguen en birdr.pro, así que se ven al pegar en el correo o Word. Si tu club crea un Flock, incluye la invitación para que se unan en un toque.',
            'Utilise Copier pour mettre cet exemple dans le presse-papiers, captures comprises. Les images restent sur birdr.pro, donc elles s’affichent si tu colles dans un mail ou Word. Si ton club crée un Flock, joins l’invitation pour que les membres rejoignent en un tap.',
            'Mit Kopieren landet dieses Beispiel in der Zwischenablage, inklusive Screenshots. Die Bilder bleiben auf birdr.pro, also erscheinen sie beim Einfügen in E-Mail oder Word. Startet euer Club einen Flock, hängt die Einladung an, damit Mitglieder mit einem Tipp beitreten.',
            'Usa Copia per mettere questo esempio negli appunti, screenshot compresi. Le immagini restano su birdr.pro, così si vedono se incolli in email o Word. Se il club crea un Flock, includi l’invito perché i membri si uniscano con un tocco.',
            'Use Copiar para colocar este exemplo na área de transferência, incluindo as capturas. As imagens ficam no birdr.pro, então aparecem ao colar no e-mail ou no Word. Se o clube criar um Flock, inclua o convite para os membros entrarem com um toque.',
            '「コピー」でこの例をクリップボードへ。画面も含みます。画像は birdr.pro 上のままなので、メールや Word に貼ると表示されます。クラブが Flock を始めるなら招待も添え、ワンタップで参加できるように。',
        ),
    ),
    (
        'If you want to get sharper at identification between outings, try <a href="https://birdr.pro/">Birdr</a>. It is a free quiz app: you see a real photograph (or hear a recording), choose the species, and learn from the ones you miss. Study the birds of your own country, or switch to another list to prepare for a trip abroad.',
        (
            'Wil je tussen excursies door scherper worden in herkenning, probeer dan <a href="https://birdr.pro/">Birdr</a>. Het is een gratis quizapp: je ziet een echte foto (of hoort een opname), kiest de soort, en leert van wat je mist. Oefen de vogels van je eigen land, of wissel van lijst om je voor te bereiden op een reis naar het buitenland.',
            'Si quieres afilar la identificación entre salidas, prueba <a href="https://birdr.pro/">Birdr</a>. Es una app de quiz gratis: ves una foto real (o oyes una grabación), eliges la especie y aprendes de las que fallas. Estudia las aves de tu propio país, o cambia de lista para preparar un viaje al extranjero.',
            'Si tu veux t’affûter en identification entre les sorties, essaie <a href="https://birdr.pro/">Birdr</a>. C’est une app de quiz gratuite : tu vois une vraie photo (ou tu entends un enregistrement), tu choisis l’espèce, et tu apprends de celles que tu rates. Étudie les oiseaux de ton propre pays, ou change de liste pour préparer un voyage à l’étranger.',
            'Wenn du zwischen Exkursionen schärfer bestimmen willst, probiere <a href="https://birdr.pro/">Birdr</a>. Es ist eine kostenlose Quiz-App: Du siehst ein echtes Foto (oder hörst eine Aufnahme), wählst die Art und lernst aus dem, was du verfehlst. Übe die Vögel deines eigenen Landes, oder wechsle die Liste, um dich auf eine Reise ins Ausland vorzubereiten.',
            'Se vuoi affinare l’identificazione tra un’uscita e l’altra, prova <a href="https://birdr.pro/">Birdr</a>. È un’app di quiz gratis: vedi una foto vera (o senti una registrazione), scegli la specie e impari da quelle che sbagli. Studia gli uccelli del tuo paese, o cambia lista per prepararti a un viaggio all’estero.',
            'Se quiser afiar a identificação entre as saídas, experimente o <a href="https://birdr.pro/">Birdr</a>. É um app de quiz grátis: você vê uma foto de verdade (ou ouve uma gravação), escolhe a espécie e aprende com as que erra. Estude as aves do seu próprio país, ou mude de lista para se preparar para uma viagem ao exterior.',
            '探鳥の合間に識別を磨きたいなら <a href="https://birdr.pro/">Birdr</a> を。無料のクイズアプリです。本物の写真（または録音）を見て種を選び、間違えたものから学びます。自国の鳥を学ぶことも、旅の前に別のリストに切り替えることもできます。',
        ),
    ),
    (
        'It is not an auto-ID camera. The point is to learn the field marks yourself. Playing is easy and intuitive: pick a country, choose a level, and start. The game is available in multiple languages, including the bird names.',
        (
            'Het is geen auto-ID-camera. Het punt is dat je zelf de kenmerken leert. Spelen is makkelijk en intuïtief: kies een land, kies een level, en start. Het spel is in meerdere talen beschikbaar, ook de vogelnamen.',
            'No es una cámara de auto-ID. El punto es aprender tú las marcas de campo. Jugar es fácil e intuitivo: elige un país, elige un nivel, y empieza. El juego está disponible en varios idiomas, incluidos los nombres de las aves.',
            'Ce n’est pas une caméra d’auto-ID. Le but est d’apprendre toi-même les critères. Jouer est simple et intuitif : choisis un pays, un niveau, et c’est parti. Le jeu est disponible en plusieurs langues, y compris les noms d’oiseaux.',
            'Es ist keine Auto-ID-Kamera. Der Punkt ist, die Feldmerkmale selbst zu lernen. Spielen ist einfach und intuitiv: Land wählen, Level wählen, und los. Das Spiel gibt es in mehreren Sprachen, auch die Vogelnamen.',
            'Non è una fotocamera auto-ID. Il punto è imparare tu i caratteri. Giocare è facile e intuitivo: scegli un paese, un livello, e parti. Il gioco è disponibile in più lingue, compresi i nomi degli uccelli.',
            'Não é uma câmera de auto-ID. O ponto é aprender você mesmo as marcas de campo. Jogar é fácil e intuitivo: escolha um país, um nível, e comece. O jogo está disponível em vários idiomas, inclusive os nomes das aves.',
            '自動識別カメラではありません。特徴を自分で覚えるのが趣旨です。遊び方はかんたん：国を選び、レベルを選んでスタート。ゲームは複数の言語に対応し、鳥の名前も選べます。',
        ),
    ),
    (
        'After each answer you can open the bird and look at more photographs, videos and sounds. When you finish the game, you can go back through every question.',
        (
            'Na elk antwoord kun je de vogel openen en meer foto’s, video’s en geluiden bekijken. Als het spel af is, kun je alle vragen nog eens nalopen.',
            'Después de cada respuesta puedes abrir el ave y ver más fotos, vídeos y sonidos. Cuando terminas la partida, puedes repasarla pregunta a pregunta.',
            'Après chaque réponse tu peux ouvrir l’oiseau et voir plus de photos, de vidéos et de sons. Quand la partie est finie, tu peux revoir toutes les questions.',
            'Nach jeder Antwort kannst du den Vogel öffnen und mehr Fotos, Videos und Töne ansehen. Wenn das Spiel vorbei ist, kannst du alle Fragen noch einmal durchgehen.',
            'Dopo ogni risposta puoi aprire l’uccello e vedere altre foto, video e suoni. A partita finita, puoi ripassare tutte le domande.',
            'Depois de cada resposta você pode abrir a ave e ver mais fotos, vídeos e sons. Quando o jogo termina, você pode rever todas as perguntas.',
            '各回答のあと、その鳥を開いて写真・動画・鳴き声をさらに見られます。ゲームが終わったら、全問を振り返ることもできます。',
        ),
    ),
    (
        'Wrong answers are not wasted. My Tricky Birds keeps the lookalikes you mix up, pipits, treecreepers, black-backed gulls, and lets you practise that pair until it sticks. When a pair is fixed, you see it.',
        (
            'Foute antwoorden zijn niet weggegooid. Mijn lastige vogels onthoudt de lookalikes die je door elkaar haalt, piepers, boomkruipers, mantelmeeuwen, en laat je dat paar oefenen tot het blijft hangen. Als een paar is opgelost, zie je dat.',
            'Las respuestas incorrectas no se tiran. Mis aves difíciles guarda los sosias que mezclas, bisbitas, agateadores, gaviones, y te deja practicar ese par hasta que se quede. Cuando un par está resuelto, lo ves.',
            'Les mauvaises réponses ne sont pas perdues. Mes oiseaux difficiles retient les sosies que tu mélanges, pipits, grimpereaux, goélands marins, et te laisse pratiquer cette paire jusqu’à ce que ça rentre. Quand une paire est réglée, tu le vois.',
            'Falsche Antworten sind nicht verloren. Meine schwierigen Vögel merkt sich die Doppelgänger, die du verwechselst, Pieper, Baumläufer, Mantelmöwen, und lässt dich das Paar üben, bis es sitzt. Wenn ein Paar fest ist, siehst du es.',
            'Le risposte sbagliate non sono sprecate. I miei uccelli difficili tiene i sosia che confondi, pispoli, rampichini, zafferani, e ti fa esercitare quella coppia finché resta. Quando una coppia è sistemata, lo vedi.',
            'Respostas erradas não se perdem. Minhas aves difíceis guarda os sósias que você mistura, petinhas, trepadeiras, gaivotões, e deixa você praticar aquele par até grudar. Quando um par está resolvido, você vê.',
            '間違いは無駄になりません。「苦手な鳥」が取り違えた似た種（タヒバリ、キバシリ、オオカモメ類など）を残し、定着するまでそのペアを練習できます。定着すると表示されます。',
        ),
    ),
    (
        'Clubs can start a Flock: Every week the same 25-question quiz for the group, with a private leaderboard. Members have the entire week to play the game.',
        (
            'Clubs kunnen een Flock starten: elke week dezelfde quiz van 25 vragen voor de groep, met een privéklassement. Leden hebben de hele week om het spel te spelen.',
            'Los clubs pueden crear un Flock: cada semana el mismo quiz de 25 preguntas para el grupo, con una clasificación privada. Los miembros tienen toda la semana para jugar.',
            'Les clubs peuvent créer un Flock : chaque semaine le même quiz de 25 questions pour le groupe, avec un classement privé. Les membres ont toute la semaine pour jouer.',
            'Clubs können einen Flock starten: jede Woche dasselbe 25-Fragen-Quiz für die Gruppe, mit privater Rangliste. Mitglieder haben die ganze Woche Zeit zu spielen.',
            'I club possono creare un Flock: ogni settimana lo stesso quiz da 25 domande per il gruppo, con classifica privata. I membri hanno tutta la settimana per giocare.',
            'Clubes podem criar um Flock: toda semana o mesmo quiz de 25 perguntas para o grupo, com ranking privado. Os membros têm a semana inteira para jogar.',
            'クラブは Flock を始められます。毎週グループ同じ25問、非公開ランキング付き。メンバーは週を通してプレイできます。',
        ),
    ),
    (
        'A Country Challenge takes you through levels on one country’s list. It starts easy, but it ends tough, nobody has made it to the end yet.',
        (
            'Een landenuitdaging neemt je mee door levels op één landenlijst. Het begint makkelijk, maar het eindigt lastig, nog niemand heeft het tot het einde gehaald.',
            'Un reto por país te lleva por niveles en la lista de un país. Empieza fácil, pero acaba duro, nadie ha llegado al final todavía.',
            'Un défi pays te fait passer des niveaux sur la liste d’un pays. Ça commence facile, mais ça finit dur, personne n’est encore allé au bout.',
            'Eine Länder-Challenge führt dich durch Level auf einer Länderliste. Es fängt leicht an, wird aber hart, noch niemand hat es bis zum Ende geschafft.',
            'Una sfida per paese ti porta attraverso livelli sulla lista di un paese. Inizia facile, ma finisce tosta, nessuno è ancora arrivato in fondo.',
            'Um desafio por país te leva por níveis na lista de um país. Começa fácil, mas termina difícil, ninguém chegou ao fim ainda.',
            '国別チャレンジは一国のリストをレベルごとに進めます。最初は易しく、終わりは厳しい。まだ誰も最後まで到達していません。',
        ),
    ),
    (
        'Birdr is free on iPhone, Android and at <a href="https://birdr.pro/">https://birdr.pro</a>. Sign up if you want to keep your progress.',
        (
            'Birdr is gratis op iPhone, Android en op <a href="https://birdr.pro/">https://birdr.pro</a>. Maak een account als je je voortgang wilt bewaren.',
            'Birdr es gratis en iPhone, Android y en <a href="https://birdr.pro/">https://birdr.pro</a>. Regístrate si quieres guardar el progreso.',
            'Birdr est gratuit sur iPhone, Android et sur <a href="https://birdr.pro/">https://birdr.pro</a>. Inscris-toi si tu veux garder ta progression.',
            'Birdr ist kostenlos auf iPhone, Android und unter <a href="https://birdr.pro/">https://birdr.pro</a>. Registriere dich, wenn du deinen Fortschritt behalten willst.',
            'Birdr è gratis su iPhone, Android e su <a href="https://birdr.pro/">https://birdr.pro</a>. Registrati se vuoi tenere i progressi.',
            'O Birdr é grátis no iPhone, Android e em <a href="https://birdr.pro/">https://birdr.pro</a>. Cadastre-se se quiser guardar o progresso.',
            'BirdrはiPhone、Android、および <a href="https://birdr.pro/">https://birdr.pro</a> で無料。進捗を残すなら登録を。',
        ),
    ),
    (
        'App Store: <a href="{apple}">{apple}</a>.',
        (
            'App Store: <a href="{apple}">{apple}</a>.',
            'App Store: <a href="{apple}">{apple}</a>.',
            'App Store : <a href="{apple}">{apple}</a>.',
            'App Store: <a href="{apple}">{apple}</a>.',
            'App Store: <a href="{apple}">{apple}</a>.',
            'App Store: <a href="{apple}">{apple}</a>.',
            'App Store: <a href="{apple}">{apple}</a>.',
        ),
    ),
    (
        'Google Play: <a href="{play}">{play}</a>.',
        (
            'Google Play: <a href="{play}">{play}</a>.',
            'Google Play: <a href="{play}">{play}</a>.',
            'Google Play : <a href="{play}">{play}</a>.',
            'Google Play: <a href="{play}">{play}</a>.',
            'Google Play: <a href="{play}">{play}</a>.',
            'Google Play: <a href="{play}">{play}</a>.',
            'Google Play: <a href="{play}">{play}</a>.',
        ),
    ),
    (
        'New game: pick a country, a language for species names, and a difficulty',
        (
            'Nieuw spel: kies een land, een taal voor soortnamen, en een moeilijkheid',
            'Nueva partida: elige un país, un idioma para los nombres de especies, y una dificultad',
            'Nouvelle partie : choisis un pays, une langue pour les noms d’espèces, et une difficulté',
            'Neues Spiel: Land, Sprache für Artnamen und Schwierigkeit wählen',
            'Nuova partita: scegli un paese, una lingua per i nomi delle specie, e una difficoltà',
            'Novo jogo: escolha um país, um idioma para os nomes das espécies, e uma dificuldade',
            '新しいゲーム：国、種名の言語、難易度を選ぶ',
        ),
    ),
    (
        'Species page: Gull-billed Tern with photos, videos and sounds to review after an answer',
        (
            'Soortpagina: lachstern met foto’s, video’s en geluiden om na een antwoord te bekijken',
            'Página de especie: pagaza piconegra con fotos, vídeos y sonidos para revisar después de una respuesta',
            'Page d’espèce : sterne hansel avec photos, vidéos et sons à revoir après une réponse',
            'Artseite: Lachseeschwalbe mit Fotos, Videos und Tönen zum Nachschauen nach einer Antwort',
            'Pagina della specie: sterna zampenere con foto, video e suoni da rivedere dopo una risposta',
            'Página da espécie: trinta-réis-de-bico-preto com fotos, vídeos e sons para rever depois de uma resposta',
            '種ページ：ハシブトアジサシの写真・動画・鳴き声。回答後に見られる',
        ),
    ),
    (
        'Birdr home: start a quiz, take a country challenge, or start a Flock for your club',
        (
            'Birdr-home: start een quiz, doe een landenuitdaging, of start een Flock voor je club',
            'Inicio de Birdr: empieza un quiz, un reto por país, o un Flock para tu club',
            'Accueil Birdr : lancer un quiz, un défi pays, ou un Flock pour ton club',
            'Birdr-Start: Quiz starten, Länder-Challenge oder Flock für den Club',
            'Home di Birdr: inizia un quiz, una sfida per paese, o un Flock per il club',
            'Início do Birdr: comece um quiz, um desafio por país, ou um Flock para o clube',
            'Birdrホーム：クイズ、国別チャレンジ、クラブのFlockを始める',
        ),
    ),
    (
        'Birdr photo quiz: a gull on water and six species to choose from',
        (
            'Birdr-fotoquiz: een meeuw op het water en zes soorten om uit te kiezen',
            'Quiz de fotos de Birdr: una gaviota en el agua y seis especies entre las que elegir',
            'Quiz photo Birdr : une mouette sur l’eau et six espèces au choix',
            'Birdr-Foto-Quiz: eine Möwe auf dem Wasser und sechs Arten zur Auswahl',
            'Quiz fotografico Birdr: un gabbiano sull’acqua e sei specie tra cui scegliere',
            'Quiz de fotos do Birdr: uma gaivota na água e seis espécies para escolher',
            'Birdr写真クイズ：水面のカモメと、選べる6種',
        ),
    ),
    (
        'Lookalike quiz: Redhead versus Common Pochard, with illustrations and eBird links',
        (
            'Lookalike-quiz: Amerikaanse tafeleend versus tafeleend, met tekeningen en eBird-links',
            'Quiz de sosias: porrón americano frente a porrón europeo, con ilustraciones y enlaces de eBird',
            'Quiz de sosies : fuligule à tête rouge contre fuligule milouin, avec illustrations et liens eBird',
            'Doppelgänger-Quiz: Riesentafelente gegen Tafelente, mit Zeichnungen und eBird-Links',
            'Quiz di sosia: moretta americana contro moriglione, con illustrazioni e link eBird',
            'Quiz de sósias: zarro-americano versus zarro-comum, com ilustrações e links do eBird',
            '似た種クイズ：アメリカホシハジロ対ホシハジロ、図とeBirdリンク付き',
        ),
    ),
    (
        'My Tricky Birds: a list of confusing pairs for the Netherlands, with Practice buttons and FIXED badges',
        (
            'Mijn lastige vogels: een lijst verwarrende paren voor Nederland, met Oefen-knoppen en FIXED-badges',
            'Mis aves difíciles: una lista de pares confusos para Países Bajos, con botones Practicar y distintivos FIXED',
            'Mes oiseaux difficiles : une liste de paires trompeuses pour les Pays-Bas, avec boutons Pratiquer et badges FIXED',
            'Meine schwierigen Vögel: eine Liste verwirrender Paare für die Niederlande, mit Üben-Buttons und FIXED-Badges',
            'I miei uccelli difficili: una lista di coppie ingannevoli per i Paesi Bassi, con pulsanti Pratica e badge FIXED',
            'Minhas aves difíceis: uma lista de pares confusos para os Países Baixos, com botões Praticar e selos FIXED',
            '苦手な鳥：オランダの紛らわしいペア一覧。練習ボタンとFIXEDバッジ付き',
        ),
    ),
    (
        'Pair practice: Eurasian Treecreeper versus Short-toed Treecreeper, with the correct species marked',
        (
            'Paaroefening: boomkruiper versus kortteenboomkruiper, met de juiste soort gemarkeerd',
            'Práctica de par: agateador euroasiático frente a agateador común, con la especie correcta marcada',
            'Pratique en paire : grimpereau des jardins contre grimpereau des bois, avec la bonne espèce marquée',
            'Paar-Übung: Waldbaumläufer gegen Gartenbaumläufer, mit der richtigen Art markiert',
            'Pratica a coppia: rampichino comune contro rampichino alpestre, con la specie corretta evidenziata',
            'Prática em par: trepadeira-comum versus trepadeira-do-bosque, com a espécie certa marcada',
            'ペア練習：キバシリ対コキバシリ、正解の種がマークされた画面',
        ),
    ),
    (
        'Pair practice results: 18 of 20 correct, and the two treecreepers no longer seem confusing',
        (
            'Resultaat paaroefening: 18 van 20 goed, en de twee boomkruipers lijken niet meer verwarrend',
            'Resultados de práctica de par: 18 de 20 correctas, y los dos agateadores ya no parecen confusos',
            'Résultats de pratique en paire : 18 sur 20 justes, et les deux grimpereaux ne semblent plus trompeurs',
            'Ergebnis der Paar-Übung: 18 von 20 richtig, und die beiden Baumläufer wirken nicht mehr verwirrend',
            'Risultati della pratica a coppia: 18 su 20 corretti, e i due rampichini non sembrano più confusi',
            'Resultados da prática em par: 18 de 20 certos, e as duas trepadeiras já não parecem confusas',
            'ペア練習の結果：20問中18問正解。2種のキバシリがもう紛らわしくない',
        ),
    ),
    (
        'Country challenge: United States Eastern, question 2 of 10, identify a Yellow-rumped Warbler',
        (
            'Landenuitdaging: Verenigde Staten Oost, vraag 2 van 10, herken een Myrtle Warbler',
            'Reto por país: este de Estados Unidos, pregunta 2 de 10, identifica un chipe rabadilla amarilla',
            'Défi pays : est des États-Unis, question 2 sur 10, identifier une paruline à croupion jaune',
            'Länder-Challenge: Osten der USA, Frage 2 von 10, einen Gelbsteiß-Waldsänger bestimmen',
            'Sfida per paese: Stati Uniti orientali, domanda 2 di 10, identifica una parula fianchi-gialli',
            'Desafio por país: leste dos Estados Unidos, pergunta 2 de 10, identifique uma mariquita-de-rabadilha-amarela',
            '国別チャレンジ：アメリカ東部、10問中2問目、キヅタアメリカムシクイを識別',
        ),
    ),
]
