"""Marketing copy translations. Keys are English source strings."""

from __future__ import annotations

_LOCALES = ('nl', 'es', 'fr', 'de', 'it', 'pt-BR', 'ja')

# Each entry: English msgid, then translations in _LOCALES order.
_ENTRIES: list[tuple[str, tuple[str, ...]]] = [
    ('How it works', ('Hoe het werkt', 'Cómo funciona', 'Comment ça marche', 'So funktioniert’s', 'Come funziona', 'Como funciona', '使い方')),
    ('Species', ('Soorten', 'Especies', 'Espèces', 'Arten', 'Specie', 'Espécies', '種')),
    ('Countries', ('Landen', 'Países', 'Pays', 'Länder', 'Paesi', 'Países', '国')),
    ('Community', ('Community', 'Comunidad', 'Communauté', 'Community', 'Community', 'Comunidade', 'コミュニティ')),
    ('Log in', ('Inloggen', 'Iniciar sesión', 'Connexion', 'Anmelden', 'Accedi', 'Entrar', 'ログイン')),
    ('My Games', ('Mijn spellen', 'Mis partidas', 'Mes parties', 'Meine Spiele', 'Le mie partite', 'Meus jogos', 'マイゲーム')),
    ('My Checklist', ('Mijn checklist', 'Mi lista', 'Ma liste', 'Meine Checkliste', 'La mia lista', 'Minha lista', 'マイチェックリスト')),
    ('My tricky birds', ('Mijn lastige vogels', 'Mis aves difíciles', 'Mes oiseaux difficiles', 'Meine schwierigen Vögel', 'I miei uccelli difficili', 'Minhas aves difíceis', '苦手な鳥')),
    ('Settings', ('Instellingen', 'Ajustes', 'Réglages', 'Einstellungen', 'Impostazioni', 'Configurações', '設定')),
    ('Admin', ('Beheer', 'Admin', 'Admin', 'Admin', 'Admin', 'Admin', '管理')),
    ('My edits', ('Mijn bewerkingen', 'Mis ediciones', 'Mes contributions', 'Meine Beiträge', 'Le mie modifiche', 'Minhas edições', 'マイ編集')),
    ('Logout', ('Uitloggen', 'Cerrar sesión', 'Déconnexion', 'Abmelden', 'Esci', 'Sair', 'ログアウト')),
    ('Language', ('Taal', 'Idioma', 'Langue', 'Sprache', 'Lingua', 'Idioma', '言語')),
    ('Get the app', ('Download de app', 'Descargar la app', 'Télécharger l’app', 'App holen', 'Scarica l’app', 'Baixar o app', 'アプリを入手')),
    ('Primary', ('Hoofdnavigatie', 'Principal', 'Principal', 'Hauptnavigation', 'Principale', 'Principal', 'メイン')),
    ('Breadcrumb', ('Kruimelpad', 'Migas', 'Fil d’Ariane', 'Brotkrumen', 'Percorso', 'Navegação', 'パンくず')),
    ('Learn', ('Leren', 'Aprender', 'Apprendre', 'Lernen', 'Impara', 'Aprender', '学ぶ')),
    ('Play in the browser', ('Speel in de browser', 'Jugar en el navegador', 'Jouer dans le navigateur', 'Im Browser spielen', 'Gioca nel browser', 'Jogar no navegador', 'ブラウザでプレイ')),
    ('Play a quiz', ('Speel een quiz', 'Jugar un quiz', 'Faire un quiz', 'Quiz spielen', 'Fai un quiz', 'Jogar um quiz', 'クイズをプレイ')),
    ('Learn bird identification', ('Leer vogels herkennen', 'Aprende a identificar aves', 'Apprendre à identifier les oiseaux', 'Vögel bestimmen lernen', 'Impara a identificare gli uccelli', 'Aprenda a identificar aves', '鳥の識別を学ぶ')),
    ('My Tricky Birds', ('Mijn lastige vogels', 'Mis aves difíciles', 'Mes oiseaux difficiles', 'Meine schwierigen Vögel', 'I miei uccelli difficili', 'Minhas aves difíceis', '苦手な鳥')),
    ('Quizzes by country', ('Quizzen per land', 'Quizzes por país', 'Quiz par pays', 'Quiz nach Land', 'Quiz per paese', 'Quizzes por país', '国別クイズ')),
    ('The app', ('De app', 'La app', 'L’app', 'Die App', 'L’app', 'O app', 'アプリ')),
    ('Flocks', ('Flocks', 'Flocks', 'Flocks', 'Flocks', 'Flocks', 'Flocks', 'Flocks')),
    ('FAQ', ('FAQ', 'FAQ', 'FAQ', 'FAQ', 'FAQ', 'FAQ', 'FAQ')),
    ('All pages', ('Alle pagina’s', 'Todas las páginas', 'Toutes les pages', 'Alle Seiten', 'Tutte le pagine', 'Todas as páginas', 'すべてのページ')),
    ('Contact', ('Contact', 'Contacto', 'Contact', 'Kontakt', 'Contatti', 'Contato', 'お問い合わせ')),
    ('Facebook group', ('Facebookgroep', 'Grupo de Facebook', 'Groupe Facebook', 'Facebook-Gruppe', 'Gruppo Facebook', 'Grupo do Facebook', 'Facebookグループ')),
    ('GitHub issues', ('GitHub-issues', 'Incidencias de GitHub', 'Tickets GitHub', 'GitHub-Issues', 'Issue GitHub', 'Issues no GitHub', 'GitHubのissue')),
    ('Join the Facebook group', ('Word lid van de Facebookgroep', 'Únete al grupo de Facebook', 'Rejoindre le groupe Facebook', 'Der Facebook-Gruppe beitreten', 'Unisciti al gruppo Facebook', 'Entre no grupo do Facebook', 'Facebookグループに参加')),
    ('Submit a ticket', ('Ticket indienen', 'Enviar un ticket', 'Ouvrir un ticket', 'Ticket einreichen', 'Apri un ticket', 'Abrir um ticket', 'チケットを送る')),
    ('Home', ('Home', 'Inicio', 'Accueil', 'Start', 'Home', 'Início', 'ホーム')),
    ('Account', ('Account', 'Cuenta', 'Compte', 'Konto', 'Account', 'Conta', 'アカウント')),
    ('Download on the App Store', ('Download in de App Store', 'Descargar en App Store', 'Télécharger dans l’App Store', 'Laden im App Store', 'Scarica su App Store', 'Baixar na App Store', 'App Storeからダウンロード')),
    ('Get it on Google Play', ('Ontdek het op Google Play', 'Disponible en Google Play', 'Disponible sur Google Play', 'Jetzt bei Google Play', 'Disponibile su Google Play', 'Disponível no Google Play', 'Google Playで手に入れよう')),
    (
        'Improve your birding skills. Free on iPhone, Android and the web.',
        (
            'Verbeter je vogelkennis. Gratis op iPhone, Android en het web.',
            'Mejora tus habilidades de observación de aves. Gratis en iPhone, Android y la web.',
            'Améliore tes compétences d’ornitho. Gratuit sur iPhone, Android et le web.',
            'Verbessere deine Vogelkenntnisse. Kostenlos auf iPhone, Android und im Web.',
            'Migliora le tue abilità da birdwatcher. Gratis su iPhone, Android e sul web.',
            'Melhore suas habilidades de observação de aves. Grátis no iPhone, Android e na web.',
            'バードウォッチングの腕を上げよう。iPhone、Android、ウェブで無料。',
        ),
    ),
    ('Improve your birding skills.', ('Verbeter je vogelkennis.', 'Mejora tus habilidades de observación de aves.', 'Améliore tes compétences d’ornitho.', 'Verbessere deine Vogelkenntnisse.', 'Migliora le tue abilità da birdwatcher.', 'Melhore suas habilidades de observação de aves.', 'バードウォッチングの腕を上げよう。')),
    (
        'Free photo quizzes, personalised practice and country challenges for birders worldwide.',
        (
            'Gratis fotoquizzen, persoonlijke oefening en landenuitdagingen voor vogelaars wereldwijd.',
            'Quizzes de fotos gratis, práctica personalizada y retos por país para observadores de todo el mundo.',
            'Quiz photo gratuits, entraînement personnalisé et défis pays pour les ornithos du monde entier.',
            'Kostenlose Foto-Quiz, persönliches Training und Länder-Challenges für Birding weltweit.',
            'Quiz fotografici gratis, pratica personalizzata e sfide per paese per birdwatcher di tutto il mondo.',
            'Quizzes de fotos grátis, prática personalizada e desafios por país para observadores do mundo todo.',
            '無料の写真クイズ、あなた向けの練習、国別チャレンジを世界中のバーダーに。',
        ),
    ),
    (
        'Birdr – Free Bird Identification Quiz & Training App',
        (
            'Birdr – Gratis quiz en training-app voor vogelherkenning',
            'Birdr – App gratis de quiz y entrenamiento de identificación de aves',
            'Birdr – App gratuite de quiz et d’entraînement à l’identification',
            'Birdr – Kostenlose Quiz- und Trainings-App zur Vogelbestimmung',
            'Birdr – App gratis di quiz e allenamento per identificare gli uccelli',
            'Birdr – App grátis de quiz e treino de identificação de aves',
            'Birdr – 無料の鳥類識別クイズ＆トレーニングアプリ',
        ),
    ),
    (
        'Learn to identify birds through photo quizzes, country challenges and personalised training. Birdr is free on iPhone, Android and the web.',
        (
            'Leer vogels herkennen met fotoquizzen, landenuitdagingen en persoonlijke training. Birdr is gratis op iPhone, Android en het web.',
            'Aprende a identificar aves con quizzes de fotos, retos por país y entrenamiento personalizado. Birdr es gratis en iPhone, Android y la web.',
            'Apprends à identifier les oiseaux avec des quiz photo, des défis pays et un entraînement personnalisé. Birdr est gratuit sur iPhone, Android et le web.',
            'Lerne Vögel bestimmen mit Foto-Quiz, Länder-Challenges und persönlichem Training. Birdr ist kostenlos auf iPhone, Android und im Web.',
            'Impara a identificare gli uccelli con quiz fotografici, sfide per paese e allenamento personalizzato. Birdr è gratis su iPhone, Android e sul web.',
            'Aprenda a identificar aves com quizzes de fotos, desafios por país e treino personalizado. O Birdr é grátis no iPhone, Android e na web.',
            '写真クイズ、国別チャレンジ、あなた向けの練習で鳥を見分けよう。BirdrはiPhone、Android、ウェブで無料。',
        ),
    ),
    ('Free bird identification training', ('Gratis training in vogelherkenning', 'Entrenamiento gratis de identificación', 'Entraînement gratuit à l’identification', 'Kostenloses Bestimmungstraining', 'Allenamento gratis all’identificazione', 'Treino grátis de identificação', '無料の鳥類識別トレーニング')),
    ('Or play a quiz in the browser', ('Of speel een quiz in de browser', 'O juega un quiz en el navegador', 'Ou fais un quiz dans le navigateur', 'Oder spiel ein Quiz im Browser', 'O fai un quiz nel browser', 'Ou jogue um quiz no navegador', 'またはブラウザでクイズ')),
    ('How Birdr teaches', ('Hoe Birdr lesgeeft', 'Cómo enseña Birdr', 'Comment Birdr enseigne', 'So lehrt Birdr', 'Come insegna Birdr', 'Como o Birdr ensina', 'Birdrの学び方')),
    ('Play a quiz', ('Speel een quiz', 'Jugar un quiz', 'Faire un quiz', 'Quiz spielen', 'Fai un quiz', 'Jogar um quiz', 'クイズをプレイ')),
    ('Answer 10, 20, 50 or 100 questions.', ('Beantwoord 10, 20, 50 of 100 vragen.', 'Responde 10, 20, 50 o 100 preguntas.', 'Réponds à 10, 20, 50 ou 100 questions.', 'Beantworte 10, 20, 50 oder 100 Fragen.', 'Rispondi a 10, 20, 50 o 100 domande.', 'Responda 10, 20, 50 ou 100 perguntas.', '10、20、50、100問から選べます。')),
    ('Review your answers', ('Bekijk je antwoorden', 'Revisa tus respuestas', 'Revois tes réponses', 'Antworten prüfen', 'Rivedi le risposte', 'Revise suas respostas', '答えを確認')),
    ('At the end of the game you can review all your answers.', ('Aan het eind van het spel kun je al je antwoorden nalopen.', 'Al final de la partida puedes revisar todas tus respuestas.', 'À la fin de la partie tu peux revoir toutes tes réponses.', 'Am Ende kannst du alle Antworten nachschauen.', 'Alla fine della partita puoi rivedere tutte le risposte.', 'No fim do jogo você pode revisar todas as respostas.', 'ゲームの終わりに、すべての答えを確認できます。')),
    ('Learn what you missed', ('Leer van je missers', 'Aprende de lo que fallaste', 'Apprends de tes erreurs', 'Lerne aus Fehlern', 'Impara dagli errori', 'Aprenda com os erros', '間違えたところを学ぶ')),
    (
        'Wrong answers become practice. <i>My Tricky Birds</i> keeps the lookalikes that will not stick.',
        (
            'Foute antwoorden worden oefening. <i>Mijn lastige vogels</i> onthoudt de lookalikes die niet blijven hangen.',
            'Las respuestas incorrectas se convierten en práctica. <i>Mis aves difíciles</i> guarda los parecidos que no se te quedan.',
            'Les mauvaises réponses deviennent de l’entraînement. <i>Mes oiseaux difficiles</i> retient les sosies qui ne rentrent pas.',
            'Falsche Antworten werden zum Training. <i>Meine schwierigen Vögel</i> merkt sich die Verwechslungsarten.',
            'Le risposte sbagliate diventano pratica. <i>I miei uccelli difficili</i> tiene i sosia che non restano.',
            'Respostas erradas viram prática. <i>Minhas aves difíceis</i> guarda os parecidos que não grudam.',
            '間違いは練習になります。<i>苦手な鳥</i> が、覚えにくい似た種を残します。',
        ),
    ),
    ('See how it works', ('Bekijk hoe het werkt', 'Mira cómo funciona', 'Voir comment ça marche', 'So funktioniert’s', 'Scopri come funziona', 'Veja como funciona', '使い方を見る')),
    ('What you can play', ('Wat je kunt spelen', 'Qué puedes jugar', 'Ce que tu peux jouer', 'Was du spielen kannst', 'Cosa puoi giocare', 'O que você pode jogar', 'プレイできること')),
    ('Photo quizzes', ('Fotoquizzen', 'Quizzes de fotos', 'Quiz photo', 'Foto-Quiz', 'Quiz fotografici', 'Quizzes de fotos', '写真クイズ')),
    ('One quick game, or a longer session. Choose a country, a level and photos, video or sound.', ('Een korte ronde of een langere sessie. Kies een land, een level en foto’s, video of geluid.', 'Una partida rápida o una sesión más larga. Elige país, nivel y fotos, vídeo o sonido.', 'Une partie rapide ou une session plus longue. Choisis un pays, un niveau et photos, vidéo ou son.', 'Ein kurzes Spiel oder eine längere Runde. Land, Level und Fotos, Video oder Ton wählen.', 'Una partita rapida o una sessione più lunga. Scegli paese, livello e foto, video o suoni.', 'Um jogo rápido ou uma sessão mais longa. Escolha país, nível e fotos, vídeo ou som.', '短いゲームでも、長めのセッションでも。国、レベル、写真・動画・音声を選べます。')),
    ('Start a quiz', ('Start een quiz', 'Empezar un quiz', 'Lancer un quiz', 'Quiz starten', 'Inizia un quiz', 'Começar um quiz', 'クイズを始める')),
    ('Sound quizzes', ('Geluidquizzen', 'Quizzes de sonido', 'Quiz sonores', 'Ton-Quiz', 'Quiz di canti', 'Quizzes de som', '鳴き声クイズ')),
    ('Hear a recording and pick the species. You can also play passerine sound quizzes in the browser.', ('Luister naar een opname en kies de soort. Je kunt zangvogel-geluidquizzen ook in de browser spelen.', 'Escucha una grabación y elige la especie. También puedes jugar quizzes de sonido de paseriformes en el navegador.', 'Écoute un enregistrement et choisis l’espèce. Tu peux aussi jouer des quiz sonores de passereaux dans le navigateur.', 'Hör dir eine Aufnahme an und wähle die Art. Sperlingsvogel-Ton-Quiz geht auch im Browser.', 'Ascolta una registrazione e scegli la specie. Puoi anche giocare quiz di canti dei passeriformi nel browser.', 'Ouça uma gravação e escolha a espécie. Você também pode jogar quizzes de som de passeriformes no navegador.', '録音を聞いて種を選びます。スズメ目の鳴き声クイズはブラウザでもできます。')),
    ('Play a sound quiz', ('Speel een geluidquiz', 'Jugar un quiz de sonido', 'Jouer un quiz sonore', 'Ton-Quiz spielen', 'Gioca un quiz di canti', 'Jogar um quiz de som', '鳴き声クイズをプレイ')),
    ('Multiplayer', ('Multiplayer', 'Multijugador', 'Multijoueur', 'Mehrspieler', 'Multigiocatore', 'Multijogador', 'マルチプレイヤー')),
    ('A live quiz for two or more players. Faster correct answers score more points.', ('Een live quiz voor twee of meer spelers. Snellere goede antwoorden leveren meer punten op.', 'Un quiz en vivo para dos o más jugadores. Las respuestas correctas más rápidas dan más puntos.', 'Un quiz en direct pour deux joueurs ou plus. Les bonnes réponses plus rapides rapportent plus de points.', 'Ein Live-Quiz für zwei oder mehr Spieler. Schnellere richtige Antworten bringen mehr Punkte.', 'Un quiz dal vivo per due o più giocatori. Le risposte corrette più veloci valgono di più.', 'Um quiz ao vivo para dois ou mais jogadores. Acertos mais rápidos valem mais pontos.', '2人以上のライブクイズ。正解が早いほど高得点。')),
    ('Start a live quiz', ('Start een live quiz', 'Empezar un quiz en vivo', 'Lancer un quiz en direct', 'Live-Quiz starten', 'Inizia un quiz dal vivo', 'Começar um quiz ao vivo', 'ライブクイズを始める')),
    ('High scores', ('High scores', 'Mejores puntuaciones', 'Meilleurs scores', 'Highscores', 'Punteggi più alti', 'Recordes', 'ハイスコア')),
    ('See how you rank after a quiz.', ('Zie hoe je scoort na een quiz.', 'Mira tu puesto después de un quiz.', 'Vois ton classement après un quiz.', 'Sieh, wo du nach einem Quiz stehst.', 'Scopri la tua posizione dopo un quiz.', 'Veja sua posição depois de um quiz.', 'クイズ後の順位を見る。')),
    ('View high scores', ('Bekijk high scores', 'Ver puntuaciones', 'Voir les scores', 'Highscores anzeigen', 'Vedi i punteggi', 'Ver recordes', 'ハイスコアを見る')),
    ('My checklist', ('Mijn checklist', 'Mi lista', 'Ma liste', 'Meine Checkliste', 'La mia lista', 'Minha lista', 'マイチェックリスト')),
    ('See which birds you named correctly in your country, and which ones you missed.', ('Zie welke vogels je in jouw land goed had, en welke je miste.', 'Mira qué aves identificaste bien en tu país y cuáles fallaste.', 'Vois quels oiseaux tu as bien nommés dans ton pays, et lesquels tu as ratés.', 'Sieh, welche Vögel du in deinem Land richtig hattest – und welche nicht.', 'Vedi quali uccelli hai riconosciuto nel tuo paese e quali hai sbagliato.', 'Veja quais aves você acertou no seu país e quais errou.', '自分の国で正しく言えた鳥と、逃した鳥がわかります。')),
    ('Open my checklist', ('Open mijn checklist', 'Abrir mi lista', 'Ouvrir ma liste', 'Checkliste öffnen', 'Apri la mia lista', 'Abrir minha lista', 'チェックリストを開く')),
    ('Country Challenges', ('Landenuitdagingen', 'Retos por país', 'Défis pays', 'Länder-Challenges', 'Sfide per paese', 'Desafios por país', '国別チャレンジ')),
    ('Structured levels for the birds of a country—from the Netherlands to Japan to Colombia.', ('Gestructureerde levels voor de vogels van een land—van Nederland tot Japan tot Colombia.', 'Niveles estructurados para las aves de un país, de los Países Bajos a Japón y Colombia.', 'Des niveaux structurés pour les oiseaux d’un pays—des Pays-Bas au Japon en Colombie.', 'Strukturierte Level für die Vögel eines Landes – von den Niederlanden über Japan bis Kolumbien.', 'Livelli strutturati per gli uccelli di un paese—dai Paesi Bassi al Giappone alla Colombia.', 'Níveis estruturados para as aves de um país—dos Países Baixos ao Japão e à Colômbia.', 'その国の鳥を段階的に。オランダから日本、コロンビアまで。')),
    ('Study a country list', ('Bestudeer een landenlijst', 'Estudia la lista de un país', 'Étudier une liste de pays', 'Eine Länderliste lernen', 'Studia la lista di un paese', 'Estude a lista de um país', '国のリストを学ぶ')),
    ('All country quizzes', ('Alle landenquizzen', 'Todos los quizzes por país', 'Tous les quiz par pays', 'Alle Länder-Quiz', 'Tutti i quiz per paese', 'Todos os quizzes por país', 'すべての国別クイズ')),
    ('What birders say', ('Wat vogelaars zeggen', 'Lo que dicen los observadores', 'Ce qu’en disent les ornithos', 'Was Birding-Leute sagen', 'Cosa dicono i birdwatcher', 'O que dizem os observadores', 'バーダーの声')),
    ('Community and FAQ', ('Community en FAQ', 'Comunidad y FAQ', 'Communauté et FAQ', 'Community und FAQ', 'Community e FAQ', 'Comunidade e FAQ', 'コミュニティとFAQ')),
    ('Birdr is a small project. Send feedback or review photos if you know a country’s birds.', ('Birdr is een klein project. Stuur feedback of beoordeel foto’s als je de vogels van een land kent.', 'Birdr es un proyecto pequeño. Envía comentarios o revisa fotos si conoces las aves de un país.', 'Birdr est un petit projet. Envoie un avis ou relis des photos si tu connais les oiseaux d’un pays.', 'Birdr ist ein kleines Projekt. Schick Feedback oder prüfe Fotos, wenn du die Vögel eines Landes kennst.', 'Birdr è un progetto piccolo. Invia feedback o rivedi le foto se conosci gli uccelli di un paese.', 'O Birdr é um projeto pequeno. Envie feedback ou revise fotos se você conhece as aves de um país.', 'Birdrは小さなプロジェクトです。その国の鳥を知っているなら、フィードバックや写真の確認をお願いします。')),
    ('How you can help', ('Hoe je kunt helpen', 'Cómo puedes ayudar', 'Comment aider', 'Wie du helfen kannst', 'Come puoi aiutare', 'Como você pode ajudar', '協力のしかた')),
    ('Is Birdr free? Does it identify birds from a photo? Where can I play?', ('Is Birdr gratis? Herkent het vogels van een foto? Waar kan ik spelen?', '¿Birdr es gratis? ¿Identifica aves a partir de una foto? ¿Dónde puedo jugar?', 'Birdr est-il gratuit ? Identifie-t-il les oiseaux à partir d’une photo ? Où jouer ?', 'Ist Birdr kostenlos? Bestimmt es Vögel anhand eines Fotos? Wo kann ich spielen?', 'Birdr è gratis? Identifica gli uccelli da una foto? Dove posso giocare?', 'O Birdr é grátis? Ele identifica aves a partir de uma foto? Onde posso jogar?', 'Birdrは無料？写真から鳥を識別する？どこで遊べる？')),
    ('Read the FAQ', ('Lees de FAQ', 'Leer las FAQ', 'Lire la FAQ', 'FAQ lesen', 'Leggi le FAQ', 'Ler as FAQ', 'FAQを読む')),
    ('Get Birdr on your phone', ('Zet Birdr op je telefoon', 'Lleva Birdr al móvil', 'Installe Birdr sur ton téléphone', 'Birdr aufs Handy', 'Birdr sul telefono', 'Coloque o Birdr no celular', 'スマホでBirdr')),
    ('The apps are the best way to practise. The browser works too if you want to try a quiz first.', ('De apps zijn de beste manier om te oefenen. De browser kan ook, als je eerst een quiz wilt proberen.', 'Las apps son la mejor forma de practicar. El navegador también sirve si quieres probar un quiz primero.', 'Les apps sont le meilleur endroit pour s’entraîner. Le navigateur marche aussi si tu veux d’abord essayer un quiz.', 'Die Apps sind der beste Ort zum Üben. Der Browser geht auch, wenn du zuerst ein Quiz ausprobieren willst.', 'Le app sono il modo migliore per esercitarsi. Il browser va bene se vuoi prima provare un quiz.', 'Os apps são o melhor jeito de praticar. O navegador também funciona se você quiser testar um quiz primeiro.', '練習するならアプリがおすすめ。まずはクイズを試したいならブラウザでも。')),
    ('Continue in the browser', ('Ga verder in de browser', 'Seguir en el navegador', 'Continuer dans le navigateur', 'Im Browser weiter', 'Continua nel browser', 'Continuar no navegador', 'ブラウザで続ける')),
    ('vs', ('vs', 'vs', 'vs', 'vs', 'vs', 'vs', '対')),
    ('Register', ('Registreren', 'Registrarse', 'Créer un compte', 'Registrieren', 'Registrati', 'Cadastrar', '登録')),
    ('Forgot password?', ('Wachtwoord vergeten?', '¿Olvidaste la contraseña?', 'Mot de passe oublié ?', 'Passwort vergessen?', 'Password dimenticata?', 'Esqueceu a senha?', 'パスワードをお忘れですか？')),
    ('Forgot password', ('Wachtwoord vergeten', 'Olvidé la contraseña', 'Mot de passe oublié', 'Passwort vergessen', 'Password dimenticata', 'Esqueci a senha', 'パスワードを忘れた')),
    ("Don't have an account?", ('Nog geen account?', '¿No tienes cuenta?', 'Pas encore de compte ?', 'Noch kein Konto?', 'Non hai un account?', 'Não tem uma conta?', 'アカウントをお持ちでない方')),
    ('Already have an account?', ('Al een account?', '¿Ya tienes cuenta?', 'Tu as déjà un compte ?', 'Schon ein Konto?', 'Hai già un account?', 'Já tem uma conta?', 'すでにアカウントをお持ちの方')),
    ('Close', ('Sluiten', 'Cerrar', 'Fermer', 'Schließen', 'Chiudi', 'Fechar', '閉じる')),
    ('Username', ('Gebruikersnaam', 'Usuario', 'Nom d’utilisateur', 'Benutzername', 'Nome utente', 'Nome de usuário', 'ユーザー名')),
    ('Email', ('E-mail', 'Correo', 'E-mail', 'E-Mail', 'Email', 'E-mail', 'メール')),
    ('Password', ('Wachtwoord', 'Contraseña', 'Mot de passe', 'Passwort', 'Password', 'Senha', 'パスワード')),
    ('Send reset link', ('Stuur resetlink', 'Enviar enlace', 'Envoyer le lien', 'Link senden', 'Invia il link', 'Enviar link', 'リセットリンクを送る')),
    ('Back to login', ('Terug naar inloggen', 'Volver al inicio de sesión', 'Retour à la connexion', 'Zurück zur Anmeldung', 'Torna al login', 'Voltar ao login', 'ログインに戻る')),
    ('Or continue with', ('Of ga verder met', 'O continúa con', 'Ou continuer avec', 'Oder weiter mit', 'O continua con', 'Ou continue com', 'または次で続ける')),
    ('Continue with Google', ('Doorgaan met Google', 'Continuar con Google', 'Continuer avec Google', 'Mit Google fortfahren', 'Continua con Google', 'Continuar com o Google', 'Googleで続ける')),
    ('Continue with Apple', ('Doorgaan met Apple', 'Continuar con Apple', 'Continuer avec Apple', 'Mit Apple fortfahren', 'Continua con Apple', 'Continuar com a Apple', 'Appleで続ける')),
    ('Password must be at least 8 characters.', ('Wachtwoord moet minstens 8 tekens zijn.', 'La contraseña debe tener al menos 8 caracteres.', 'Le mot de passe doit faire au moins 8 caractères.', 'Das Passwort muss mindestens 8 Zeichen haben.', 'La password deve avere almeno 8 caratteri.', 'A senha deve ter pelo menos 8 caracteres.', 'パスワードは8文字以上にしてください。')),
    ('Authentication failed. Please try again.', ('Aanmelden mislukt. Probeer het opnieuw.', 'Error de autenticación. Inténtalo de nuevo.', 'Échec de l’authentification. Réessaie.', 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.', 'Autenticazione non riuscita. Riprova.', 'Falha na autenticação. Tente de novo.', '認証に失敗しました。もう一度お試しください。')),
    ('Failed to send password reset email', ('Resetmail versturen mislukt', 'No se pudo enviar el correo de restablecimiento', 'Échec de l’envoi de l’e-mail de réinitialisation', 'Reset-E-Mail konnte nicht gesendet werden', 'Invio e-mail di reset non riuscito', 'Falha ao enviar o e-mail de redefinição', 'パスワード再設定メールを送れませんでした')),
    ('If an account with this email exists, a password reset link has been sent.', ('Als er een account met dit e-mailadres bestaat, is er een resetlink verstuurd.', 'Si existe una cuenta con este correo, se ha enviado un enlace para restablecer la contraseña.', 'Si un compte existe avec cet e-mail, un lien de réinitialisation a été envoyé.', 'Falls ein Konto mit dieser E-Mail existiert, wurde ein Reset-Link gesendet.', 'Se esiste un account con questa email, è stato inviato un link per reimpostare la password.', 'Se existir uma conta com este e-mail, um link de redefinição foi enviado.', 'このメールのアカウントがあれば、再設定リンクを送りました。')),
    ("Enter your email address and we'll send you a link to reset your password.", ('Vul je e-mailadres in, dan sturen we een link om je wachtwoord te resetten.', 'Introduce tu correo y te enviaremos un enlace para restablecer la contraseña.', 'Saisis ton e-mail et nous t’enverrons un lien pour réinitialiser ton mot de passe.', 'Gib deine E-Mail ein, dann schicken wir einen Link zum Zurücksetzen.', 'Inserisci la tua email e ti invieremo un link per reimpostare la password.', 'Informe seu e-mail e enviaremos um link para redefinir a senha.', 'メールアドレスを入力すると、パスワード再設定用のリンクを送ります。')),
    ('Is Birdr free?', ('Is Birdr gratis?', '¿Birdr es gratis?', 'Birdr est-il gratuit ?', 'Ist Birdr kostenlos?', 'Birdr è gratis?', 'O Birdr é grátis?', 'Birdrは無料ですか？')),
    (
        'Yes. Birdr is free on iPhone, Android and the web. Photo quizzes, country challenges and personalised practice do not require a paid subscription.',
        (
            'Ja. Birdr is gratis op iPhone, Android en het web. Fotoquizzen, landenuitdagingen en persoonlijke oefening vereisen geen betaald abonnement.',
            'Sí. Birdr es gratis en iPhone, Android y la web. Los quizzes de fotos, los retos por país y la práctica personalizada no requieren suscripción de pago.',
            'Oui. Birdr est gratuit sur iPhone, Android et le web. Quiz photo, défis pays et entraînement personnalisé ne demandent pas d’abonnement payant.',
            'Ja. Birdr ist kostenlos auf iPhone, Android und im Web. Foto-Quiz, Länder-Challenges und persönliches Training brauchen kein Abo.',
            'Sì. Birdr è gratis su iPhone, Android e sul web. Quiz fotografici, sfide per paese e pratica personalizzata non richiedono un abbonamento a pagamento.',
            'Sim. O Birdr é grátis no iPhone, Android e na web. Quizzes de fotos, desafios por país e prática personalizada não exigem assinatura paga.',
            'はい。BirdrはiPhone、Android、ウェブで無料です。写真クイズ、国別チャレンジ、あなた向けの練習に有料登録は不要です。',
        ),
    ),
    ('Does Birdr identify birds from a photo for me?', ('Herkent Birdr vogels voor mij van een foto?', '¿Birdr identifica aves a partir de una foto por mí?', 'Birdr identifie-t-il les oiseaux à partir d’une photo à ma place ?', 'Bestimmt Birdr Vögel anhand eines Fotos für mich?', 'Birdr identifica gli uccelli da una foto al posto mio?', 'O Birdr identifica aves a partir de uma foto por mim?', 'Birdrは写真から鳥を識別してくれますか？')),
    (
        'No. Birdr is a training app: you learn to identify birds yourself through quizzes and practice, rather than handing a photo to an automatic identifier.',
        (
            'Nee. Birdr is een trainingsapp: je leert zelf vogels herkennen met quizzen en oefening, in plaats van een foto aan een automatische herkenner te geven.',
            'No. Birdr es una app de entrenamiento: aprendes a identificar aves tú mismo con quizzes y práctica, en lugar de entregar una foto a un identificador automático.',
            'Non. Birdr est une app d’entraînement : tu apprends à identifier les oiseaux toi-même par des quiz et de la pratique, plutôt que de donner une photo à un identificateur automatique.',
            'Nein. Birdr ist eine Trainings-App: Du lernst, Vögel selbst zu bestimmen – mit Quiz und Übung, statt ein Foto an eine Auto-ID zu geben.',
            'No. Birdr è un’app di allenamento: impari a identificare gli uccelli da solo con quiz e pratica, invece di dare una foto a un identificatore automatico.',
            'Não. O Birdr é um app de treino: você aprende a identificar aves você mesmo com quizzes e prática, em vez de entregar uma foto a um identificador automático.',
            'いいえ。Birdrはトレーニングアプリです。自動識別に写真を渡すのではなく、クイズと練習で自分で見分けます。',
        ),
    ),
    ('Can I practise the birds of my country?', ('Kan ik de vogels van mijn land oefenen?', '¿Puedo practicar las aves de mi país?', 'Puis-je m’entraîner sur les oiseaux de mon pays ?', 'Kann ich die Vögel meines Landes üben?', 'Posso esercitarmi sugli uccelli del mio paese?', 'Posso praticar as aves do meu país?', '自分の国の鳥を練習できますか？')),
    (
        'Yes. Start a photo quiz for a country list, or take a Country Challenge with levels from easy to expert. Birdr covers birders worldwide, not only Europe.',
        (
            'Ja. Start een fotoquiz voor een landenlijst, of doe een landenuitdaging met levels van makkelijk tot expert. Birdr is voor vogelaars wereldwijd, niet alleen Europa.',
            'Sí. Empieza un quiz de fotos con la lista de un país, o un reto por país con niveles de fácil a experto. Birdr cubre observadores de todo el mundo, no solo Europa.',
            'Oui. Lance un quiz photo sur une liste de pays, ou un défi pays du facile à l’expert. Birdr s’adresse aux ornithos du monde entier, pas seulement en Europe.',
            'Ja. Starte ein Foto-Quiz für eine Länderliste oder eine Länder-Challenge von leicht bis Expert. Birdr ist für Birding weltweit, nicht nur Europa.',
            'Sì. Inizia un quiz fotografico su una lista di paese, o una sfida per paese dal facile all’esperto. Birdr è per birdwatcher di tutto il mondo, non solo in Europa.',
            'Sim. Comece um quiz de fotos com a lista de um país, ou um desafio por país do fácil ao expert. O Birdr é para observadores do mundo todo, não só da Europa.',
            'はい。国のリストで写真クイズを始めるか、易しい〜上級の国別チャレンジを。Birdrは欧州だけでなく世界中のバーダー向けです。',
        ),
    ),
    ('What is My Tricky Birds?', ('Wat is Mijn lastige vogels?', '¿Qué es Mis aves difíciles?', 'Qu’est-ce que Mes oiseaux difficiles ?', 'Was sind Meine schwierigen Vögel?', 'Cosa sono I miei uccelli difficili?', 'O que é Minhas aves difíceis?', '「苦手な鳥」とは？')),
    (
        'When you mix up species, Birdr remembers those trouble spots so you can practise the difficult birds and confusing pairs until they stick.',
        (
            'Als je soorten door elkaar haalt, onthoudt Birdr die lastige plekken, zodat je de moeilijke vogels en verwarrende paren kunt oefenen tot ze blijven hangen.',
            'Cuando confundes especies, Birdr recuerda esos puntos débiles para que practiques las aves difíciles y los pares confusos hasta que se queden.',
            'Quand tu mélanges des espèces, Birdr retient ces points faibles pour que tu t’entraînes sur les oiseaux difficiles et les paires trompeuses jusqu’à ce que ça rentre.',
            'Wenn du Arten verwechselst, merkt sich Birdr diese Schwachstellen, damit du schwierige Vögel und Paare üben kannst, bis sie sitzen.',
            'Quando confondi le specie, Birdr ricorda quei punti deboli così puoi esercitarti sugli uccelli difficili e le coppie ingannevoli finché restano.',
            'Quando você confunde espécies, o Birdr lembra esses pontos fracos para você praticar as aves difíceis e os pares confusos até grudar.',
            '種を取り違えると、Birdrがその苦手を覚えておき、難しい鳥や紛らわしいペアを定着するまで練習できます。',
        ),
    ),
    ('What are Flocks?', ('Wat zijn Flocks?', '¿Qué son los Flocks?', 'Que sont les Flocks ?', 'Was sind Flocks?', 'Cosa sono i Flocks?', 'O que são Flocks?', 'Flockとは？')),
    (
        'A Flock is a bird club or group on Birdr. Members play shared quizzes and see a leaderboard—useful for clubs, WhatsApp groups and trip companions.',
        (
            'Een Flock is een vogelclub of groep op Birdr. Leden spelen dezelfde quizzen en zien een klassement—handig voor clubs, WhatsApp-groepen en reisgenoten.',
            'Un Flock es un club o grupo de aves en Birdr. Los miembros juegan quizzes compartidos y ven una clasificación: útil para clubs, grupos de WhatsApp y compañeros de viaje.',
            'Un Flock est un club ou un groupe d’ornithos sur Birdr. Les membres jouent les mêmes quiz et voient un classement—pratique pour les clubs, groupes WhatsApp et compagnons de voyage.',
            'Ein Flock ist ein Vogelclub oder eine Gruppe auf Birdr. Mitglieder spielen gemeinsame Quiz und sehen eine Rangliste – praktisch für Clubs, WhatsApp-Gruppen und Reisegefährten.',
            'Un Flock è un club o un gruppo di birdwatching su Birdr. I membri giocano quiz condivisi e vedono una classifica—utile per club, gruppi WhatsApp e compagni di viaggio.',
            'Um Flock é um clube ou grupo de observação no Birdr. Os membros jogam quizzes em comum e veem um ranking—útil para clubes, grupos de WhatsApp e companheiros de viagem.',
            'FlockはBirdr上の探鳥クラブやグループです。メンバーが同じクイズをプレイし、ランキングを見られます。クラブ、WhatsApp、旅の仲間向け。',
        ),
    ),
    ('Where can I play?', ('Waar kan ik spelen?', '¿Dónde puedo jugar?', 'Où puis-je jouer ?', 'Wo kann ich spielen?', 'Dove posso giocare?', 'Onde posso jogar?', 'どこでプレイできますか？')),
    (
        'In the free iOS and Android apps, or in the browser at birdr.pro. Your progress stays with your account across devices.',
        (
            'In de gratis iOS- en Android-apps, of in de browser op birdr.pro. Je voortgang blijft bij je account, op al je apparaten.',
            'En las apps gratis de iOS y Android, o en el navegador en birdr.pro. Tu progreso se queda con tu cuenta en todos los dispositivos.',
            'Dans les apps iOS et Android gratuites, ou dans le navigateur sur birdr.pro. Ta progression reste liée à ton compte sur tous les appareils.',
            'In den kostenlosen iOS- und Android-Apps oder im Browser auf birdr.pro. Dein Fortschritt bleibt beim Konto, geräteübergreifend.',
            'Nelle app iOS e Android gratis, o nel browser su birdr.pro. I progressi restano sul tuo account su tutti i dispositivi.',
            'Nos apps grátis de iOS e Android, ou no navegador em birdr.pro. Seu progresso fica na conta, em todos os aparelhos.',
            '無料のiOS・Androidアプリ、または birdr.pro のブラウザで。進捗はアカウントに保存され、端末をまたいで残ります。',
        ),
    ),
    ('How Birdr Works – Quizzes, Practice & Country Challenges', ('Hoe Birdr werkt – quizzen, oefenen en landenuitdagingen', 'Cómo funciona Birdr – quizzes, práctica y retos por país', 'Comment Birdr fonctionne – quiz, pratique et défis pays', 'So funktioniert Birdr – Quiz, Übung und Länder-Challenges', 'Come funziona Birdr – quiz, pratica e sfide per paese', 'Como o Birdr funciona – quizzes, prática e desafios por país', 'Birdrの仕組み – クイズ、練習、国別チャレンジ')),
    ('How Birdr works', ('Hoe Birdr werkt', 'Cómo funciona Birdr', 'Comment Birdr fonctionne', 'So funktioniert Birdr', 'Come funziona Birdr', 'Como o Birdr funciona', 'Birdrの仕組み')),
    ('Try a quiz in the browser', ('Probeer een quiz in de browser', 'Prueba un quiz en el navegador', 'Essaye un quiz dans le navigateur', 'Quiz im Browser ausprobieren', 'Prova un quiz nel browser', 'Experimente um quiz no navegador', 'ブラウザでクイズを試す')),
    ('Beginner', ('Beginner', 'Principiante', 'Débutant', 'Anfänger', 'Principiante', 'Iniciante', '初級')),
    ('Novice', ('Beginner+', 'Novato', 'Novice', 'Fortgeschritten-Anfänger', 'Novizio', 'Novato', '初級+')),
    ('Advanced', ('Gevorderd', 'Avanzado', 'Avancé', 'Fortgeschritten', 'Avanzato', 'Avançado', '上級')),
    ('Pro', ('Pro', 'Pro', 'Pro', 'Pro', 'Pro', 'Pro', 'プロ')),
    ('Expert', ('Expert', 'Experto', 'Expert', 'Experte', 'Esperto', 'Expert', 'エキスパート')),
    ('Starting a quiz', ('Een quiz starten', 'Empezar un quiz', 'Commencer un quiz', 'Ein Quiz starten', 'Iniziare un quiz', 'Começar um quiz', 'クイズの始め方')),
    ('Levels', ('Levels', 'Niveles', 'Niveaux', 'Level', 'Livelli', 'Níveis', 'レベル')),
    ('Other settings', ('Overige instellingen', 'Otros ajustes', 'Autres réglages', 'Weitere Einstellungen', 'Altre impostazioni', 'Outras configurações', 'その他の設定')),
    ('Species language', ('Soortentaal', 'Idioma de las especies', 'Langue des espèces', 'Artensprache', 'Lingua delle specie', 'Idioma das espécies', '種名の言語')),
    ('Country', ('Land', 'País', 'Pays', 'Land', 'Paese', 'País', '国')),
    ('Number of questions', ('Aantal vragen', 'Número de preguntas', 'Nombre de questions', 'Anzahl Fragen', 'Numero di domande', 'Número de perguntas', '問題数')),
    ('Media', ('Media', 'Medios', 'Médias', 'Medien', 'Media', 'Mídia', 'メディア')),
    ('Taxonomic order / family', ('Taxonomische orde / familie', 'Orden / familia taxonómica', 'Ordre / famille taxonomique', 'Taxonomische Ordnung / Familie', 'Ordine / famiglia tassonomica', 'Ordem / família taxonômica', '目 / 科')),
    ('Best on the app', ('Het best in de app', 'Mejor en la app', 'Mieux dans l’app', 'Am besten in der App', 'Meglio nell’app', 'Melhor no app', 'アプリがおすすめ')),
    ('Install Birdr for quizzes on the go. Same account in the browser if you prefer.', ('Installeer Birdr voor quizzen onderweg. Hetzelfde account in de browser als je dat liever hebt.', 'Instala Birdr para quizzes sobre la marcha. La misma cuenta en el navegador si lo prefieres.', 'Installe Birdr pour des quiz en déplacement. Le même compte dans le navigateur si tu préfères.', 'Installiere Birdr für Quiz unterwegs. Dasselbe Konto im Browser, wenn du magst.', 'Installa Birdr per i quiz in movimento. Lo stesso account nel browser se preferisci.', 'Instale o Birdr para quizzes em qualquer lugar. A mesma conta no navegador se preferir.', '移動中のクイズにはBirdrをインストール。ブラウザでも同じアカウント。')),
    ('Find a bird', ('Zoek een vogel', 'Busca un ave', 'Trouver un oiseau', 'Einen Vogel finden', 'Trova un uccello', 'Encontre uma ave', '鳥を探す')),
    ('Practice', ('Oefenen', 'Practicar', 'S’entraîner', 'Üben', 'Allenati', 'Praticar', '練習')),
    ('Search', ('Zoeken', 'Buscar', 'Rechercher', 'Suchen', 'Cerca', 'Pesquisar', '検索')),
    ('Family', ('Familie', 'Familia', 'Famille', 'Familie', 'Famiglia', 'Família', '科')),
    ('Order', ('Orde', 'Orden', 'Ordre', 'Ordnung', 'Ordine', 'Ordem', '目')),
    ('All families', ('Alle families', 'Todas las familias', 'Toutes les familles', 'Alle Familien', 'Tutte le famiglie', 'Todas as famílias', 'すべての科')),
    ('How can I help?', ('Hoe kan ik helpen?', '¿Cómo puedo ayudar?', 'Comment aider ?', 'Wie kann ich helfen?', 'Come posso aiutare?', 'Como posso ajudar?', 'どう協力できる？')),
    ('Write a better description', ('Schrijf een betere beschrijving', 'Escribe una descripción mejor', 'Écrire une meilleure description', 'Eine bessere Beschreibung schreiben', 'Scrivi una descrizione migliore', 'Escreva uma descrição melhor', 'より良い説明を書く')),
    ('Send feedback', ('Stuur feedback', 'Enviar comentarios', 'Envoyer un avis', 'Feedback senden', 'Invia feedback', 'Enviar feedback', 'フィードバックを送る')),
    ('Review photos', ('Foto’s beoordelen', 'Revisar fotos', 'Relire les photos', 'Fotos prüfen', 'Rivedi le foto', 'Revisar fotos', '写真を確認')),
    ('Write comparisons', ('Schrijf vergelijkingen', 'Escribir comparaciones', 'Écrire des comparaisons', 'Vergleiche schreiben', 'Scrivi confronti', 'Escrever comparações', '比較を書く')),
    ('Find lookalikes', ('Zoek lookalikes', 'Buscar parecidos', 'Trouver les sosies', 'Ähnliche Arten finden', 'Trova i sosia', 'Encontrar parecidos', '似た種を探す')),
    ('Pages', ('Pagina’s', 'Páginas', 'Pages', 'Seiten', 'Pagine', 'Páginas', 'ページ')),
    ('Page not found', ('Pagina niet gevonden', 'Página no encontrada', 'Page introuvable', 'Seite nicht gefunden', 'Pagina non trovata', 'Página não encontrada', 'ページが見つかりません')),
    ('Birdr home', ('Birdr-home', 'Inicio de Birdr', 'Accueil Birdr', 'Birdr-Startseite', 'Home di Birdr', 'Início do Birdr', 'Birdrホーム')),
    ('In short', ('Kort gezegd', 'En breve', 'En bref', 'Kurz gesagt', 'In breve', 'Em resumo', '要点')),
    ('Identification tips', ('Herkenningstips', 'Consejos de identificación', 'Conseils d’identification', 'Bestimmungstipps', 'Consigli di identificazione', 'Dicas de identificação', '識別のコツ')),
    ('Size', ('Grootte', 'Tamaño', 'Taille', 'Größe', 'Taglia', 'Tamanho', '大きさ')),
    ('Plumage', ('Verenkleed', 'Plumaje', 'Plumage', 'Gefieder', 'Piumaggio', 'Plumagem', '羽色')),
    ('Behaviour', ('Gedrag', 'Comportamiento', 'Comportement', 'Verhalten', 'Comportamento', 'Comportamento', '行動')),
    ('Habitat', ('Habitat', 'Hábitat', 'Habitat', 'Lebensraum', 'Habitat', 'Habitat', '生息環境')),
    ('Voice', ('Geluid', 'Voz', 'Voix', 'Stimme', 'Voce', 'Voz', '声')),
    ('Write at least one section before publishing.', ('Schrijf minstens één onderdeel voordat je publiceert.', 'Escribe al menos una sección antes de publicar.', 'Écris au moins une section avant de publier.', 'Schreibe mindestens einen Abschnitt vor dem Veröffentlichen.', 'Scrivi almeno una sezione prima di pubblicare.', 'Escreva pelo menos uma seção antes de publicar.', '公開する前に、少なくとも1つの項目を書いてください。')),
    ('A community description is already published for this pair.', ('Er staat al een communitybeschrijving voor dit paar.', 'Ya hay una descripción de la comunidad para este par.', 'Une description communautaire est déjà publiée pour cette paire.', 'Für dieses Paar gibt es schon eine Community-Beschreibung.', 'È già pubblicata una descrizione della community per questa coppia.', 'Já há uma descrição da comunidade para este par.', 'このペアのコミュニティ説明はすでに公開されています。')),
    ('Country Challenge', ('Landenuitdaging', 'Reto por país', 'Défi pays', 'Länder-Challenge', 'Sfida per paese', 'Desafio do país', '国別チャレンジ')),
    ('Player', ('Speler', 'Jugador', 'Joueur', 'Spieler', 'Giocatore', 'Jogador', 'プレイヤー')),
    ('Level', ('Level', 'Nivel', 'Niveau', 'Level', 'Livello', 'Nível', 'レベル')),
    ('Score', ('Score', 'Puntuación', 'Score', 'Punkte', 'Punteggio', 'Pontuação', 'スコア')),
    ('Misses', ('Missers', 'Fallos', 'Erreurs', 'Fehler', 'Errori', 'Erros', 'ミス')),
    ('Mix-ups', ('Verwarringen', 'Confusiones', 'Confusions', 'Verwechslungen', 'Confusioni', 'Confusões', '取り違え')),
    ('Pair', ('Paar', 'Par', 'Paire', 'Paar', 'Coppia', 'Par', 'ペア')),
    ('Most missed species', ('Meest gemiste soorten', 'Especies más falladas', 'Espèces les plus ratées', 'Am häufigsten verfehlte Arten', 'Specie più sbagliate', 'Espécies mais erradas', 'いちばん間違えられる種')),
    ('Confusing pairs', ('Verwarrende paren', 'Pares confusos', 'Paires trompeuses', 'Verwirrende Paare', 'Coppie ingannevoli', 'Pares confusos', '紛らわしいペア')),
    ('How to tell them apart', ('Hoe je ze uit elkaar houdt', 'Cómo distinguirlas', 'Comment les distinguer', 'Wie man sie unterscheidet', 'Come distinguerli', 'Como distingui-las', '見分け方')),
    ('Type at least two letters to search.', ('Typ minstens twee letters om te zoeken.', 'Escribe al menos dos letras para buscar.', 'Tape au moins deux lettres pour chercher.', 'Tippe mindestens zwei Buchstaben zum Suchen.', 'Scrivi almeno due lettere per cercare.', 'Digite pelo menos duas letras para pesquisar.', '検索するには2文字以上入力してください。')),
    ('Pages – Birdr', ('Pagina’s – Birdr', 'Páginas – Birdr', 'Pages – Birdr', 'Seiten – Birdr', 'Pagine – Birdr', 'Páginas – Birdr', 'ページ – Birdr')),
    ('Page not found · Birdr', ('Pagina niet gevonden · Birdr', 'Página no encontrada · Birdr', 'Page introuvable · Birdr', 'Seite nicht gefunden · Birdr', 'Pagina non trovata · Birdr', 'Página não encontrada · Birdr', 'ページが見つかりません · Birdr')),
    ('This page is not available on Birdr.', ('Deze pagina bestaat niet op Birdr.', 'Esta página no está disponible en Birdr.', 'Cette page n’existe pas sur Birdr.', 'Diese Seite gibt es auf Birdr nicht.', 'Questa pagina non è disponibile su Birdr.', 'Esta página não está disponível no Birdr.', 'このページはBirdrにありません。')),
    ('That address is not a page on Birdr.', ('Dat adres is geen pagina op Birdr.', 'Esa dirección no es una página de Birdr.', 'Cette adresse n’est pas une page Birdr.', 'Diese Adresse ist keine Birdr-Seite.', 'Questo indirizzo non è una pagina di Birdr.', 'Esse endereço não é uma página do Birdr.', 'そのアドレスはBirdrのページではありません。')),
    ('optional', ('optioneel', 'opcional', 'facultatif', 'optional', 'facoltativo', 'opcional', '任意')),
    ('Name', ('Naam', 'Nombre', 'Nom', 'Name', 'Nome', 'Nome', '名前')),
    ('Message', ('Bericht', 'Mensaje', 'Message', 'Nachricht', 'Messaggio', 'Mensagem', 'メッセージ')),
    ('Your feedback…', ('Jouw feedback…', 'Tu comentario…', 'Ton avis…', 'Dein Feedback…', 'Il tuo feedback…', 'Seu feedback…', 'フィードバック…')),
    ('Website', ('Website', 'Sitio web', 'Site web', 'Website', 'Sito web', 'Site', 'ウェブサイト')),
    ('Cancel', ('Annuleren', 'Cancelar', 'Annuler', 'Abbrechen', 'Annulla', 'Cancelar', 'キャンセル')),
    ('Submit', ('Versturen', 'Enviar', 'Envoyer', 'Absenden', 'Invia', 'Enviar', '送信')),
    ('Images', ('Afbeeldingen', 'Imágenes', 'Images', 'Bilder', 'Immagini', 'Imagens', '画像')),
    ('Videos', ('Video’s', 'Vídeos', 'Vidéos', 'Videos', 'Video', 'Vídeos', '動画')),
    ('Sounds', ('Geluiden', 'Sonidos', 'Sons', 'Töne', 'Suoni', 'Sons', '音声')),
    ('Loading…', ('Laden…', 'Cargando…', 'Chargement…', 'Laden…', 'Caricamento…', 'Carregando…', '読み込み中…')),
    ('Reviewed', ('Beoordeeld', 'Revisado', 'Relu', 'Geprüft', 'Revisionato', 'Revisado', '確認済み')),
    ('Review needed', ('Beoordeling nodig', 'Revisión necesaria', 'Relecture nécessaire', 'Prüfung nötig', 'Revisione necessaria', 'Revisão necessária', '確認が必要')),
    ('Write', ('Schrijven', 'Escribir', 'Écrire', 'Schreiben', 'Scrivi', 'Escrever', '書く')),
    ('Edit this description', ('Bewerk deze beschrijving', 'Editar esta descripción', 'Modifier cette description', 'Beschreibung bearbeiten', 'Modifica questa descrizione', 'Editar esta descrição', 'この説明を編集')),
    ('Updated {date}', ('Bijgewerkt {date}', 'Actualizado {date}', 'Mis à jour {date}', 'Aktualisiert {date}', 'Aggiornato {date}', 'Atualizado {date}', '{date} 更新')),
    ('{left} vs {right}', ('{left} vs {right}', '{left} vs {right}', '{left} vs {right}', '{left} vs {right}', '{left} vs {right}', '{left} vs {right}', '{left} 対 {right}')),
    ('Bird Quiz: {name} – Identify the Birds | Birdr', ('Vogelquiz: {name} – Herken de vogels | Birdr', 'Quiz de aves: {name} – Identifica las aves | Birdr', 'Quiz oiseaux : {name} – Identifie les oiseaux | Birdr', 'Vogelquiz: {name} – Vögel bestimmen | Birdr', 'Quiz di uccelli: {name} – Identifica gli uccelli | Birdr', 'Quiz de aves: {name} – Identifique as aves | Birdr', '鳥クイズ: {name} – 鳥を見分けよう | Birdr')),
    ('Birds of {name}', ('Vogels van {name}', 'Aves de {name}', 'Oiseaux de {name}', 'Vögel von {name}', 'Uccelli di {name}', 'Aves de {name}', '{name}の鳥')),
    (
        'I gave Birdr a quick spin and immediately found it incredibly useful. Kudos to the developer!',
        (
            'Ik heb Birdr even uitgeprobeerd en vond het meteen enorm nuttig. Complimenten aan de maker!',
            'Probé Birdr un momento y al instante me pareció increíblemente útil. ¡Enhorabuena al desarrollador!',
            'J’ai jeté un œil à Birdr et je l’ai tout de suite trouvé extrêmement utile. Bravo au développeur !',
            'Ich habe Birdr kurz ausprobiert und sofort enorm nützlich gefunden. Kompliment an den Entwickler!',
            'Ho provato Birdr un attimo e l’ho trovato subito utilissimo. Complimenti allo sviluppatore!',
            'Dei uma olhada rápida no Birdr e achei imediatamente muito útil. Parabéns ao desenvolvedor!',
            'Birdrを少し試しただけで、とても役立つとわかりました。開発者に感謝！',
        ),
    ),
]

from jizz.marketing.catalogs_extra import EXTRA_ENTRIES
from jizz.marketing.catalogs_ui import UI_ENTRIES

CATALOGS: dict[str, dict[str, str]] = {code: {} for code in _LOCALES}
for msgid, translations in (*_ENTRIES, *EXTRA_ENTRIES, *UI_ENTRIES):
    if len(translations) != len(_LOCALES):
        raise ValueError(f'Bad translation count for {msgid!r}')
    for code, text in zip(_LOCALES, translations):
        CATALOGS[code][msgid] = text
