# Generated by Django 4.2.3 on 2025-11-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jizz', '0072_add_user_profile_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_type', models.CharField(choices=[('species', 'Species vs Species'), ('family', 'Family vs Family'), ('order', 'Order vs Order'), ('species_family', 'Species vs Family'), ('species_order', 'Species vs Order')], max_length=50)),
                ('family_1', models.CharField(blank=True, help_text='First family (if comparing families)', max_length=200, null=True)),
                ('order_1', models.CharField(blank=True, help_text='First order (if comparing orders)', max_length=200, null=True)),
                ('family_2', models.CharField(blank=True, help_text='Second family (if comparing families)', max_length=200, null=True)),
                ('order_2', models.CharField(blank=True, help_text='Second order (if comparing orders)', max_length=200, null=True)),
                ('summary', models.TextField(help_text='Brief summary of key differences')),
                ('detailed_comparison', models.TextField(help_text='Detailed comparison text generated by AI')),
                ('size_comparison', models.TextField(blank=True, null=True)),
                ('plumage_comparison', models.TextField(blank=True, null=True)),
                ('behavior_comparison', models.TextField(blank=True, null=True)),
                ('habitat_comparison', models.TextField(blank=True, null=True)),
                ('vocalization_comparison', models.TextField(blank=True, null=True)),
                ('identification_tips', models.TextField(blank=True, help_text='Tips for distinguishing between the two', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.CharField(default='gpt-4', help_text='AI model used for generation', max_length=100)),
                ('ai_prompt_version', models.CharField(default='v1', help_text='Version of the prompt used', max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this comparison has been manually verified')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score (0-1) if available', null=True)),
                ('species_1', models.ForeignKey(blank=True, help_text='First species (if comparing species)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='jizz.species')),
                ('species_2', models.ForeignKey(blank=True, help_text='Second species (if comparing species)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='jizz.species')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_type', models.CharField(max_length=50)),
                ('species_1_id', models.IntegerField(blank=True, null=True)),
                ('species_2_id', models.IntegerField(blank=True, null=True)),
                ('family_1', models.CharField(blank=True, max_length=200, null=True)),
                ('family_2', models.CharField(blank=True, max_length=200, null=True)),
                ('order_1', models.CharField(blank=True, max_length=200, null=True)),
                ('order_2', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='compare.speciescomparison')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested the comparison (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('size', 'Size'), ('plumage', 'Plumage'), ('behavior', 'Behavior'), ('habitat', 'Habitat'), ('distribution', 'Distribution'), ('diet', 'Diet'), ('vocalization', 'Vocalization'), ('identification', 'Identification'), ('similar_species', 'Similar Species'), ('measurements', 'Measurements'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(help_text='Short title/heading for this trait', max_length=200)),
                ('content', models.TextField(help_text='Detailed description of the trait')),
                ('source_url', models.URLField(blank=True, help_text='URL from Birds of the World', null=True)),
                ('section', models.CharField(blank=True, help_text="Section name from source (e.g., 'Identification', 'Plumages')", max_length=200, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this trait has been manually verified')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='jizz.species')),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['species', 'category'], name='compare_spe_species_3bbd32_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='speciescomparison',
            index=models.Index(fields=['species_1', 'species_2'], name='compare_spe_species_b55cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='speciescomparison',
            index=models.Index(fields=['comparison_type'], name='compare_spe_compari_f72ad5_idx'),
        ),
    ]
