# Generated by Django 4.2.3 on 2025-11-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescomparison',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', help_text='AI model used for generation', max_length=100),
        ),
    ]
