# Generated by Django 4.2.3 on 2026-08-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0130_feedback_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0002_alter_speciescomparison_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, default='')),
                ('identification_tips', models.TextField(blank=True, default='')),
                ('size_comparison', models.TextField(blank=True, default='')),
                ('plumage_comparison', models.TextField(blank=True, default='')),
                ('behavior_comparison', models.TextField(blank=True, default='')),
                ('habitat_comparison', models.TextField(blank=True, default='')),
                ('vocalization_comparison', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=True, help_text='Shown on the public compare page. Review can be added later.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comparisons', to=settings.AUTH_USER_MODEL)),
                ('species_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comparisons_as_high', to='jizz.species')),
                ('species_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comparisons_as_low', to='jizz.species')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddConstraint(
            model_name='communitycomparison',
            constraint=models.UniqueConstraint(fields=('species_low', 'species_high'), name='community_comparison_pair_uniq'),
        ),
    ]
