# Generated by Django 4.2.3 on 2023-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
    ]
