# Generated by Django 4.2.3 on 2023-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0002_species_alter_country_options_countryspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
