# Generated by Django 4.2.3 on 2023-07-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0004_auto_20230719_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['id'], 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizz.species')),
            ],
        ),
    ]
