# Generated by Django 4.2.3 on 2023-10-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0005_alter_country_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='codes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countryspecies',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='jizz.country'),
        ),
        migrations.AlterField(
            model_name='countryspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='jizz.species'),
        ),
        migrations.AlterField(
            model_name='speciesimage',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jizz.species'),
        ),
    ]
