# Generated by Django 4.2.3 on 2024-08-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0007_game_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.CharField(default='beginner', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jizz.game'),
        ),
        migrations.AlterField(
            model_name='question',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jizz.species'),
        ),
    ]
