# Generated by Django 4.2.3 on 2024-09-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0009_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
