# Generated by Django 4.2.3 on 2024-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0010_game_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
