# Generated by Django 4.2.3 on 2024-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0011_species_name_nl'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
