# Generated by Django 4.2.3 on 2024-09-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0012_game_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesSounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='jizz.species')),
            ],
        ),
    ]
