# Generated by Django 4.2.3 on 2024-09-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0013_speciessounds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeciesSounds',
            new_name='SpeciesSound',
        ),
    ]
