# Generated by Django 4.2.3 on 2024-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0016_remove_game_user_remove_player_answered_game_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
