# Generated by Django 4.2.3 on 2024-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0017_remove_game_host_player_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
