# Generated by Django 4.2.3 on 2024-10-07 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0019_alter_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
