# Generated by Django 4.2.3 on 2024-10-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0020_alter_player_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='code',
            new_name='token',
        ),
    ]
