# Generated by Django 4.2.3 on 2024-10-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0021_rename_code_player_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
    ]
