# Generated by Django 4.2.3 on 2024-10-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0022_game_multiplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
