# Generated by Django 4.2.3 on 2024-10-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0023_game_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct',
            new_name='done',
        ),
    ]
