# Generated by Django 4.2.3 on 2024-10-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0024_rename_correct_question_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publications',
            field=models.ManyToManyField(to='jizz.species'),
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
