# Generated by Django 4.2.3 on 2024-10-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0025_question_publications_delete_questionoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publications',
            new_name='options',
        ),
    ]
