# Generated by Django 4.2.3 on 2024-10-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0028_answer_correct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('player', 'question')},
        ),
    ]
