# Generated by Django 4.2.3 on 2024-10-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0029_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countryspecies',
            unique_together={('country', 'species')},
        ),
    ]
