# Generated by Django 4.2.3 on 2024-10-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0030_alter_countryspecies_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciesimage',
            unique_together={('species', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='speciessound',
            unique_together={('species', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='speciesvideo',
            unique_together={('species', 'url')},
        ),
    ]
