# Generated by Django 4.2.3 on 2024-10-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0031_alter_speciesimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
