# Generated by Django 4.2.3 on 2024-10-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0034_remove_game_code_alter_game_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_host',
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='jizz.player'),
        ),
    ]
