# Generated by Django 4.2.3 on 2024-10-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0035_remove_player_is_host_game_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jizz.player'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizz.question')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizz.species')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
