# Generated by Django 4.2.3 on 2024-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0036_remove_question_options_alter_answer_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(through='jizz.QuestionOption', to='jizz.species'),
        ),
    ]
