# Generated by Django 4.2.3 on 2024-10-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0037_question_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='option',
            new_name='question',
        ),
    ]
