# Generated by Django 4.2.3 on 2024-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0039_answer_created_answer_score_player_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
