# Generated by Django 4.2.3 on 2024-10-18 17:11

from django.db import migrations
from django.db.models import Sum


def migrate_scores(apps, schema_editor):
    Player = apps.get_model('jizz', 'Player')
    Game = apps.get_model('jizz', 'Game')
    PlayerScore = apps.get_model('jizz', 'PlayerScore')

    for player in Player.objects.all():
        game_ids = player.answers.values_list('question__game_id', flat=True)
        for game in Game.objects.filter(id__in=game_ids).all():
            score = player.answers.filter(question__game=game).aggregate(score=Sum('score'))['score']
            PlayerScore.objects.update_or_create(
                player=player,
                game=game,
                defaults={
                    "score": score
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0041_remove_player_game_alter_answer_question_playerscore'),
    ]

    operations = [
        migrations.RunPython(
            migrate_scores,
            migrations.RunPython.noop
        )
    ]
