# Generated by Django 4.2.3 on 2024-10-18 18:30

from django.db import migrations


def migrate_answers(apps, schema_editor):
    Answer = apps.get_model('jizz', 'Answer')
    PlayerScore = apps.get_model('jizz', 'PlayerScore')

    for answer in Answer.objects.all():
        player_score = PlayerScore.objects.filter(
            game=answer.question.game,
            player=answer.player
        ).first()
        if player_score:
            answer.player_score = player_score
            answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0043_alter_answer_unique_together_answer_player_score_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_answers,
            migrations.RunPython
        )
    ]
