# Generated by Django 4.2.3 on 2024-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0045_remove_answer_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='tax_family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='tax_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
