# Generated by Django 4.2.3 on 2024-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0046_species_tax_family_species_tax_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tax_order',
            field=models.CharField(blank=True, help_text='Only show birds from this order', max_length=100, null=True, verbose_name='Taxonomic order'),
        ),
        migrations.AlterField(
            model_name='species',
            name='tax_family',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='species',
            name='tax_order',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order'),
        ),
    ]
