# Generated by Django 4.2.3 on 2024-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0047_game_tax_order_alter_species_tax_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryspecies',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
