# Generated by Django 4.2.3 on 2024-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0048_countryspecies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='include_escapes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='include_rare',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='countryspecies',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('native', 'Native'), ('rare', 'Rare'), ('introduced', 'Introduced'), ('extirpated', 'Extirpated'), ('uncertain', 'Uncertain'), ('endemic', 'Endemic')], default='unknown', max_length=100),
        ),
    ]
