# Generated by Django 4.2.3 on 2024-10-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0049_game_include_escapes_game_include_rare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='jizz.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='jizz.question')),
            ],
        ),
    ]
