# Generated by Django 4.2.3 on 2024-11-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0050_flagquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jizz.player')),
            ],
        ),
        migrations.CreateModel(
            name='CountryChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='jizz.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='jizz.player')),
            ],
        ),
        migrations.CreateModel(
            name='CountryBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizz.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizz.player')),
            ],
        ),
    ]
