# Generated by Django 4.2.3 on 2025-02-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0054_update_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='tax_family_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Family english'),
        ),
    ]
