# Generated by Django 4.2.3 on 2025-03-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0054_update_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryspecies',
            options={'verbose_name': 'Country Species', 'verbose_name_plural': 'Country Species'},
        ),
        migrations.RemoveField(
            model_name='challengelevel',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengelevel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='challengelevel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='challengelevel',
            name='passed',
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='include_escapes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='include_rare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='media',
            field=models.CharField(default='images', max_length=10),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
    ]
