# Generated by Django 4.2.3 on 2025-03-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0057_challengelevel_tax_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrychallenge',
            name='level',
        ),
        migrations.CreateModel(
            name='CountryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('country_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='jizz.countrychallenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_games', to='jizz.game')),
            ],
        ),
    ]
