# Generated by Django 4.2.3 on 2025-03-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0058_remove_countrychallenge_level_countrygame'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrygame',
            name='challenge_level',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='country_games', to='jizz.challengelevel'),
            preserve_default=False,
        ),
    ]
