# Generated by Django 4.2.3 on 2025-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0059_countrygame_challenge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengelevel',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengelevel',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='advanced', max_length=20),
        ),
    ]
