# Generated by Django 4.2.3 on 2025-03-08 10:23

from django.db import migrations


def create_challenge_levels(apps, schema_editor):
    ChallengeLevel = apps.get_model('jizz', 'ChallengeLevel')
    ChallengeLevel.objects.all().delete()

    LEVELS = [
        {
            'sequence': 0,
            'level': 'beginner',
            'title': 'Beginner Bird Images',
            'description': 'Start with 10 common birds using images',
            'length': 10,
            'media': 'images',
            'jokers': 2,
            'include_rare': False,
            'include_escapes': False,
        },
        {
            'sequence': 1,
            'level': 'beginner',
            'title': 'Beginner Bird Videos',
            'description': 'Test your skills with 20 bird videos',
            'length': 20,
            'media': 'video',
            'jokers': 2,
            'include_rare': False,
            'include_escapes': False,
        },
        {
            'sequence': 2,
            'level': 'advanced',
            'title': 'Advanced Bird Images',
            'description': 'Challenge yourself with 20 bird images',
            'length': 20,
            'media': 'images',
            'jokers': 2,
            'include_rare': False,
            'include_escapes': False,
        },
        {
            'sequence': 3,
            'level': 'advanced',
            'title': 'Advanced Marathon',
            'description': '50 bird images including rare species',
            'length': 50,
            'media': 'images',
            'jokers': 5,
            'include_rare': True,
            'include_escapes': False,
        },
        {
            'sequence': 4,
            'level': 'advanced',
            'title': 'Advanced Video Sprint',
            'description': '10 bird videos including rare species',
            'length': 10,
            'media': 'videos',
            'jokers': 0,
            'include_rare': True,
            'include_escapes': False,
        },
        {
            'sequence': 5,
            'level': 'expert',
            'title': 'Expert Bird Images',
            'description': '20 challenging bird images',
            'length': 20,
            'media': 'images',
            'jokers': 2,
            'include_rare': True,
            'include_escapes': False,
        },
        {
            'sequence': 6,
            'level': 'advanced',
            'title': 'Advanced Bird Sounds',
            'description': '20 bird sounds including rare species',
            'length': 20,
            'media': 'sounds',
            'jokers': 5,
            'include_rare': True,
            'include_escapes': False,
        },
        {
            'sequence': 7,
            'level': 'expert',
            'title': 'Expert Bird Videos',
            'description': '20 challenging bird videos',
            'length': 20,
            'media': 'videos',
            'jokers': 1,
            'include_rare': True,
            'include_escapes': False,
        },
    ]

    for level_data in LEVELS:
        ChallengeLevel.objects.create(**level_data)


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0060_challengelevel_sequence_alter_challengelevel_level'),
    ]

    operations = [
        migrations.RunPython(create_challenge_levels, migrations.RunPython.noop),
    ]
