# Generated by Django 4.2.3 on 2025-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0061_auto_20250308_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrygame',
            name='passed',
        ),
        migrations.AddField(
            model_name='countrygame',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=10),
        ),
    ]
