# Generated by Django 4.2.3 on 2025-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0062_remove_countrygame_passed_countrygame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygame',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='new', max_length=10),
        ),
    ]
