# Generated by Django 4.2.3 on 2025-03-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0055_species_tax_family_en'),
        ('jizz', '0063_alter_countrygame_status'),
    ]

    operations = [
    ]
