# Generated by Django 4.2.3 on 2025-03-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0064_merge_20250309_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrygame',
            name='status',
        ),
    ]
