# Generated by Django 4.2.3 on 2025-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0065_remove_countrygame_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrygame',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='description_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='challengelevel',
            name='title_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
