# Generated by Django 4.2.3 on 2025-06-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0067_copy_challengelevel_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tax_family',
            field=models.CharField(blank=True, help_text='Only show birds from this family', max_length=100, null=True, verbose_name='Taxonomic family'),
        ),
    ]
