# Generated by Django 4.2.3 on 2025-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0069_language_alter_game_tax_family_alter_game_tax_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
