# Generated by Django 4.2.3 on 2025-11-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0071_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Preferred country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jizz.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='Preferred language', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_updates',
            field=models.BooleanField(default=False, help_text='Receive updates about Birdr app'),
        ),
    ]
