# Generated by Django 4.2.3 on 2025-11-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0072_add_user_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesimage',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_images', to='jizz.species'),
        ),
    ]
