# Generated by Django 4.2.3 on 2025-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0073_alter_speciesimage_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagquestion',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
