# Generated by Django 4.2.3 on 2025-11-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_remove_image_species_remove_video_species_and_more'),
        ('jizz', '0074_flagquestion_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagquestion',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='media.media'),
        ),
    ]
