# Generated by Django 4.2.3 on 2025-11-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0075_flagquestion_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagquestion',
            name='media',
        ),
    ]
