# Generated by Django 4.2.3 on 2026-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0076_remove_flagquestion_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='jizz.question'),
        ),
    ]
