# Generated by Django 4.2.3 on 2026-05-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0100_journey_level_step'),
        ('jizz', '0101_countryspecies_vagrant_and_native_default_frequency'),
    ]

    operations = [
    ]
