# Generated by Django 4.2.3 on 2025-11-18 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jizz', '0072_add_user_profile_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('wikimedia', 'Wikimedia'), ('inaturalist', 'iNaturalist'), ('youtube', 'YouTube CC'), ('eol', 'EOL')], default='', max_length=50)),
                ('contributor', models.CharField(blank=True, default='', max_length=200)),
                ('copyright', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='media/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_videos', to='jizz.species')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('inaturalist', 'iNaturalist'), ('wikimedia', 'Wikimedia'), ('gbif', 'GBIF'), ('flickr', 'Flickr CC'), ('eol', 'EOL'), ('observation', 'Observation.org')], default='', max_length=50)),
                ('contributor', models.CharField(blank=True, default='', max_length=200)),
                ('copyright', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='jizz.species')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('xeno_canto', 'Xeno-Canto')], default='', max_length=50)),
                ('contributor', models.CharField(blank=True, default='', max_length=200)),
                ('copyright', models.CharField(blank=True, default='', max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='media/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'flac'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_audio', to='jizz.species')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio',
                'ordering': ['-created'],
            },
        ),
    ]
