# Generated by Django 4.2.3 on 2025-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_audio_contributor_alter_audio_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, choices=[('inaturalist', 'iNaturalist'), ('wikimedia', 'Wikimedia'), ('gbif', 'GBIF'), ('flickr', 'Flickr CC'), ('eol', 'EOL'), ('observation', 'Observation.org')], default='', max_length=200),
        ),
    ]
