# Generated by Django 4.2.3 on 2025-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_image_link_alter_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
