# Generated by Django 4.2.3 on 2025-11-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0074_flagquestion_media_url'),
        ('media', '0004_audio_hide_audio_url_image_hide_image_url_video_hide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jizz.species'),
        ),
    ]
