# Generated by Django 4.2.3 on 2025-11-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0074_flagquestion_media_url'),
        ('media', '0005_alter_image_species'),
    ]

    operations = [
        # Rename Image model to Media
        migrations.RenameModel(
            old_name='Image',
            new_name='Media',
        ),
        # Add type field with default 'image' for existing records
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=200),
        ),
        # Update source choices to include all sources (xeno_canto added)
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.CharField(blank=True, choices=[('inaturalist', 'iNaturalist'), ('wikimedia', 'Wikimedia'), ('gbif', 'GBIF'), ('flickr', 'Flickr CC'), ('observation', 'Observation.org'), ('xeno_canto', 'Xeno-Canto')], default='', max_length=200),
        ),
        # Remove the old media ImageField (file upload field) if it exists
        migrations.RemoveField(
            model_name='media',
            name='media',
        ),
        # Update Meta options
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        # Delete Video and Audio models
        migrations.RemoveField(
            model_name='video',
            name='species',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='species',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
