# Generated by Django 4.2.3 on 2025-11-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0076_remove_flagquestion_media'),
        ('media', '0006_media_remove_image_species_remove_video_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='media.media')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_flags', to='jizz.player')),
            ],
            options={
                'verbose_name': 'Media Flag',
                'verbose_name_plural': 'Media Flags',
                'ordering': ['-created'],
            },
        ),
    ]
