# Generated by Django 4.2.3 on 2025-11-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0076_remove_flagquestion_media'),
        ('media', '0007_mediaflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='media.media')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reviews', to='jizz.player')),
            ],
            options={
                'verbose_name': 'Media Review',
                'verbose_name_plural': 'Media Reviews',
                'ordering': ['-created'],
                'unique_together': {('media', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='MediaFlag',
        ),
    ]
