# Generated by Django 4.2.3 on 2025-12-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_mediareview_delete_mediaflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='copyright',
        ),
        migrations.AddField(
            model_name='media',
            name='copyright_standardized',
            field=models.CharField(blank=True, default='', help_text='Standardized copyright notation (e.g., CC BY, CC BY-NC, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='copyright_text',
            field=models.CharField(blank=True, default='', help_text='Copyright text as received from scraper', max_length=500),
        ),
        migrations.AddField(
            model_name='media',
            name='non_commercial_only',
            field=models.BooleanField(default=False, help_text='If checked, media is for non-commercial use only. If unchecked, media is free to use with attribution.'),
        ),
        migrations.AlterField(
            model_name='mediareview',
            name='review_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('not_sure', 'Not Sure')], max_length=20),
        ),
    ]
