# Generated by Django 4.2.3 on 2026-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizz', '0077_alter_flagquestion_question'),
        ('media', '0009_remove_media_copyright_media_copyright_standardized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jizz.species'),
        ),
        migrations.CreateModel(
            name='FlagMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='media.media')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_flags', to='jizz.player')),
            ],
            options={
                'verbose_name': 'Flagged Media',
                'verbose_name_plural': 'Flagged Media',
                'ordering': ['-created'],
                'unique_together': {('media', 'player')},
            },
        ),
    ]
