# Generated by Django 4.2.3 on 2026-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_mediareview_user_player_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='contributor',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='media',
            name='copyright_text',
            field=models.CharField(blank=True, default='', help_text='Copyright text as received from scraper', max_length=2000),
        ),
    ]
