from django.db import models
from jizz.models import Species


class SpeciesTrait(models.Model):
    """
    Stores extracted traits and characteristics of a species from Birds of the World.
    Each trait represents a specific aspect like size, plumage, behavior, etc.
    """
    species = models.ForeignKey(Species, on_delete=models.CASCADE, related_name='traits')
    
    # Trait categories
    CATEGORY_CHOICES = [
        ('size', 'Size'),
        ('plumage', 'Plumage'),
        ('behavior', 'Behavior'),
        ('habitat', 'Habitat'),
        ('distribution', 'Distribution'),
        ('diet', 'Diet'),
        ('vocalization', 'Vocalization'),
        ('identification', 'Identification'),
        ('similar_species', 'Similar Species'),
        ('measurements', 'Measurements'),
        ('other', 'Other'),
    ]
    
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='other')
    title = models.CharField(max_length=200, help_text="Short title/heading for this trait")
    content = models.TextField(help_text="Detailed description of the trait")
    
    # Source information
    source_url = models.URLField(null=True, blank=True, help_text="URL from Birds of the World")
    section = models.CharField(max_length=200, null=True, blank=True, help_text="Section name from source (e.g., 'Identification', 'Plumages')")
    
    # Metadata
    extracted_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_verified = models.BooleanField(default=False, help_text="Whether this trait has been manually verified")
    
    class Meta:
        ordering = ['category', 'title']
        indexes = [
            models.Index(fields=['species', 'category']),
        ]
    
    def __str__(self):
        return f"{self.species.name} - {self.category}: {self.title}"


class SpeciesComparison(models.Model):
    """
    Stores AI-generated comparisons between two species, families, or orders.
    """
    # Comparison type
    COMPARISON_TYPE_CHOICES = [
        ('species', 'Species vs Species'),
        ('family', 'Family vs Family'),
        ('order', 'Order vs Order'),
        ('species_family', 'Species vs Family'),
        ('species_order', 'Species vs Order'),
    ]
    
    comparison_type = models.CharField(max_length=50, choices=COMPARISON_TYPE_CHOICES)
    
    # First entity (can be species, family, or order)
    species_1 = models.ForeignKey(
        Species, 
        on_delete=models.CASCADE, 
        related_name='comparisons_as_first',
        null=True, 
        blank=True,
        help_text="First species (if comparing species)"
    )
    family_1 = models.CharField(max_length=200, null=True, blank=True, help_text="First family (if comparing families)")
    order_1 = models.CharField(max_length=200, null=True, blank=True, help_text="First order (if comparing orders)")
    
    # Second entity
    species_2 = models.ForeignKey(
        Species, 
        on_delete=models.CASCADE, 
        related_name='comparisons_as_second',
        null=True, 
        blank=True,
        help_text="Second species (if comparing species)"
    )
    family_2 = models.CharField(max_length=200, null=True, blank=True, help_text="Second family (if comparing families)")
    order_2 = models.CharField(max_length=200, null=True, blank=True, help_text="Second order (if comparing orders)")
    
    # Comparison content
    summary = models.TextField(help_text="Brief summary of key differences")
    detailed_comparison = models.TextField(help_text="Detailed comparison text generated by AI")
    
    # Comparison sections (structured data)
    size_comparison = models.TextField(null=True, blank=True)
    plumage_comparison = models.TextField(null=True, blank=True)
    behavior_comparison = models.TextField(null=True, blank=True)
    habitat_comparison = models.TextField(null=True, blank=True)
    vocalization_comparison = models.TextField(null=True, blank=True)
    identification_tips = models.TextField(null=True, blank=True, help_text="Tips for distinguishing between the two")
    
    # Metadata
    generated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    ai_model = models.CharField(max_length=100, default='gpt-4o-mini', help_text="AI model used for generation")
    ai_prompt_version = models.CharField(max_length=50, default='v1', help_text="Version of the prompt used")
    is_verified = models.BooleanField(default=False, help_text="Whether this comparison has been manually verified")
    quality_score = models.FloatField(null=True, blank=True, help_text="Quality score (0-1) if available")
    
    class Meta:
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['species_1', 'species_2']),
            models.Index(fields=['comparison_type']),
        ]
        # Note: unique_together constraints are handled at the application level
        # since we have different comparison types with different field combinations
    
    def __str__(self):
        if self.comparison_type == 'species' and self.species_1 and self.species_2:
            return f"{self.species_1.name} vs {self.species_2.name}"
        elif self.comparison_type == 'family' and self.family_1 and self.family_2:
            return f"{self.family_1} vs {self.family_2}"
        elif self.comparison_type == 'order' and self.order_1 and self.order_2:
            return f"{self.order_1} vs {self.order_2}"
        return f"Comparison {self.id}"


class ComparisonRequest(models.Model):
    """
    Tracks requests for generating comparisons (for analytics and caching).
    """
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    comparison = models.ForeignKey(
        SpeciesComparison, 
        on_delete=models.CASCADE, 
        related_name='requests',
        null=True,
        blank=True
    )
    
    # Request parameters
    comparison_type = models.CharField(max_length=50)
    species_1_id = models.IntegerField(null=True, blank=True)
    species_2_id = models.IntegerField(null=True, blank=True)
    family_1 = models.CharField(max_length=200, null=True, blank=True)
    family_2 = models.CharField(max_length=200, null=True, blank=True)
    order_1 = models.CharField(max_length=200, null=True, blank=True)
    order_2 = models.CharField(max_length=200, null=True, blank=True)
    
    # Status tracking
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    error_message = models.TextField(null=True, blank=True)
    
    # Metadata
    requested_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    requested_by = models.ForeignKey(
        'auth.User',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="User who requested the comparison (if authenticated)"
    )
    
    class Meta:
        ordering = ['-requested_at']
    
    def __str__(self):
        return f"Comparison request {self.id} - {self.status}"

